// ¡Hablemos! カリキュラムデータ
// 6ヶ月 / 6フェーズ / 24ユニット — 会話特化(単語・リスニング・スピーキング)
// 各アイテム: es = スペイン語, en = 英語, ja = 日本語

const CURRICULUM = [
  {
    phase: 1,
    title: "サバイバル基礎",
    en: "Survival Basics",
    month: "1ヶ月目",
    color: "#e63946",
    units: [
      {
        id: "u1", icon: "👋", title: "あいさつ", en: "Greetings",
        words: [
          { es: "hola", en: "hello / hi", ja: "こんにちは、やあ" },
          { es: "buenos días", en: "good morning", ja: "おはよう" },
          { es: "buenas tardes", en: "good afternoon", ja: "こんにちは(午後)" },
          { es: "buenas noches", en: "good evening / good night", ja: "こんばんは、おやすみ" },
          { es: "adiós", en: "goodbye", ja: "さようなら" },
          { es: "hasta luego", en: "see you later", ja: "またね、また後で" },
          { es: "gracias", en: "thank you", ja: "ありがとう" },
          { es: "de nada", en: "you're welcome", ja: "どういたしまして" },
          { es: "por favor", en: "please", ja: "お願いします" },
          { es: "perdón", en: "sorry / excuse me", ja: "ごめんなさい、すみません" },
          { es: "sí", en: "yes", ja: "はい" },
          { es: "no", en: "no", ja: "いいえ" },
        ],
        phrases: [
          { es: "¿Cómo estás?", en: "How are you?", ja: "元気?" },
          { es: "Muy bien, ¿y tú?", en: "Very well, and you?", ja: "とても元気だよ、君は?" },
          { es: "Mucho gusto.", en: "Nice to meet you.", ja: "はじめまして" },
          { es: "¿Qué tal?", en: "What's up? / How's it going?", ja: "調子どう?" },
          { es: "Nos vemos.", en: "See you.", ja: "じゃあね" },
          { es: "Que tengas un buen día.", en: "Have a nice day.", ja: "良い一日を" },
        ],
      },
      {
        id: "u2", icon: "🙋", title: "自己紹介", en: "Introducing Yourself",
        words: [
          { es: "el nombre", en: "name", ja: "名前" },
          { es: "el país", en: "country", ja: "国" },
          { es: "Japón", en: "Japan", ja: "日本" },
          { es: "japonés / japonesa", en: "Japanese (man / woman)", ja: "日本人(男性/女性)" },
          { es: "el amigo / la amiga", en: "friend (male / female)", ja: "友達(男性/女性)" },
          { es: "el/la estudiante", en: "student", ja: "学生" },
          { es: "el trabajo", en: "work / job", ja: "仕事" },
          { es: "la casa", en: "house / home", ja: "家" },
          { es: "el idioma", en: "language", ja: "言語" },
          { es: "el español", en: "Spanish (language)", ja: "スペイン語" },
          { es: "el inglés", en: "English (language)", ja: "英語" },
          { es: "vivir", en: "to live", ja: "住む、生きる" },
        ],
        phrases: [
          { es: "Me llamo Ken.", en: "My name is Ken.", ja: "私の名前はケンです" },
          { es: "¿Cómo te llamas?", en: "What's your name?", ja: "名前は何ていうの?" },
          { es: "Soy de Japón.", en: "I'm from Japan.", ja: "日本出身です" },
          { es: "Vivo en Tokio.", en: "I live in Tokyo.", ja: "東京に住んでいます" },
          { es: "Estoy aprendiendo español.", en: "I'm learning Spanish.", ja: "スペイン語を勉強中です" },
          { es: "¿De dónde eres?", en: "Where are you from?", ja: "どこ出身?" },
        ],
      },
      {
        id: "u3", icon: "🔢", title: "数字と年齢", en: "Numbers & Age",
        words: [
          { es: "uno", en: "one", ja: "1" },
          { es: "dos", en: "two", ja: "2" },
          { es: "tres", en: "three", ja: "3" },
          { es: "cuatro", en: "four", ja: "4" },
          { es: "cinco", en: "five", ja: "5" },
          { es: "seis", en: "six", ja: "6" },
          { es: "siete", en: "seven", ja: "7" },
          { es: "ocho", en: "eight", ja: "8" },
          { es: "nueve", en: "nine", ja: "9" },
          { es: "diez", en: "ten", ja: "10" },
          { es: "quince", en: "fifteen", ja: "15" },
          { es: "veinte", en: "twenty", ja: "20" },
        ],
        phrases: [
          { es: "¿Cuántos años tienes?", en: "How old are you?", ja: "何歳?" },
          { es: "Tengo treinta años.", en: "I'm thirty years old.", ja: "30歳です" },
          { es: "¿Cuál es tu número de teléfono?", en: "What's your phone number?", ja: "電話番号は何番?" },
          { es: "¿Cuánto es?", en: "How much is it?", ja: "いくらですか?" },
          { es: "Son diez euros.", en: "It's ten euros.", ja: "10ユーロです" },
          { es: "Un momento, por favor.", en: "One moment, please.", ja: "ちょっと待ってください" },
        ],
      },
      {
        id: "u4", icon: "👨‍👩‍👧", title: "家族", en: "Family",
        words: [
          { es: "la familia", en: "family", ja: "家族" },
          { es: "la madre / mamá", en: "mother / mom", ja: "母、ママ" },
          { es: "el padre / papá", en: "father / dad", ja: "父、パパ" },
          { es: "los padres", en: "parents", ja: "両親" },
          { es: "el hermano", en: "brother", ja: "兄、弟" },
          { es: "la hermana", en: "sister", ja: "姉、妹" },
          { es: "el hijo", en: "son", ja: "息子" },
          { es: "la hija", en: "daughter", ja: "娘" },
          { es: "el abuelo", en: "grandfather", ja: "祖父" },
          { es: "la abuela", en: "grandmother", ja: "祖母" },
          { es: "el esposo / marido", en: "husband", ja: "夫" },
          { es: "la esposa / mujer", en: "wife", ja: "妻" },
        ],
        phrases: [
          { es: "¿Tienes hermanos?", en: "Do you have siblings?", ja: "兄弟はいる?" },
          { es: "Tengo dos hermanos.", en: "I have two brothers.", ja: "兄弟が2人います" },
          { es: "Esta es mi madre.", en: "This is my mother.", ja: "こちらは私の母です" },
          { es: "Mi familia es grande.", en: "My family is big.", ja: "私の家族は大家族です" },
          { es: "Quiero mucho a mi familia.", en: "I love my family very much.", ja: "家族が大好きです" },
          { es: "¿Estás casado?", en: "Are you married?", ja: "結婚してる?" },
        ],
      },
    ],
  },
  {
    phase: 2,
    title: "日常の基本",
    en: "Everyday Basics",
    month: "2ヶ月目",
    color: "#f77f00",
    units: [
      {
        id: "u5", icon: "🍎", title: "食べ物・飲み物", en: "Food & Drinks",
        words: [
          { es: "el agua", en: "water", ja: "水" },
          { es: "el café", en: "coffee", ja: "コーヒー" },
          { es: "el té", en: "tea", ja: "お茶、紅茶" },
          { es: "la leche", en: "milk", ja: "牛乳" },
          { es: "el pan", en: "bread", ja: "パン" },
          { es: "el arroz", en: "rice", ja: "米、ご飯" },
          { es: "la carne", en: "meat", ja: "肉" },
          { es: "el pollo", en: "chicken", ja: "鶏肉、チキン" },
          { es: "el pescado", en: "fish (as food)", ja: "魚(食材)" },
          { es: "la fruta", en: "fruit", ja: "果物" },
          { es: "la verdura", en: "vegetable", ja: "野菜" },
          { es: "la cerveza", en: "beer", ja: "ビール" },
        ],
        phrases: [
          { es: "Tengo hambre.", en: "I'm hungry.", ja: "お腹すいた" },
          { es: "Tengo sed.", en: "I'm thirsty.", ja: "喉が渇いた" },
          { es: "¿Qué quieres comer?", en: "What do you want to eat?", ja: "何食べたい?" },
          { es: "Me gusta el café.", en: "I like coffee.", ja: "コーヒーが好きです" },
          { es: "¡Está muy rico!", en: "It's delicious!", ja: "すごくおいしい!" },
          { es: "No me gusta el pescado.", en: "I don't like fish.", ja: "魚は好きじゃない" },
        ],
      },
      {
        id: "u6", icon: "🍽️", title: "レストランで", en: "At the Restaurant",
        words: [
          { es: "el restaurante", en: "restaurant", ja: "レストラン" },
          { es: "el menú", en: "menu", ja: "メニュー" },
          { es: "la mesa", en: "table", ja: "テーブル" },
          { es: "el camarero / mesero", en: "waiter", ja: "ウェイター、店員" },
          { es: "la cuenta", en: "the bill / check", ja: "お会計" },
          { es: "el plato", en: "plate / dish", ja: "皿、料理" },
          { es: "el vaso", en: "glass (for drinking)", ja: "コップ、グラス" },
          { es: "el desayuno", en: "breakfast", ja: "朝食" },
          { es: "el almuerzo", en: "lunch", ja: "昼食" },
          { es: "la cena", en: "dinner", ja: "夕食" },
          { es: "el postre", en: "dessert", ja: "デザート" },
          { es: "la propina", en: "tip (money)", ja: "チップ" },
        ],
        phrases: [
          { es: "Una mesa para dos, por favor.", en: "A table for two, please.", ja: "2名席をお願いします" },
          { es: "¿Qué me recomienda?", en: "What do you recommend?", ja: "おすすめは何ですか?" },
          { es: "Quiero esto, por favor.", en: "I want this, please.", ja: "これをください" },
          { es: "La cuenta, por favor.", en: "The check, please.", ja: "お会計お願いします" },
          { es: "¿Puedo pagar con tarjeta?", en: "Can I pay by card?", ja: "カードで払えますか?" },
          { es: "¡Buen provecho!", en: "Enjoy your meal!", ja: "召し上がれ!(食事を楽しんで)" },
        ],
      },
      {
        id: "u7", icon: "🕐", title: "時間と曜日", en: "Time & Days",
        words: [
          { es: "la hora", en: "hour / time", ja: "時間、〜時" },
          { es: "el día", en: "day", ja: "日、一日" },
          { es: "la semana", en: "week", ja: "週" },
          { es: "el lunes", en: "Monday", ja: "月曜日" },
          { es: "el martes", en: "Tuesday", ja: "火曜日" },
          { es: "el miércoles", en: "Wednesday", ja: "水曜日" },
          { es: "el jueves", en: "Thursday", ja: "木曜日" },
          { es: "el viernes", en: "Friday", ja: "金曜日" },
          { es: "el sábado", en: "Saturday", ja: "土曜日" },
          { es: "el domingo", en: "Sunday", ja: "日曜日" },
          { es: "hoy", en: "today", ja: "今日" },
          { es: "mañana", en: "tomorrow / morning", ja: "明日、朝" },
        ],
        phrases: [
          { es: "¿Qué hora es?", en: "What time is it?", ja: "今何時?" },
          { es: "Son las tres.", en: "It's three o'clock.", ja: "3時です" },
          { es: "¿Qué día es hoy?", en: "What day is it today?", ja: "今日は何曜日?" },
          { es: "Hoy es lunes.", en: "Today is Monday.", ja: "今日は月曜日です" },
          { es: "Hasta mañana.", en: "See you tomorrow.", ja: "また明日" },
          { es: "Es tarde.", en: "It's late.", ja: "もう遅い時間だ" },
        ],
      },
      {
        id: "u8", icon: "🏃", title: "毎日の動作", en: "Daily Actions",
        words: [
          { es: "comer", en: "to eat", ja: "食べる" },
          { es: "beber", en: "to drink", ja: "飲む" },
          { es: "dormir", en: "to sleep", ja: "眠る" },
          { es: "trabajar", en: "to work", ja: "働く" },
          { es: "estudiar", en: "to study", ja: "勉強する" },
          { es: "ir", en: "to go", ja: "行く" },
          { es: "venir", en: "to come", ja: "来る" },
          { es: "hacer", en: "to do / to make", ja: "する、作る" },
          { es: "ver", en: "to see / to watch", ja: "見る" },
          { es: "escuchar", en: "to listen", ja: "聞く" },
          { es: "hablar", en: "to speak / to talk", ja: "話す" },
          { es: "cocinar", en: "to cook", ja: "料理する" },
        ],
        phrases: [
          { es: "Me levanto a las siete.", en: "I get up at seven.", ja: "7時に起きます" },
          { es: "Trabajo de nueve a cinco.", en: "I work from nine to five.", ja: "9時から5時まで働きます" },
          { es: "¿Qué haces?", en: "What are you doing?", ja: "何してるの?" },
          { es: "Voy al gimnasio.", en: "I'm going to the gym.", ja: "ジムに行きます" },
          { es: "Estoy cansado.", en: "I'm tired.", ja: "疲れた" },
          { es: "Me acuesto tarde.", en: "I go to bed late.", ja: "寝るのが遅いです" },
        ],
      },
    ],
  },
  {
    phase: 3,
    title: "街へ出よう",
    en: "Out in Town",
    month: "3ヶ月目",
    color: "#fcbf49",
    units: [
      {
        id: "u9", icon: "🗺️", title: "場所と道案内", en: "Places & Directions",
        words: [
          { es: "la ciudad", en: "city", ja: "街、都市" },
          { es: "la calle", en: "street", ja: "通り、道" },
          { es: "el banco", en: "bank", ja: "銀行" },
          { es: "el hospital", en: "hospital", ja: "病院" },
          { es: "la escuela", en: "school", ja: "学校" },
          { es: "la tienda", en: "store / shop", ja: "店" },
          { es: "el baño", en: "bathroom / toilet", ja: "トイレ" },
          { es: "la estación", en: "station", ja: "駅" },
          { es: "aquí", en: "here", ja: "ここ" },
          { es: "allí", en: "there", ja: "あそこ" },
          { es: "la derecha", en: "right (direction)", ja: "右" },
          { es: "la izquierda", en: "left (direction)", ja: "左" },
        ],
        phrases: [
          { es: "¿Dónde está el baño?", en: "Where is the bathroom?", ja: "トイレはどこですか?" },
          { es: "Está a la derecha.", en: "It's on the right.", ja: "右側にあります" },
          { es: "Sigue todo recto.", en: "Go straight ahead.", ja: "まっすぐ行って" },
          { es: "Está cerca de aquí.", en: "It's near here.", ja: "ここから近いです" },
          { es: "Está lejos.", en: "It's far.", ja: "遠いです" },
          { es: "Estoy perdido.", en: "I'm lost.", ja: "道に迷いました" },
        ],
      },
      {
        id: "u10", icon: "🛍️", title: "買い物とお金", en: "Shopping & Money",
        words: [
          { es: "el dinero", en: "money", ja: "お金" },
          { es: "el precio", en: "price", ja: "値段" },
          { es: "barato", en: "cheap", ja: "安い" },
          { es: "caro", en: "expensive", ja: "高い(値段)" },
          { es: "la tarjeta", en: "card", ja: "カード" },
          { es: "el efectivo", en: "cash", ja: "現金" },
          { es: "la ropa", en: "clothes", ja: "服" },
          { es: "la camisa", en: "shirt", ja: "シャツ" },
          { es: "los zapatos", en: "shoes", ja: "靴" },
          { es: "la talla", en: "size (clothing)", ja: "サイズ(服)" },
          { es: "cien", en: "one hundred", ja: "100" },
          { es: "mil", en: "one thousand", ja: "1000" },
        ],
        phrases: [
          { es: "¿Cuánto cuesta?", en: "How much does it cost?", ja: "いくらですか?" },
          { es: "Es muy caro.", en: "It's very expensive.", ja: "高すぎます" },
          { es: "¿Tiene una talla más grande?", en: "Do you have a bigger size?", ja: "もっと大きいサイズありますか?" },
          { es: "Me lo llevo.", en: "I'll take it.", ja: "これください(買います)" },
          { es: "Solo estoy mirando.", en: "I'm just looking.", ja: "見てるだけです" },
          { es: "¿Hay descuento?", en: "Is there a discount?", ja: "割引ありますか?" },
        ],
      },
      {
        id: "u11", icon: "🚌", title: "乗り物・移動", en: "Transport & Travel",
        words: [
          { es: "el coche / carro", en: "car", ja: "車" },
          { es: "el autobús", en: "bus", ja: "バス" },
          { es: "el tren", en: "train", ja: "電車" },
          { es: "el metro", en: "subway / metro", ja: "地下鉄" },
          { es: "el avión", en: "airplane", ja: "飛行機" },
          { es: "el taxi", en: "taxi", ja: "タクシー" },
          { es: "la bicicleta", en: "bicycle", ja: "自転車" },
          { es: "el billete / boleto", en: "ticket", ja: "切符、チケット" },
          { es: "el aeropuerto", en: "airport", ja: "空港" },
          { es: "la parada", en: "(bus) stop", ja: "停留所" },
          { es: "el viaje", en: "trip / journey", ja: "旅行" },
          { es: "la maleta", en: "suitcase", ja: "スーツケース" },
        ],
        phrases: [
          { es: "¿Dónde está la parada de autobús?", en: "Where is the bus stop?", ja: "バス停はどこですか?" },
          { es: "Un billete para Madrid, por favor.", en: "One ticket to Madrid, please.", ja: "マドリッド行きの切符を1枚ください" },
          { es: "¿A qué hora sale el tren?", en: "What time does the train leave?", ja: "電車は何時に出ますか?" },
          { es: "Voy al aeropuerto.", en: "I'm going to the airport.", ja: "空港に行きます" },
          { es: "¿Cuánto tarda?", en: "How long does it take?", ja: "どのくらいかかりますか?" },
          { es: "Ya llegamos.", en: "We've arrived.", ja: "着いたよ" },
        ],
      },
      {
        id: "u12", icon: "☀️", title: "天気と季節", en: "Weather & Seasons",
        words: [
          { es: "el tiempo", en: "weather / time", ja: "天気、時間" },
          { es: "el sol", en: "sun", ja: "太陽" },
          { es: "la lluvia", en: "rain", ja: "雨" },
          { es: "la nieve", en: "snow", ja: "雪" },
          { es: "el viento", en: "wind", ja: "風" },
          { es: "la nube", en: "cloud", ja: "雲" },
          { es: "el calor", en: "heat", ja: "暑さ" },
          { es: "el frío", en: "cold (noun)", ja: "寒さ" },
          { es: "el verano", en: "summer", ja: "夏" },
          { es: "el invierno", en: "winter", ja: "冬" },
          { es: "la primavera", en: "spring (season)", ja: "春" },
          { es: "el otoño", en: "autumn / fall", ja: "秋" },
        ],
        phrases: [
          { es: "¿Qué tiempo hace?", en: "What's the weather like?", ja: "天気はどう?" },
          { es: "Hace calor.", en: "It's hot.", ja: "暑いです" },
          { es: "Hace frío.", en: "It's cold.", ja: "寒いです" },
          { es: "Está lloviendo.", en: "It's raining.", ja: "雨が降っています" },
          { es: "¡Qué buen día!", en: "What a nice day!", ja: "なんていい天気!" },
          { es: "Va a llover mañana.", en: "It's going to rain tomorrow.", ja: "明日は雨が降りそう" },
        ],
      },
    ],
  },
  {
    phase: 4,
    title: "気持ちを伝える",
    en: "Expressing Yourself",
    month: "4ヶ月目",
    color: "#2a9d8f",
    units: [
      {
        id: "u13", icon: "💚", title: "感情と体調", en: "Feelings & Health",
        words: [
          { es: "feliz", en: "happy", ja: "幸せな、うれしい" },
          { es: "triste", en: "sad", ja: "悲しい" },
          { es: "enojado / enfadado", en: "angry", ja: "怒っている" },
          { es: "nervioso", en: "nervous", ja: "緊張している" },
          { es: "cansado", en: "tired", ja: "疲れている" },
          { es: "enfermo", en: "sick / ill", ja: "病気の、具合が悪い" },
          { es: "el dolor", en: "pain / ache", ja: "痛み" },
          { es: "la cabeza", en: "head", ja: "頭" },
          { es: "el estómago", en: "stomach", ja: "お腹、胃" },
          { es: "la fiebre", en: "fever", ja: "熱" },
          { es: "el médico", en: "doctor", ja: "医者" },
          { es: "la farmacia", en: "pharmacy", ja: "薬局" },
        ],
        phrases: [
          { es: "¿Cómo te sientes?", en: "How do you feel?", ja: "気分はどう?" },
          { es: "Me duele la cabeza.", en: "My head hurts.", ja: "頭が痛い" },
          { es: "Estoy resfriado.", en: "I have a cold.", ja: "風邪をひきました" },
          { es: "Necesito un médico.", en: "I need a doctor.", ja: "医者が必要です" },
          { es: "No te preocupes.", en: "Don't worry.", ja: "心配しないで" },
          { es: "Ya me siento mejor.", en: "I feel better now.", ja: "もう良くなりました" },
        ],
      },
      {
        id: "u14", icon: "🎸", title: "好き嫌いと趣味", en: "Likes & Hobbies",
        words: [
          { es: "la música", en: "music", ja: "音楽" },
          { es: "la película", en: "movie / film", ja: "映画" },
          { es: "el deporte", en: "sport", ja: "スポーツ" },
          { es: "el fútbol", en: "soccer / football", ja: "サッカー" },
          { es: "el libro", en: "book", ja: "本" },
          { es: "el juego", en: "game", ja: "ゲーム、遊び" },
          { es: "bailar", en: "to dance", ja: "踊る" },
          { es: "cantar", en: "to sing", ja: "歌う" },
          { es: "la fiesta", en: "party", ja: "パーティー" },
          { es: "la playa", en: "beach", ja: "ビーチ、海辺" },
          { es: "la montaña", en: "mountain", ja: "山" },
          { es: "la foto", en: "photo", ja: "写真" },
        ],
        phrases: [
          { es: "¿Qué te gusta hacer?", en: "What do you like to do?", ja: "何をするのが好き?" },
          { es: "Me encanta bailar.", en: "I love dancing.", ja: "踊るのが大好き" },
          { es: "¿Quieres ir al cine?", en: "Do you want to go to the movies?", ja: "映画観に行かない?" },
          { es: "¡Suena divertido!", en: "Sounds fun!", ja: "楽しそう!" },
          { es: "Prefiero quedarme en casa.", en: "I prefer to stay home.", ja: "家にいる方がいいな" },
          { es: "Juego al fútbol los domingos.", en: "I play soccer on Sundays.", ja: "日曜日にサッカーをします" },
        ],
      },
      {
        id: "u15", icon: "🙏", title: "お願いと頼みごと", en: "Requests & Favors",
        words: [
          { es: "la ayuda", en: "help", ja: "助け、手伝い" },
          { es: "el favor", en: "favor", ja: "お願い、頼みごと" },
          { es: "el momento", en: "moment", ja: "瞬間、ちょっとの間" },
          { es: "el problema", en: "problem", ja: "問題" },
          { es: "la pregunta", en: "question", ja: "質問" },
          { es: "la respuesta", en: "answer", ja: "答え" },
          { es: "la cosa", en: "thing", ja: "物、こと" },
          { es: "algo", en: "something", ja: "何か" },
          { es: "nada", en: "nothing", ja: "何も(〜ない)" },
          { es: "todo", en: "everything / all", ja: "全部、すべて" },
          { es: "otra vez", en: "again / one more time", ja: "もう一度" },
          { es: "despacio", en: "slowly", ja: "ゆっくり" },
        ],
        phrases: [
          { es: "¿Me puedes ayudar?", en: "Can you help me?", ja: "手伝ってくれる?" },
          { es: "¿Puedo pasar?", en: "May I come in / pass?", ja: "入っていい?(通っていい?)" },
          { es: "¿Me pasas la sal?", en: "Can you pass me the salt?", ja: "塩を取ってくれる?" },
          { es: "No hay problema.", en: "No problem.", ja: "問題ないよ" },
          { es: "¿Puedes hablar más despacio?", en: "Can you speak more slowly?", ja: "もっとゆっくり話してくれる?" },
          { es: "Tengo una pregunta.", en: "I have a question.", ja: "質問があります" },
        ],
      },
      {
        id: "u16", icon: "⏪", title: "過去の話をする", en: "Talking About the Past",
        words: [
          { es: "ayer", en: "yesterday", ja: "昨日" },
          { es: "anoche", en: "last night", ja: "昨夜" },
          { es: "la semana pasada", en: "last week", ja: "先週" },
          { es: "el año pasado", en: "last year", ja: "去年" },
          { es: "antes", en: "before", ja: "前に、以前" },
          { es: "después", en: "after / later", ja: "後で、その後" },
          { es: "entonces", en: "then / so", ja: "それで、その時" },
          { es: "ya", en: "already", ja: "もう、すでに" },
          { es: "todavía", en: "still / yet", ja: "まだ" },
          { es: "nunca", en: "never", ja: "決して〜ない" },
          { es: "siempre", en: "always", ja: "いつも" },
          { es: "una vez", en: "once / one time", ja: "一度、一回" },
        ],
        phrases: [
          { es: "¿Qué hiciste ayer?", en: "What did you do yesterday?", ja: "昨日何した?" },
          { es: "Fui al cine.", en: "I went to the movies.", ja: "映画館に行きました" },
          { es: "Comí paella.", en: "I ate paella.", ja: "パエリアを食べました" },
          { es: "Fue increíble.", en: "It was incredible.", ja: "最高だった" },
          { es: "Lo pasé muy bien.", en: "I had a great time.", ja: "とても楽しかった" },
          { es: "No hice nada.", en: "I didn't do anything.", ja: "何もしなかった" },
        ],
      },
    ],
  },
  {
    phase: 5,
    title: "会話を広げる",
    en: "Expanding Conversations",
    month: "5ヶ月目",
    color: "#457b9d",
    units: [
      {
        id: "u17", icon: "🔮", title: "予定と未来", en: "Plans & Future",
        words: [
          { es: "próximo", en: "next", ja: "次の" },
          { es: "el plan", en: "plan", ja: "計画、予定" },
          { es: "la cita", en: "appointment / date", ja: "約束、デート" },
          { es: "las vacaciones", en: "vacation / holidays", ja: "休暇、バカンス" },
          { es: "el fin de semana", en: "weekend", ja: "週末" },
          { es: "pronto", en: "soon", ja: "もうすぐ、すぐに" },
          { es: "luego", en: "later / then", ja: "後で" },
          { es: "quizás", en: "maybe / perhaps", ja: "たぶん、もしかしたら" },
          { es: "seguro", en: "sure / safe", ja: "確かな、安全な" },
          { es: "la idea", en: "idea", ja: "アイデア、考え" },
          { es: "el sueño", en: "dream", ja: "夢" },
          { es: "el futuro", en: "future", ja: "未来" },
        ],
        phrases: [
          { es: "¿Qué vas a hacer mañana?", en: "What are you going to do tomorrow?", ja: "明日何するの?" },
          { es: "Voy a viajar a México.", en: "I'm going to travel to Mexico.", ja: "メキシコに旅行に行きます" },
          { es: "Quiero aprender a cocinar.", en: "I want to learn to cook.", ja: "料理を習いたい" },
          { es: "Tengo planes este fin de semana.", en: "I have plans this weekend.", ja: "今週末は予定があります" },
          { es: "¿Nos vemos el sábado?", en: "Shall we meet on Saturday?", ja: "土曜日に会う?" },
          { es: "¡Ojalá!", en: "I hope so! / Hopefully!", ja: "そうだといいな!" },
        ],
      },
      {
        id: "u18", icon: "💬", title: "意見を言う", en: "Giving Opinions",
        words: [
          { es: "la opinión", en: "opinion", ja: "意見" },
          { es: "la verdad", en: "truth", ja: "真実、本当のこと" },
          { es: "la mentira", en: "lie", ja: "嘘" },
          { es: "la razón", en: "reason / being right", ja: "理由、正しさ" },
          { es: "importante", en: "important", ja: "重要な" },
          { es: "difícil", en: "difficult", ja: "難しい" },
          { es: "fácil", en: "easy", ja: "簡単な" },
          { es: "mejor", en: "better / best", ja: "より良い" },
          { es: "peor", en: "worse / worst", ja: "より悪い" },
          { es: "igual", en: "the same / equal", ja: "同じ" },
          { es: "diferente", en: "different", ja: "違う、異なる" },
          { es: "interesante", en: "interesting", ja: "面白い、興味深い" },
        ],
        phrases: [
          { es: "¿Qué piensas?", en: "What do you think?", ja: "どう思う?" },
          { es: "Creo que sí.", en: "I think so.", ja: "そう思うよ" },
          { es: "Para mí, es importante.", en: "For me, it's important.", ja: "私にとっては大事なことです" },
          { es: "Tienes razón.", en: "You're right.", ja: "君の言う通りだ" },
          { es: "No estoy de acuerdo.", en: "I don't agree.", ja: "賛成できない" },
          { es: "Depende.", en: "It depends.", ja: "場合によるね" },
        ],
      },
      {
        id: "u19", icon: "📱", title: "電話とメッセージ", en: "Phone & Messages",
        words: [
          { es: "el teléfono", en: "phone", ja: "電話" },
          { es: "el mensaje", en: "message", ja: "メッセージ" },
          { es: "la llamada", en: "phone call", ja: "電話(通話)" },
          { es: "el correo", en: "mail / email", ja: "郵便、メール" },
          { es: "el video", en: "video", ja: "動画、ビデオ" },
          { es: "el internet", en: "internet", ja: "インターネット" },
          { es: "las redes sociales", en: "social media", ja: "SNS" },
          { es: "el número", en: "number", ja: "番号、数" },
          { es: "el contacto", en: "contact", ja: "連絡先" },
          { es: "la batería", en: "battery", ja: "バッテリー、電池" },
          { es: "la señal", en: "signal", ja: "電波、信号" },
          { es: "llamar", en: "to call", ja: "電話する、呼ぶ" },
        ],
        phrases: [
          { es: "¿Me das tu número?", en: "Can you give me your number?", ja: "番号教えてくれる?" },
          { es: "Te llamo luego.", en: "I'll call you later.", ja: "後で電話するね" },
          { es: "Mándame un mensaje.", en: "Send me a message.", ja: "メッセージ送ってね" },
          { es: "No tengo batería.", en: "My battery is dead.", ja: "充電がない" },
          { es: "¿Estás ahí?", en: "Are you there?", ja: "(電話・チャットで)いる? 聞こえてる?" },
          { es: "Se cortó la llamada.", en: "The call got cut off.", ja: "電話が切れちゃった" },
        ],
      },
      {
        id: "u20", icon: "🚨", title: "トラブルと緊急時", en: "Trouble & Emergencies",
        words: [
          { es: "la emergencia", en: "emergency", ja: "緊急事態" },
          { es: "la policía", en: "police", ja: "警察" },
          { es: "el ladrón", en: "thief", ja: "泥棒" },
          { es: "el fuego", en: "fire", ja: "火、火事" },
          { es: "el peligro", en: "danger", ja: "危険" },
          { es: "el cuidado", en: "care / caution", ja: "注意" },
          { es: "el pasaporte", en: "passport", ja: "パスポート" },
          { es: "la embajada", en: "embassy", ja: "大使館" },
          { es: "el accidente", en: "accident", ja: "事故" },
          { es: "la herida", en: "wound / injury", ja: "けが、傷" },
          { es: "perder", en: "to lose", ja: "失くす、負ける" },
          { es: "robar", en: "to steal", ja: "盗む" },
        ],
        phrases: [
          { es: "¡Socorro! / ¡Ayuda!", en: "Help!", ja: "助けて!" },
          { es: "Llama a la policía.", en: "Call the police.", ja: "警察を呼んで" },
          { es: "Perdí mi pasaporte.", en: "I lost my passport.", ja: "パスポートを失くしました" },
          { es: "Me robaron la cartera.", en: "My wallet was stolen.", ja: "財布を盗まれました" },
          { es: "¡Ten cuidado!", en: "Be careful!", ja: "気をつけて!" },
          { es: "Todo está bien.", en: "Everything is fine.", ja: "大丈夫、全部順調だよ" },
        ],
      },
    ],
  },
  {
    phase: 6,
    title: "ネイティブに近づく",
    en: "Sounding Native",
    month: "6ヶ月目",
    color: "#7b2cbf",
    units: [
      {
        id: "u21", icon: "😲", title: "リアクション・相づち", en: "Reactions & Fillers",
        words: [
          { es: "claro", en: "of course / sure", ja: "もちろん" },
          { es: "vale", en: "okay (Spain)", ja: "オッケー、了解(スペイン)" },
          { es: "bueno", en: "well... / good", ja: "えっと、まあ(つなぎ言葉)" },
          { es: "pues", en: "well / so", ja: "うーん、それで(つなぎ言葉)" },
          { es: "oye", en: "hey / listen", ja: "ねえ、ちょっと" },
          { es: "mira", en: "look / hey", ja: "ほら、あのね" },
          { es: "genial", en: "great / awesome", ja: "すごくいい、最高" },
          { es: "increíble", en: "incredible / amazing", ja: "信じられない、すごい" },
          { es: "perfecto", en: "perfect", ja: "完璧、バッチリ" },
          { es: "exacto", en: "exactly", ja: "その通り" },
          { es: "más o menos", en: "more or less / so-so", ja: "まあまあ、だいたい" },
          { es: "a ver", en: "let's see", ja: "えっと、どれどれ" },
        ],
        phrases: [
          { es: "¡No me digas!", en: "No way! / You don't say!", ja: "うそでしょ!まさか!" },
          { es: "¿En serio?", en: "Seriously?", ja: "マジで?" },
          { es: "¡Qué bien!", en: "How nice! / Great!", ja: "いいね!よかった!" },
          { es: "¡Qué pena!", en: "What a shame!", ja: "残念!" },
          { es: "Ya veo.", en: "I see.", ja: "なるほどね" },
          { es: "¡Qué va!", en: "No way! / Not at all!", ja: "まさか!全然そんなことないよ!" },
        ],
      },
      {
        id: "u22", icon: "😎", title: "くだけた表現", en: "Casual & Slang",
        words: [
          { es: "guay", en: "cool (Spain)", ja: "かっこいい、イケてる(スペイン)" },
          { es: "chévere", en: "cool (Latin America)", ja: "かっこいい、いいね(中南米)" },
          { es: "el tío / la tía", en: "dude / girl (Spain slang)", ja: "やつ、あいつ(スペイン口語)" },
          { es: "el/la colega", en: "buddy / mate", ja: "仲間、ダチ" },
          { es: "la pasta", en: "money (slang) / pasta", ja: "お金(俗語)、パスタ" },
          { es: "flipar", en: "to be amazed (Spain slang)", ja: "ビックリする、ハマる(俗語)" },
          { es: "molar", en: "to be cool (Spain slang)", ja: "イケてる、いい感じ(俗語)" },
          { es: "vale la pena", en: "it's worth it", ja: "価値がある、やる価値あり" },
          { es: "echar de menos", en: "to miss (someone)", ja: "(人を)恋しく思う" },
          { es: "tener ganas de", en: "to feel like / look forward to", ja: "〜したい気分、楽しみにする" },
          { es: "caer bien", en: "to make a good impression / to like (a person)", ja: "(人として)好感が持てる" },
          { es: "pasarlo bien", en: "to have a good time", ja: "楽しく過ごす" },
        ],
        phrases: [
          { es: "¡Qué guay!", en: "How cool!", ja: "超いいじゃん!" },
          { es: "Me cae muy bien.", en: "I really like him/her (as a person).", ja: "あの人、すごく感じがいい" },
          { es: "Tengo ganas de verte.", en: "I'm looking forward to seeing you.", ja: "早く会いたいな" },
          { es: "Te echo de menos.", en: "I miss you.", ja: "君がいなくて寂しい" },
          { es: "Vale la pena.", en: "It's worth it.", ja: "その価値はあるよ" },
          { es: "¡Estoy flipando!", en: "I'm blown away!", ja: "マジでビックリしてる!" },
        ],
      },
      {
        id: "u23", icon: "📖", title: "話をつなげる", en: "Telling Stories",
        words: [
          { es: "primero", en: "first", ja: "まず、最初に" },
          { es: "luego / después", en: "then / afterwards", ja: "それから、その後" },
          { es: "de repente", en: "suddenly", ja: "突然" },
          { es: "al final", en: "in the end / finally", ja: "最後に、結局" },
          { es: "porque", en: "because", ja: "なぜなら" },
          { es: "pero", en: "but", ja: "でも、しかし" },
          { es: "aunque", en: "although / even though", ja: "〜だけれども" },
          { es: "mientras", en: "while", ja: "〜の間に" },
          { es: "por eso", en: "that's why / therefore", ja: "だから" },
          { es: "además", en: "besides / also", ja: "その上、さらに" },
          { es: "en fin", en: "anyway / in short", ja: "まあとにかく、要するに" },
          { es: "la historia", en: "story / history", ja: "話、物語、歴史" },
        ],
        phrases: [
          { es: "Primero fuimos a la playa.", en: "First we went to the beach.", ja: "まずビーチに行きました" },
          { es: "De repente, empezó a llover.", en: "Suddenly, it started to rain.", ja: "突然、雨が降り出しました" },
          { es: "Al final, todo salió bien.", en: "In the end, everything turned out fine.", ja: "結局、全部うまくいきました" },
          { es: "Fue un día inolvidable.", en: "It was an unforgettable day.", ja: "忘れられない一日でした" },
          { es: "¿Sabes qué pasó?", en: "You know what happened?", ja: "何があったか知ってる?" },
          { es: "Te lo cuento luego.", en: "I'll tell you later.", ja: "後で話すね" },
        ],
      },
      {
        id: "u24", icon: "🎓", title: "卒業ユニット", en: "Graduation",
        words: [
          { es: "la conversación", en: "conversation", ja: "会話" },
          { es: "la palabra", en: "word", ja: "単語、言葉" },
          { es: "la frase", en: "phrase / sentence", ja: "フレーズ、文" },
          { es: "el significado", en: "meaning", ja: "意味" },
          { es: "el ejemplo", en: "example", ja: "例" },
          { es: "la práctica", en: "practice", ja: "練習" },
          { es: "la costumbre", en: "custom / habit", ja: "習慣、風習" },
          { es: "la cultura", en: "culture", ja: "文化" },
          { es: "el mundo", en: "world", ja: "世界" },
          { es: "la meta", en: "goal", ja: "目標、ゴール" },
          { es: "el éxito", en: "success", ja: "成功" },
          { es: "lograr", en: "to achieve", ja: "達成する" },
        ],
        phrases: [
          { es: "¿Puedes repetir, por favor?", en: "Can you repeat, please?", ja: "もう一度言ってもらえますか?" },
          { es: "¿Qué significa esto?", en: "What does this mean?", ja: "これはどういう意味?" },
          { es: "¿Cómo se dice esto en español?", en: "How do you say this in Spanish?", ja: "これはスペイン語で何て言うの?" },
          { es: "Cada día hablo mejor.", en: "Every day I speak better.", ja: "毎日どんどん話せるようになっている" },
          { es: "Sigue practicando.", en: "Keep practicing.", ja: "練習を続けて" },
          { es: "¡Lo lograste!", en: "You did it!", ja: "やったね!達成したよ!" },
        ],
      },
    ],
  },
];
