// ¡Escucha! 単語データ 2/4 — 衣類・体・健康・人・感情・自然・動物

const WORD_PART_2 = [
  {
    cat: "衣類・アクセサリー", icon: "👕",
    items: [
      { es: "la camiseta", en: "T-shirt", ja: "Tシャツ" },
      { es: "los pantalones", en: "pants / trousers", ja: "ズボン、パンツ" },
      { es: "los vaqueros", en: "jeans", ja: "ジーンズ" },
      { es: "los pantalones cortos", en: "shorts", ja: "短パン、ショートパンツ" },
      { es: "la falda", en: "skirt", ja: "スカート" },
      { es: "el vestido", en: "dress", ja: "ワンピース、ドレス" },
      { es: "el traje", en: "suit", ja: "スーツ" },
      { es: "la chaqueta", en: "jacket", ja: "ジャケット、上着" },
      { es: "el abrigo", en: "coat", ja: "コート" },
      { es: "el jersey / el suéter", en: "sweater", ja: "セーター" },
      { es: "la sudadera", en: "sweatshirt / hoodie", ja: "トレーナー、パーカー" },
      { es: "la blusa", en: "blouse", ja: "ブラウス" },
      { es: "la corbata", en: "tie", ja: "ネクタイ" },
      { es: "el cinturón", en: "belt", ja: "ベルト" },
      { es: "los calcetines", en: "socks", ja: "靴下" },
      { es: "las medias", en: "stockings / tights", ja: "ストッキング、タイツ" },
      { es: "la ropa interior", en: "underwear", ja: "下着" },
      { es: "el pijama", en: "pajamas", ja: "パジャマ" },
      { es: "el bañador", en: "swimsuit", ja: "水着" },
      { es: "las zapatillas", en: "sneakers", ja: "スニーカー、運動靴" },
      { es: "las botas", en: "boots", ja: "ブーツ" },
      { es: "las sandalias", en: "sandals", ja: "サンダル" },
      { es: "los tacones", en: "high heels", ja: "ハイヒール" },
      { es: "el sombrero", en: "hat", ja: "帽子(つば付き)" },
      { es: "la gorra", en: "cap", ja: "キャップ、野球帽" },
      { es: "los guantes", en: "gloves", ja: "手袋" },
      { es: "la bufanda", en: "scarf (winter)", ja: "マフラー" },
      { es: "el pañuelo", en: "scarf / handkerchief", ja: "スカーフ、ハンカチ" },
      { es: "el anillo", en: "ring", ja: "指輪" },
      { es: "el collar", en: "necklace", ja: "ネックレス" },
      { es: "los pendientes", en: "earrings", ja: "ピアス、イヤリング" },
      { es: "la pulsera", en: "bracelet", ja: "ブレスレット" },
      { es: "la joya", en: "jewel / jewelry", ja: "宝石、アクセサリー" },
      { es: "la moda", en: "fashion", ja: "ファッション、流行" },
      { es: "la marca", en: "brand", ja: "ブランド、銘柄" },
      { es: "el estilo", en: "style", ja: "スタイル、様式" },
      { es: "el bolsillo", en: "pocket", ja: "ポケット" },
      { es: "la cremallera", en: "zipper", ja: "ファスナー、チャック" },
      { es: "el botón", en: "button", ja: "ボタン" },
      { es: "la manga", en: "sleeve", ja: "袖" },
      { es: "la tela", en: "fabric / cloth", ja: "布、生地" },
      { es: "el algodón", en: "cotton", ja: "綿、コットン" },
      { es: "la lana", en: "wool", ja: "ウール、毛糸" },
      { es: "el cuero", en: "leather", ja: "革、レザー" },
      { es: "la seda", en: "silk", ja: "絹、シルク" },
    ],
  },
  {
    cat: "体・顔", icon: "💪",
    items: [
      { es: "el cuerpo", en: "body", ja: "体" },
      { es: "la cara", en: "face", ja: "顔" },
      { es: "el ojo", en: "eye", ja: "目" },
      { es: "la nariz", en: "nose", ja: "鼻" },
      { es: "la boca", en: "mouth", ja: "口" },
      { es: "la oreja", en: "ear", ja: "耳" },
      { es: "el oído", en: "ear (inner) / hearing", ja: "耳(内耳)、聴覚" },
      { es: "el diente", en: "tooth", ja: "歯" },
      { es: "la muela", en: "molar / back tooth", ja: "奥歯" },
      { es: "la lengua", en: "tongue", ja: "舌" },
      { es: "el labio", en: "lip", ja: "唇" },
      { es: "la mejilla", en: "cheek", ja: "頬" },
      { es: "la frente", en: "forehead", ja: "額、おでこ" },
      { es: "la ceja", en: "eyebrow", ja: "眉毛" },
      { es: "la barba", en: "beard", ja: "ひげ" },
      { es: "el pelo / el cabello", en: "hair", ja: "髪、毛" },
      { es: "el cuello", en: "neck", ja: "首" },
      { es: "la garganta", en: "throat", ja: "のど" },
      { es: "el hombro", en: "shoulder", ja: "肩" },
      { es: "el brazo", en: "arm", ja: "腕" },
      { es: "el codo", en: "elbow", ja: "肘" },
      { es: "la muñeca", en: "wrist / doll", ja: "手首、人形" },
      { es: "la mano", en: "hand", ja: "手" },
      { es: "el dedo", en: "finger / toe", ja: "指" },
      { es: "la uña", en: "nail", ja: "爪" },
      { es: "el pecho", en: "chest", ja: "胸" },
      { es: "la espalda", en: "back", ja: "背中" },
      { es: "la cintura", en: "waist", ja: "腰、ウエスト" },
      { es: "la cadera", en: "hip", ja: "股関節、ヒップ" },
      { es: "la pierna", en: "leg", ja: "脚" },
      { es: "la rodilla", en: "knee", ja: "膝" },
      { es: "el tobillo", en: "ankle", ja: "足首" },
      { es: "el pie", en: "foot", ja: "足" },
      { es: "la piel", en: "skin", ja: "肌、皮膚" },
      { es: "el hueso", en: "bone", ja: "骨" },
      { es: "el músculo", en: "muscle", ja: "筋肉" },
      { es: "el corazón", en: "heart", ja: "心臓、心" },
      { es: "el cerebro", en: "brain", ja: "脳" },
      { es: "el pulmón", en: "lung", ja: "肺" },
      { es: "la sangre", en: "blood", ja: "血、血液" },
      { es: "la voz", en: "voice", ja: "声" },
      { es: "la sonrisa", en: "smile", ja: "笑顔、ほほえみ" },
      { es: "las lágrimas", en: "tears", ja: "涙" },
      { es: "el peso", en: "weight", ja: "体重、重さ" },
      { es: "la altura", en: "height", ja: "身長、高さ" },
    ],
  },
  {
    cat: "健康・病気・病院", icon: "🏥",
    items: [
      { es: "la salud", en: "health", ja: "健康" },
      { es: "la enfermedad", en: "illness / disease", ja: "病気" },
      { es: "el resfriado", en: "cold (illness)", ja: "風邪" },
      { es: "la gripe", en: "flu", ja: "インフルエンザ" },
      { es: "la tos", en: "cough", ja: "せき" },
      { es: "el estornudo", en: "sneeze", ja: "くしゃみ" },
      { es: "la alergia", en: "allergy", ja: "アレルギー" },
      { es: "el mareo", en: "dizziness", ja: "めまい、乗り物酔い" },
      { es: "la náusea", en: "nausea", ja: "吐き気" },
      { es: "la lesión", en: "injury", ja: "けが、故障(スポーツ)" },
      { es: "la quemadura", en: "burn", ja: "やけど" },
      { es: "la picadura", en: "insect bite / sting", ja: "虫刺され" },
      { es: "el golpe", en: "hit / bump", ja: "打撲、衝撃" },
      { es: "la medicina / el medicamento", en: "medicine", ja: "薬" },
      { es: "la pastilla", en: "pill / tablet", ja: "錠剤" },
      { es: "la vacuna", en: "vaccine", ja: "ワクチン、予防接種" },
      { es: "la tirita", en: "band-aid", ja: "絆創膏" },
      { es: "la venda", en: "bandage", ja: "包帯" },
      { es: "el termómetro", en: "thermometer", ja: "体温計" },
      { es: "la consulta", en: "doctor's visit / office", ja: "診察、診療室" },
      { es: "la cita médica", en: "medical appointment", ja: "診察の予約" },
      { es: "el/la paciente", en: "patient", ja: "患者" },
      { es: "el enfermero / la enfermera", en: "nurse", ja: "看護師" },
      { es: "el/la dentista", en: "dentist", ja: "歯医者" },
      { es: "la ambulancia", en: "ambulance", ja: "救急車" },
      { es: "las urgencias", en: "emergency room", ja: "救急外来" },
      { es: "la operación", en: "operation / surgery", ja: "手術" },
      { es: "la radiografía", en: "X-ray", ja: "レントゲン" },
      { es: "el análisis de sangre", en: "blood test", ja: "血液検査" },
      { es: "la tensión", en: "blood pressure", ja: "血圧" },
      { es: "el seguro médico", en: "health insurance", ja: "医療保険" },
      { es: "la receta médica", en: "prescription", ja: "処方箋" },
      { es: "el descanso", en: "rest", ja: "休息、休憩" },
      { es: "el estrés", en: "stress", ja: "ストレス" },
      { es: "la dieta", en: "diet", ja: "ダイエット、食事療法" },
      { es: "el ejercicio", en: "exercise", ja: "運動" },
      { es: "la respiración", en: "breathing", ja: "呼吸" },
      { es: "el cansancio", en: "tiredness / fatigue", ja: "疲れ、疲労" },
      { es: "la siesta", en: "nap / siesta", ja: "昼寝、シエスタ" },
      { es: "embarazada", en: "pregnant", ja: "妊娠している" },
    ],
  },
  {
    cat: "人・ライフステージ", icon: "🧑‍🤝‍🧑",
    items: [
      { es: "la gente", en: "people", ja: "人々" },
      { es: "la persona", en: "person", ja: "人" },
      { es: "el hombre", en: "man", ja: "男性、男" },
      { es: "la mujer", en: "woman", ja: "女性、女" },
      { es: "el chico / la chica", en: "boy / girl", ja: "男の子、女の子、若者" },
      { es: "el niño / la niña", en: "child (boy / girl)", ja: "子ども" },
      { es: "el bebé", en: "baby", ja: "赤ちゃん" },
      { es: "el/la joven", en: "young person", ja: "若者" },
      { es: "el adulto / la adulta", en: "adult", ja: "大人" },
      { es: "el anciano / la anciana", en: "elderly person", ja: "お年寄り、高齢者" },
      { es: "el señor", en: "Mr. / gentleman", ja: "〜さん(男性)、紳士" },
      { es: "la señora", en: "Mrs. / lady", ja: "〜さん(女性)、婦人" },
      { es: "el primo / la prima", en: "cousin", ja: "いとこ" },
      { es: "el sobrino / la sobrina", en: "nephew / niece", ja: "甥、姪" },
      { es: "el nieto / la nieta", en: "grandson / granddaughter", ja: "孫" },
      { es: "el suegro / la suegra", en: "father-in-law / mother-in-law", ja: "義父、義母" },
      { es: "el cuñado / la cuñada", en: "brother-in-law / sister-in-law", ja: "義兄弟、義姉妹" },
      { es: "el novio / la novia", en: "boyfriend / girlfriend", ja: "恋人、彼氏、彼女" },
      { es: "la pareja", en: "couple / partner", ja: "カップル、パートナー" },
      { es: "el matrimonio", en: "marriage / married couple", ja: "結婚、夫婦" },
      { es: "la boda", en: "wedding", ja: "結婚式" },
      { es: "el divorcio", en: "divorce", ja: "離婚" },
      { es: "el nacimiento", en: "birth", ja: "誕生" },
      { es: "el cumpleaños", en: "birthday", ja: "誕生日" },
      { es: "la infancia", en: "childhood", ja: "子ども時代" },
      { es: "la juventud", en: "youth", ja: "青春、若い頃" },
      { es: "la vejez", en: "old age", ja: "老年" },
      { es: "la muerte", en: "death", ja: "死" },
      { es: "la vida", en: "life", ja: "人生、生活、命" },
      { es: "el vecindario", en: "neighborhood / community", ja: "ご近所、地域社会" },
      { es: "el/la conocido/a", en: "acquaintance", ja: "知り合い" },
      { es: "el desconocido / la desconocida", en: "stranger", ja: "見知らぬ人" },
      { es: "el/la invitado/a", en: "guest", ja: "招待客、ゲスト" },
      { es: "el apellido", en: "last name / surname", ja: "名字、姓" },
      { es: "la edad", en: "age", ja: "年齢" },
      { es: "el género", en: "gender", ja: "性別、ジェンダー" },
      { es: "la nacionalidad", en: "nationality", ja: "国籍" },
      { es: "el extranjero / la extranjera", en: "foreigner", ja: "外国人" },
      { es: "el carácter", en: "character / personality", ja: "性格" },
      { es: "la personalidad", en: "personality", ja: "個性、人柄" },
    ],
  },
  {
    cat: "感情・気持ち", icon: "❤️",
    items: [
      { es: "el amor", en: "love", ja: "愛" },
      { es: "la amistad", en: "friendship", ja: "友情" },
      { es: "la felicidad", en: "happiness", ja: "幸せ、幸福" },
      { es: "la alegría", en: "joy", ja: "喜び" },
      { es: "la tristeza", en: "sadness", ja: "悲しみ" },
      { es: "el miedo", en: "fear", ja: "恐怖、怖さ" },
      { es: "la sorpresa", en: "surprise", ja: "驚き、サプライズ" },
      { es: "la vergüenza", en: "embarrassment / shame", ja: "恥ずかしさ" },
      { es: "los celos", en: "jealousy", ja: "嫉妬、やきもち" },
      { es: "la envidia", en: "envy", ja: "うらやましさ、ねたみ" },
      { es: "el enfado", en: "anger", ja: "怒り" },
      { es: "la preocupación", en: "worry / concern", ja: "心配" },
      { es: "la esperanza", en: "hope", ja: "希望" },
      { es: "la confianza", en: "trust / confidence", ja: "信頼、自信" },
      { es: "la paciencia", en: "patience", ja: "忍耐、我慢" },
      { es: "el ánimo", en: "spirit / mood / cheer", ja: "元気、気力" },
      { es: "el humor", en: "mood / humor", ja: "機嫌、ユーモア" },
      { es: "la risa", en: "laughter", ja: "笑い" },
      { es: "el beso", en: "kiss", ja: "キス" },
      { es: "el abrazo", en: "hug", ja: "ハグ、抱擁" },
      { es: "el cariño", en: "affection", ja: "愛情、いとしさ" },
      { es: "el recuerdo", en: "memory / souvenir", ja: "思い出、記憶" },
      { es: "la sensación", en: "feeling / sensation", ja: "感覚、感じ" },
      { es: "el sentimiento", en: "feeling / emotion", ja: "感情、気持ち" },
      { es: "el gusto", en: "taste / pleasure", ja: "好み、喜び" },
      { es: "el interés", en: "interest", ja: "興味、関心" },
      { es: "la curiosidad", en: "curiosity", ja: "好奇心" },
      { es: "la suerte", en: "luck", ja: "運、幸運" },
      { es: "el orgullo", en: "pride", ja: "誇り、プライド" },
      { es: "la soledad", en: "loneliness", ja: "孤独、寂しさ" },
    ],
  },
  {
    cat: "性格・様子(形容詞)", icon: "😊",
    items: [
      { es: "contento / contenta", en: "glad / pleased", ja: "満足した、うれしい" },
      { es: "alegre", en: "cheerful", ja: "陽気な、明るい" },
      { es: "emocionado / emocionada", en: "excited", ja: "わくわくした、感動した" },
      { es: "tranquilo / tranquila", en: "calm / quiet", ja: "落ち着いた、静かな" },
      { es: "relajado / relajada", en: "relaxed", ja: "リラックスした" },
      { es: "aburrido / aburrida", en: "bored / boring", ja: "退屈した、つまらない" },
      { es: "sorprendido / sorprendida", en: "surprised", ja: "驚いた" },
      { es: "asustado / asustada", en: "scared", ja: "怖がった、おびえた" },
      { es: "preocupado / preocupada", en: "worried", ja: "心配した" },
      { es: "estresado / estresada", en: "stressed", ja: "ストレスを感じた" },
      { es: "ocupado / ocupada", en: "busy", ja: "忙しい" },
      { es: "libre", en: "free", ja: "自由な、暇な、空いている" },
      { es: "solo / sola", en: "alone", ja: "ひとりの" },
      { es: "orgulloso / orgullosa", en: "proud", ja: "誇りに思う" },
      { es: "agradecido / agradecida", en: "grateful", ja: "感謝している" },
      { es: "celoso / celosa", en: "jealous", ja: "嫉妬した" },
      { es: "enamorado / enamorada", en: "in love", ja: "恋している" },
      { es: "amable", en: "kind / friendly", ja: "親切な、優しい" },
      { es: "simpático / simpática", en: "nice / likeable", ja: "感じのいい、気さくな" },
      { es: "antipático / antipática", en: "unfriendly", ja: "感じの悪い" },
      { es: "generoso / generosa", en: "generous", ja: "気前のいい、寛大な" },
      { es: "tacaño / tacaña", en: "stingy", ja: "けちな" },
      { es: "honesto / honesta", en: "honest", ja: "正直な" },
      { es: "sincero / sincera", en: "sincere", ja: "誠実な、率直な" },
      { es: "tímido / tímida", en: "shy", ja: "内気な、シャイな" },
      { es: "valiente", en: "brave", ja: "勇敢な" },
      { es: "cobarde", en: "cowardly", ja: "臆病な" },
      { es: "inteligente", en: "intelligent / smart", ja: "頭のいい、賢い" },
      { es: "tonto / tonta", en: "silly / dumb", ja: "ばかな、おバカな" },
      { es: "gracioso / graciosa", en: "funny", ja: "面白い、ひょうきんな" },
      { es: "serio / seria", en: "serious", ja: "まじめな、真剣な" },
      { es: "trabajador / trabajadora", en: "hardworking", ja: "働き者の、勤勉な" },
      { es: "perezoso / perezosa", en: "lazy", ja: "怠け者の" },
      { es: "educado / educada", en: "polite", ja: "礼儀正しい" },
      { es: "maleducado / maleducada", en: "rude", ja: "無礼な、行儀の悪い" },
      { es: "responsable", en: "responsible", ja: "責任感のある" },
      { es: "optimista", en: "optimistic", ja: "楽観的な" },
      { es: "pesimista", en: "pessimistic", ja: "悲観的な" },
      { es: "sociable", en: "sociable / outgoing", ja: "社交的な" },
      { es: "callado / callada", en: "quiet (person)", ja: "無口な、おとなしい" },
    ],
  },
  {
    cat: "天気・自然", icon: "🌤",
    items: [
      { es: "el clima", en: "climate / weather", ja: "気候、天気" },
      { es: "la temperatura", en: "temperature", ja: "気温、温度" },
      { es: "el grado", en: "degree", ja: "度(温度)" },
      { es: "la tormenta", en: "storm", ja: "嵐" },
      { es: "el trueno", en: "thunder", ja: "雷(音)" },
      { es: "el relámpago", en: "lightning", ja: "稲妻" },
      { es: "la niebla", en: "fog", ja: "霧" },
      { es: "el arcoíris", en: "rainbow", ja: "虹" },
      { es: "la humedad", en: "humidity", ja: "湿気、湿度" },
      { es: "el pronóstico", en: "forecast", ja: "予報" },
      { es: "la sombra", en: "shade / shadow", ja: "日陰、影" },
      { es: "el amanecer", en: "sunrise / dawn", ja: "日の出、夜明け" },
      { es: "el atardecer", en: "sunset / dusk", ja: "夕暮れ" },
      { es: "el cielo", en: "sky", ja: "空" },
      { es: "la estrella", en: "star", ja: "星" },
      { es: "la luna", en: "moon", ja: "月" },
      { es: "la tierra", en: "earth / land / soil", ja: "地球、土地、土" },
      { es: "el mar", en: "sea", ja: "海" },
      { es: "el océano", en: "ocean", ja: "大洋、オーシャン" },
      { es: "la ola", en: "wave", ja: "波" },
      { es: "la arena", en: "sand", ja: "砂" },
      { es: "la isla", en: "island", ja: "島" },
      { es: "la costa", en: "coast", ja: "海岸、沿岸" },
      { es: "el río", en: "river", ja: "川" },
      { es: "el lago", en: "lake", ja: "湖" },
      { es: "la cascada", en: "waterfall", ja: "滝" },
      { es: "el bosque", en: "forest", ja: "森" },
      { es: "la selva", en: "jungle / rainforest", ja: "ジャングル、熱帯雨林" },
      { es: "el desierto", en: "desert", ja: "砂漠" },
      { es: "el valle", en: "valley", ja: "谷" },
      { es: "la colina", en: "hill", ja: "丘" },
      { es: "el volcán", en: "volcano", ja: "火山" },
      { es: "el terremoto", en: "earthquake", ja: "地震" },
      { es: "la inundación", en: "flood", ja: "洪水" },
      { es: "el incendio", en: "fire (disaster)", ja: "火事、火災" },
      { es: "la naturaleza", en: "nature", ja: "自然" },
      { es: "el paisaje", en: "landscape / scenery", ja: "風景、景色" },
      { es: "el medio ambiente", en: "environment", ja: "環境" },
      { es: "la contaminación", en: "pollution", ja: "汚染、公害" },
      { es: "el reciclaje", en: "recycling", ja: "リサイクル" },
      { es: "la piedra", en: "stone / rock", ja: "石" },
      { es: "la roca", en: "rock / boulder", ja: "岩" },
      { es: "el fuego artificial", en: "fireworks", ja: "花火" },
      { es: "el aire", en: "air", ja: "空気" },
      { es: "el espacio", en: "space", ja: "宇宙、スペース" },
    ],
  },
  {
    cat: "動物", icon: "🐶",
    items: [
      { es: "el animal", en: "animal", ja: "動物" },
      { es: "la mascota", en: "pet", ja: "ペット" },
      { es: "el perro", en: "dog", ja: "犬" },
      { es: "el gato", en: "cat", ja: "猫" },
      { es: "el pájaro", en: "bird", ja: "鳥" },
      { es: "el pez", en: "fish (live)", ja: "魚(生き物)" },
      { es: "el caballo", en: "horse", ja: "馬" },
      { es: "la vaca", en: "cow", ja: "牛" },
      { es: "el toro", en: "bull", ja: "雄牛" },
      { es: "la oveja", en: "sheep", ja: "羊" },
      { es: "la cabra", en: "goat", ja: "ヤギ" },
      { es: "la gallina", en: "hen / chicken", ja: "めんどり、鶏" },
      { es: "el pato", en: "duck", ja: "アヒル、カモ" },
      { es: "el conejo", en: "rabbit", ja: "ウサギ" },
      { es: "el ratón", en: "mouse", ja: "ネズミ" },
      { es: "el león", en: "lion", ja: "ライオン" },
      { es: "el tigre", en: "tiger", ja: "トラ" },
      { es: "el oso", en: "bear", ja: "クマ" },
      { es: "el elefante", en: "elephant", ja: "ゾウ" },
      { es: "el mono", en: "monkey", ja: "サル" },
      { es: "la jirafa", en: "giraffe", ja: "キリン" },
      { es: "el lobo", en: "wolf", ja: "オオカミ" },
      { es: "el zorro", en: "fox", ja: "キツネ" },
      { es: "el ciervo", en: "deer", ja: "シカ" },
      { es: "el jabalí", en: "wild boar", ja: "イノシシ" },
      { es: "la serpiente", en: "snake", ja: "ヘビ" },
      { es: "la rana", en: "frog", ja: "カエル" },
      { es: "la tortuga", en: "turtle", ja: "カメ" },
      { es: "el tiburón", en: "shark", ja: "サメ" },
      { es: "la ballena", en: "whale", ja: "クジラ" },
      { es: "el delfín", en: "dolphin", ja: "イルカ" },
      { es: "el insecto", en: "insect / bug", ja: "昆虫、虫" },
      { es: "la mosca", en: "fly", ja: "ハエ" },
      { es: "el mosquito", en: "mosquito", ja: "蚊" },
      { es: "la abeja", en: "bee", ja: "ハチ" },
      { es: "la hormiga", en: "ant", ja: "アリ" },
      { es: "la mariposa", en: "butterfly", ja: "チョウ" },
      { es: "la araña", en: "spider", ja: "クモ" },
      { es: "la cucaracha", en: "cockroach", ja: "ゴキブリ" },
      { es: "el zoo / el zoológico", en: "zoo", ja: "動物園" },
    ],
  },
  {
    cat: "植物", icon: "🌷",
    items: [
      { es: "la planta", en: "plant", ja: "植物" },
      { es: "la flor", en: "flower", ja: "花" },
      { es: "el árbol", en: "tree", ja: "木" },
      { es: "la hoja", en: "leaf", ja: "葉" },
      { es: "la rama", en: "branch", ja: "枝" },
      { es: "la raíz", en: "root", ja: "根" },
      { es: "la semilla", en: "seed", ja: "種" },
      { es: "la hierba", en: "grass / herb", ja: "草、ハーブ" },
      { es: "la rosa", en: "rose", ja: "バラ" },
      { es: "el girasol", en: "sunflower", ja: "ひまわり" },
      { es: "el cerezo", en: "cherry tree", ja: "桜の木" },
      { es: "la palmera", en: "palm tree", ja: "ヤシの木" },
      { es: "el cactus", en: "cactus", ja: "サボテン" },
      { es: "la maceta", en: "flower pot", ja: "植木鉢" },
      { es: "el ramo", en: "bouquet", ja: "花束" },
    ],
  },
];
