// ¡Escucha! 単語データ 1/4 — 住まい・日用品・食
// 各アイテム: es = スペイン語(冠詞付き), en = 英語, ja = 日本語
// ※ ¡Hablemos! 本編に収録済みの単語は除外

const WORD_PART_1 = [
  {
    cat: "家・部屋", icon: "🏠",
    items: [
      { es: "el apartamento / el piso", en: "apartment", ja: "アパート、マンション" },
      { es: "el edificio", en: "building", ja: "建物、ビル" },
      { es: "la habitación", en: "room", ja: "部屋" },
      { es: "el dormitorio", en: "bedroom", ja: "寝室" },
      { es: "el salón / la sala", en: "living room", ja: "リビング、居間" },
      { es: "la cocina", en: "kitchen", ja: "台所、キッチン" },
      { es: "el comedor", en: "dining room", ja: "ダイニング、食堂" },
      { es: "el garaje", en: "garage", ja: "車庫、ガレージ" },
      { es: "el jardín", en: "garden / yard", ja: "庭" },
      { es: "el balcón", en: "balcony", ja: "バルコニー" },
      { es: "la terraza", en: "terrace", ja: "テラス" },
      { es: "la entrada", en: "entrance", ja: "入口、玄関" },
      { es: "la salida", en: "exit", ja: "出口" },
      { es: "el pasillo", en: "hallway / corridor", ja: "廊下" },
      { es: "la escalera", en: "stairs", ja: "階段" },
      { es: "el ascensor", en: "elevator", ja: "エレベーター" },
      { es: "la puerta", en: "door", ja: "ドア、扉" },
      { es: "la ventana", en: "window", ja: "窓" },
      { es: "la pared", en: "wall", ja: "壁" },
      { es: "el techo", en: "ceiling / roof", ja: "天井、屋根" },
      { es: "el suelo", en: "floor / ground", ja: "床、地面" },
      { es: "la llave", en: "key", ja: "鍵" },
      { es: "la cerradura", en: "lock", ja: "錠、ロック" },
      { es: "el timbre", en: "doorbell", ja: "呼び鈴、チャイム" },
      { es: "el vecino / la vecina", en: "neighbor", ja: "隣人、近所の人" },
      { es: "el barrio", en: "neighborhood", ja: "地区、近所" },
      { es: "el sótano", en: "basement", ja: "地下室" },
      { es: "la planta baja", en: "ground floor", ja: "1階" },
      { es: "la dirección", en: "address", ja: "住所" },
      { es: "el alquiler", en: "rent", ja: "家賃、賃貸" },
      { es: "el dueño / la dueña", en: "owner / landlord", ja: "持ち主、大家" },
      { es: "la mudanza", en: "move (house)", ja: "引っ越し" },
      { es: "la luz", en: "light / electricity", ja: "明かり、電気" },
      { es: "el gas", en: "gas", ja: "ガス" },
      { es: "el enchufe", en: "plug / outlet", ja: "コンセント、プラグ" },
      { es: "el interruptor", en: "switch", ja: "スイッチ" },
      { es: "la calefacción", en: "heating", ja: "暖房" },
      { es: "el aire acondicionado", en: "air conditioning", ja: "エアコン、冷房" },
      { es: "el buzón", en: "mailbox", ja: "郵便受け、ポスト" },
      { es: "la basura", en: "trash / garbage", ja: "ゴミ" },
      { es: "el cubo de basura", en: "trash can", ja: "ゴミ箱" },
      { es: "la ducha", en: "shower", ja: "シャワー" },
      { es: "la bañera", en: "bathtub", ja: "浴槽、バスタブ" },
      { es: "el lavabo", en: "sink / washbasin", ja: "洗面台" },
      { es: "el inodoro", en: "toilet (bowl)", ja: "便器、トイレ" },
      { es: "el espejo", en: "mirror", ja: "鏡" },
      { es: "la chimenea", en: "fireplace / chimney", ja: "暖炉、煙突" },
      { es: "el patio", en: "courtyard / patio", ja: "中庭、パティオ" },
      { es: "la piscina", en: "swimming pool", ja: "プール" },
      { es: "el césped", en: "lawn / grass", ja: "芝生" },
    ],
  },
  {
    cat: "家具・家電", icon: "🛋",
    items: [
      { es: "los muebles", en: "furniture", ja: "家具" },
      { es: "la cama", en: "bed", ja: "ベッド" },
      { es: "el sofá", en: "sofa / couch", ja: "ソファ" },
      { es: "la silla", en: "chair", ja: "椅子" },
      { es: "el sillón", en: "armchair", ja: "肘掛け椅子、一人掛けソファ" },
      { es: "el escritorio", en: "desk", ja: "机、デスク" },
      { es: "la estantería", en: "bookshelf / shelves", ja: "棚、本棚" },
      { es: "el armario", en: "closet / wardrobe", ja: "クローゼット、タンス" },
      { es: "el cajón", en: "drawer", ja: "引き出し" },
      { es: "la lámpara", en: "lamp", ja: "ランプ、照明" },
      { es: "la alfombra", en: "carpet / rug", ja: "じゅうたん、ラグ" },
      { es: "la cortina", en: "curtain", ja: "カーテン" },
      { es: "la almohada", en: "pillow", ja: "枕" },
      { es: "la manta", en: "blanket", ja: "毛布" },
      { es: "las sábanas", en: "sheets", ja: "シーツ" },
      { es: "el colchón", en: "mattress", ja: "マットレス" },
      { es: "la mesita de noche", en: "nightstand", ja: "ナイトテーブル" },
      { es: "el cuadro", en: "picture / painting", ja: "絵、額" },
      { es: "el reloj", en: "clock / watch", ja: "時計" },
      { es: "el despertador", en: "alarm clock", ja: "目覚まし時計" },
      { es: "la televisión / la tele", en: "television / TV", ja: "テレビ" },
      { es: "la radio", en: "radio", ja: "ラジオ" },
      { es: "la nevera / el refrigerador", en: "fridge / refrigerator", ja: "冷蔵庫" },
      { es: "el congelador", en: "freezer", ja: "冷凍庫" },
      { es: "el horno", en: "oven", ja: "オーブン" },
      { es: "el microondas", en: "microwave", ja: "電子レンジ" },
      { es: "la lavadora", en: "washing machine", ja: "洗濯機" },
      { es: "la secadora", en: "dryer", ja: "乾燥機" },
      { es: "el lavavajillas", en: "dishwasher", ja: "食洗機" },
      { es: "la aspiradora", en: "vacuum cleaner", ja: "掃除機" },
      { es: "la plancha", en: "iron", ja: "アイロン" },
      { es: "el ventilador", en: "fan", ja: "扇風機" },
      { es: "la estufa", en: "heater / stove", ja: "ストーブ、こんろ" },
      { es: "la bombilla", en: "light bulb", ja: "電球" },
      { es: "la percha", en: "hanger", ja: "ハンガー" },
    ],
  },
  {
    cat: "キッチン・調理器具", icon: "🍳",
    items: [
      { es: "la sartén", en: "frying pan", ja: "フライパン" },
      { es: "la olla", en: "pot", ja: "鍋" },
      { es: "el cuchillo", en: "knife", ja: "ナイフ、包丁" },
      { es: "el tenedor", en: "fork", ja: "フォーク" },
      { es: "la cuchara", en: "spoon", ja: "スプーン" },
      { es: "los palillos", en: "chopsticks", ja: "箸" },
      { es: "el bol / el tazón", en: "bowl", ja: "ボウル、お椀" },
      { es: "la taza", en: "cup / mug", ja: "カップ、マグ" },
      { es: "la copa", en: "wine glass", ja: "ワイングラス、グラス" },
      { es: "la botella", en: "bottle", ja: "瓶、ボトル" },
      { es: "la jarra", en: "jug / pitcher", ja: "水差し、ジョッキ" },
      { es: "la tabla de cortar", en: "cutting board", ja: "まな板" },
      { es: "el fregadero", en: "kitchen sink", ja: "流し台、シンク" },
      { es: "el grifo", en: "faucet / tap", ja: "蛇口" },
      { es: "la esponja", en: "sponge", ja: "スポンジ" },
      { es: "el delantal", en: "apron", ja: "エプロン" },
      { es: "la servilleta", en: "napkin", ja: "ナプキン" },
      { es: "el mantel", en: "tablecloth", ja: "テーブルクロス" },
      { es: "la bandeja", en: "tray", ja: "トレー、お盆" },
      { es: "el táper", en: "food container", ja: "保存容器、タッパー" },
      { es: "el papel de aluminio", en: "aluminum foil", ja: "アルミホイル" },
      { es: "la tapa", en: "lid", ja: "ふた" },
      { es: "la receta", en: "recipe", ja: "レシピ" },
      { es: "el ingrediente", en: "ingredient", ja: "材料、食材" },
      { es: "el hervidor", en: "kettle", ja: "やかん、ケトル" },
      { es: "la batidora", en: "blender / mixer", ja: "ミキサー" },
      { es: "la tostadora", en: "toaster", ja: "トースター" },
      { es: "la cafetera", en: "coffee maker", ja: "コーヒーメーカー" },
      { es: "el sacacorchos", en: "corkscrew", ja: "ワインオープナー" },
      { es: "el abrelatas", en: "can opener", ja: "缶切り" },
      { es: "el colador", en: "strainer / colander", ja: "ざる、こし器" },
      { es: "el arrocero / la arrocera", en: "rice cooker", ja: "炊飯器" },
    ],
  },
  {
    cat: "日用品・身の回り", icon: "🧴",
    items: [
      { es: "el jabón", en: "soap", ja: "石けん" },
      { es: "el champú", en: "shampoo", ja: "シャンプー" },
      { es: "la pasta de dientes", en: "toothpaste", ja: "歯磨き粉" },
      { es: "el cepillo de dientes", en: "toothbrush", ja: "歯ブラシ" },
      { es: "el peine", en: "comb", ja: "くし" },
      { es: "la toalla", en: "towel", ja: "タオル" },
      { es: "el papel higiénico", en: "toilet paper", ja: "トイレットペーパー" },
      { es: "el pañuelo de papel", en: "tissue", ja: "ティッシュ" },
      { es: "la maquinilla de afeitar", en: "razor", ja: "カミソリ" },
      { es: "el secador de pelo", en: "hair dryer", ja: "ドライヤー" },
      { es: "el maquillaje", en: "makeup", ja: "化粧、メイク" },
      { es: "la crema", en: "cream / lotion", ja: "クリーム" },
      { es: "el perfume", en: "perfume", ja: "香水" },
      { es: "el desodorante", en: "deodorant", ja: "制汗剤、デオドラント" },
      { es: "el protector solar", en: "sunscreen", ja: "日焼け止め" },
      { es: "las tijeras", en: "scissors", ja: "はさみ" },
      { es: "el paraguas", en: "umbrella", ja: "傘" },
      { es: "la pila", en: "battery (dry cell)", ja: "乾電池" },
      { es: "la vela", en: "candle", ja: "ろうそく、キャンドル" },
      { es: "la cerilla", en: "match", ja: "マッチ" },
      { es: "el mechero", en: "lighter", ja: "ライター" },
      { es: "la linterna", en: "flashlight", ja: "懐中電灯" },
      { es: "la escoba", en: "broom", ja: "ほうき" },
      { es: "la fregona", en: "mop", ja: "モップ" },
      { es: "el trapo", en: "rag / cloth", ja: "雑巾、布巾" },
      { es: "el detergente", en: "detergent", ja: "洗剤" },
      { es: "la aguja", en: "needle", ja: "針" },
      { es: "el hilo", en: "thread", ja: "糸" },
      { es: "la cinta adhesiva", en: "tape", ja: "テープ" },
      { es: "el pegamento", en: "glue", ja: "のり、接着剤" },
      { es: "las gafas", en: "glasses", ja: "メガネ" },
      { es: "las gafas de sol", en: "sunglasses", ja: "サングラス" },
      { es: "las lentillas", en: "contact lenses", ja: "コンタクトレンズ" },
      { es: "el bolso", en: "handbag / purse", ja: "ハンドバッグ、かばん" },
      { es: "la mochila", en: "backpack", ja: "リュック" },
      { es: "la cartera", en: "wallet", ja: "財布" },
      { es: "el paquete", en: "package / parcel", ja: "小包、パッケージ" },
      { es: "la caja", en: "box", ja: "箱" },
      { es: "la bolsa", en: "bag", ja: "袋、バッグ" },
      { es: "el objeto", en: "object", ja: "物、物体" },
    ],
  },
  {
    cat: "野菜", icon: "🥕",
    items: [
      { es: "la patata / la papa", en: "potato", ja: "じゃがいも" },
      { es: "el tomate", en: "tomato", ja: "トマト" },
      { es: "la cebolla", en: "onion", ja: "玉ねぎ" },
      { es: "el ajo", en: "garlic", ja: "にんにく" },
      { es: "la zanahoria", en: "carrot", ja: "にんじん" },
      { es: "la lechuga", en: "lettuce", ja: "レタス" },
      { es: "el pepino", en: "cucumber", ja: "きゅうり" },
      { es: "el pimiento", en: "bell pepper", ja: "ピーマン、パプリカ" },
      { es: "la berenjena", en: "eggplant", ja: "なす" },
      { es: "el calabacín", en: "zucchini", ja: "ズッキーニ" },
      { es: "la calabaza", en: "pumpkin", ja: "かぼちゃ" },
      { es: "el brócoli", en: "broccoli", ja: "ブロッコリー" },
      { es: "la coliflor", en: "cauliflower", ja: "カリフラワー" },
      { es: "las espinacas", en: "spinach", ja: "ほうれん草" },
      { es: "el maíz", en: "corn", ja: "とうもろこし" },
      { es: "los guisantes", en: "peas", ja: "グリーンピース" },
      { es: "las judías verdes", en: "green beans", ja: "さやいんげん" },
      { es: "el champiñón", en: "mushroom", ja: "マッシュルーム" },
      { es: "la seta", en: "mushroom (wild)", ja: "きのこ" },
      { es: "el rábano", en: "radish", ja: "大根、ラディッシュ" },
      { es: "el apio", en: "celery", ja: "セロリ" },
      { es: "el puerro", en: "leek", ja: "長ねぎ、リーキ" },
      { es: "el repollo / la col", en: "cabbage", ja: "キャベツ" },
      { es: "el aguacate", en: "avocado", ja: "アボカド" },
      { es: "el jengibre", en: "ginger", ja: "しょうが" },
      { es: "el perejil", en: "parsley", ja: "パセリ" },
      { es: "la batata / el boniato", en: "sweet potato", ja: "さつまいも" },
    ],
  },
  {
    cat: "果物", icon: "🍓",
    items: [
      { es: "la manzana", en: "apple", ja: "りんご" },
      { es: "el plátano / la banana", en: "banana", ja: "バナナ" },
      { es: "la naranja", en: "orange", ja: "オレンジ" },
      { es: "el limón", en: "lemon", ja: "レモン" },
      { es: "la fresa", en: "strawberry", ja: "いちご" },
      { es: "la uva", en: "grape", ja: "ぶどう" },
      { es: "la sandía", en: "watermelon", ja: "すいか" },
      { es: "el melón", en: "melon", ja: "メロン" },
      { es: "el melocotón / el durazno", en: "peach", ja: "桃" },
      { es: "la pera", en: "pear", ja: "洋なし" },
      { es: "la piña", en: "pineapple", ja: "パイナップル" },
      { es: "el mango", en: "mango", ja: "マンゴー" },
      { es: "el kiwi", en: "kiwi", ja: "キウイ" },
      { es: "la cereza", en: "cherry", ja: "さくらんぼ" },
      { es: "la ciruela", en: "plum", ja: "プラム、すもも" },
      { es: "la frambuesa", en: "raspberry", ja: "ラズベリー" },
      { es: "el arándano", en: "blueberry", ja: "ブルーベリー" },
      { es: "la mandarina", en: "mandarin / tangerine", ja: "みかん" },
      { es: "el pomelo", en: "grapefruit", ja: "グレープフルーツ" },
      { es: "el coco", en: "coconut", ja: "ココナッツ" },
    ],
  },
  {
    cat: "肉・魚介・卵・乳製品", icon: "🥩",
    items: [
      { es: "la ternera", en: "beef / veal", ja: "牛肉" },
      { es: "el cerdo", en: "pork / pig", ja: "豚肉、豚" },
      { es: "el cordero", en: "lamb", ja: "子羊の肉、ラム" },
      { es: "el jamón", en: "ham", ja: "ハム、生ハム" },
      { es: "el beicon / el tocino", en: "bacon", ja: "ベーコン" },
      { es: "la salchicha", en: "sausage", ja: "ソーセージ" },
      { es: "el chorizo", en: "chorizo", ja: "チョリソ" },
      { es: "el pavo", en: "turkey", ja: "七面鳥" },
      { es: "la carne picada", en: "ground meat", ja: "ひき肉" },
      { es: "el filete", en: "steak / fillet", ja: "ステーキ、切り身" },
      { es: "el atún", en: "tuna", ja: "まぐろ、ツナ" },
      { es: "el salmón", en: "salmon", ja: "サーモン、鮭" },
      { es: "la sardina", en: "sardine", ja: "いわし" },
      { es: "el bacalao", en: "cod", ja: "たら" },
      { es: "el marisco", en: "seafood / shellfish", ja: "魚介、シーフード" },
      { es: "la gamba / el camarón", en: "shrimp", ja: "えび" },
      { es: "el cangrejo", en: "crab", ja: "かに" },
      { es: "la langosta", en: "lobster", ja: "ロブスター、伊勢えび" },
      { es: "el mejillón", en: "mussel", ja: "ムール貝" },
      { es: "la almeja", en: "clam", ja: "あさり、二枚貝" },
      { es: "el calamar", en: "squid", ja: "いか" },
      { es: "el pulpo", en: "octopus", ja: "たこ" },
      { es: "el huevo", en: "egg", ja: "卵" },
      { es: "el queso", en: "cheese", ja: "チーズ" },
      { es: "el yogur", en: "yogurt", ja: "ヨーグルト" },
      { es: "la mantequilla", en: "butter", ja: "バター" },
      { es: "la nata", en: "cream (dairy)", ja: "生クリーム" },
      { es: "el tofu", en: "tofu", ja: "豆腐" },
    ],
  },
  {
    cat: "食材・調味料", icon: "🧂",
    items: [
      { es: "la sal", en: "salt", ja: "塩" },
      { es: "la pimienta", en: "pepper (spice)", ja: "こしょう" },
      { es: "el azúcar", en: "sugar", ja: "砂糖" },
      { es: "la miel", en: "honey", ja: "はちみつ" },
      { es: "el aceite", en: "oil", ja: "油" },
      { es: "el aceite de oliva", en: "olive oil", ja: "オリーブオイル" },
      { es: "el vinagre", en: "vinegar", ja: "酢" },
      { es: "la salsa", en: "sauce", ja: "ソース" },
      { es: "la salsa de soja", en: "soy sauce", ja: "しょうゆ" },
      { es: "la mostaza", en: "mustard", ja: "マスタード、からし" },
      { es: "la mayonesa", en: "mayonnaise", ja: "マヨネーズ" },
      { es: "el kétchup", en: "ketchup", ja: "ケチャップ" },
      { es: "la harina", en: "flour", ja: "小麦粉" },
      { es: "los fideos", en: "noodles", ja: "麺" },
      { es: "los espaguetis", en: "spaghetti", ja: "スパゲッティ、パスタ" },
      { es: "las especias", en: "spices", ja: "スパイス、香辛料" },
      { es: "la canela", en: "cinnamon", ja: "シナモン" },
      { es: "el curry", en: "curry", ja: "カレー" },
      { es: "la sopa", en: "soup", ja: "スープ" },
      { es: "el caldo", en: "broth / stock", ja: "だし、スープの素" },
      { es: "los frijoles / las alubias", en: "beans", ja: "豆" },
      { es: "las lentejas", en: "lentils", ja: "レンズ豆" },
      { es: "los garbanzos", en: "chickpeas", ja: "ひよこ豆" },
      { es: "las almendras", en: "almonds", ja: "アーモンド" },
      { es: "los cacahuetes", en: "peanuts", ja: "ピーナッツ" },
      { es: "las nueces", en: "walnuts / nuts", ja: "くるみ、ナッツ" },
      { es: "la avena", en: "oats", ja: "オートミール" },
      { es: "los cereales", en: "cereal", ja: "シリアル" },
      { es: "la mermelada", en: "jam", ja: "ジャム" },
    ],
  },
  {
    cat: "パン・お菓子", icon: "🍰",
    items: [
      { es: "el bocadillo", en: "sandwich (baguette)", ja: "ボカディージョ、サンドイッチ" },
      { es: "el sándwich", en: "sandwich", ja: "サンドイッチ" },
      { es: "la tostada", en: "toast", ja: "トースト" },
      { es: "el cruasán", en: "croissant", ja: "クロワッサン" },
      { es: "la galleta", en: "cookie", ja: "クッキー、ビスケット" },
      { es: "el pastel", en: "cake", ja: "ケーキ" },
      { es: "la tarta", en: "tart / cake", ja: "タルト、ホールケーキ" },
      { es: "el helado", en: "ice cream", ja: "アイスクリーム" },
      { es: "el chocolate", en: "chocolate", ja: "チョコレート" },
      { es: "el caramelo", en: "candy", ja: "あめ、キャラメル" },
      { es: "el chicle", en: "chewing gum", ja: "ガム" },
      { es: "las patatas fritas", en: "french fries / chips", ja: "フライドポテト、ポテトチップス" },
      { es: "los dulces", en: "sweets / candy", ja: "甘いもの、お菓子" },
      { es: "el flan", en: "flan / custard pudding", ja: "プリン" },
      { es: "los churros", en: "churros", ja: "チュロス" },
      { es: "las palomitas", en: "popcorn", ja: "ポップコーン" },
    ],
  },
  {
    cat: "飲み物", icon: "🥤",
    items: [
      { es: "el zumo / el jugo", en: "juice", ja: "ジュース" },
      { es: "el refresco", en: "soft drink / soda", ja: "清涼飲料、ソーダ" },
      { es: "el vino", en: "wine", ja: "ワイン" },
      { es: "el vino tinto", en: "red wine", ja: "赤ワイン" },
      { es: "el vino blanco", en: "white wine", ja: "白ワイン" },
      { es: "el champán", en: "champagne", ja: "シャンパン" },
      { es: "la sangría", en: "sangria", ja: "サングリア" },
      { es: "la limonada", en: "lemonade", ja: "レモネード" },
      { es: "el batido", en: "milkshake / smoothie", ja: "シェイク、スムージー" },
      { es: "el café con leche", en: "coffee with milk / latte", ja: "カフェラテ、ミルク入りコーヒー" },
      { es: "el café solo", en: "black coffee / espresso", ja: "ブラックコーヒー、エスプレッソ" },
      { es: "el té verde", en: "green tea", ja: "緑茶" },
      { es: "la infusión", en: "herbal tea", ja: "ハーブティー" },
      { es: "el agua con gas", en: "sparkling water", ja: "炭酸水" },
      { es: "el agua mineral", en: "mineral water", ja: "ミネラルウォーター" },
      { es: "el hielo", en: "ice", ja: "氷" },
    ],
  },
  {
    cat: "食事・レストラン", icon: "🍽",
    items: [
      { es: "la comida", en: "food / meal / lunch", ja: "食べ物、食事、昼食" },
      { es: "el sabor", en: "flavor / taste", ja: "味" },
      { es: "la merienda", en: "afternoon snack", ja: "おやつ、軽食" },
      { es: "el aperitivo", en: "appetizer / aperitif", ja: "前菜、食前酒" },
      { es: "las tapas", en: "tapas (small dishes)", ja: "タパス、小皿料理" },
      { es: "el primer plato", en: "first course", ja: "前菜、一皿目" },
      { es: "el segundo plato", en: "main course", ja: "メイン、二皿目" },
      { es: "el plato del día", en: "dish of the day", ja: "本日の一皿、日替わり" },
      { es: "la especialidad", en: "specialty", ja: "名物、おすすめ料理" },
      { es: "la reserva", en: "reservation", ja: "予約" },
      { es: "el cocinero / la cocinera", en: "cook / chef", ja: "料理人、シェフ" },
      { es: "la barra", en: "bar counter", ja: "カウンター、バル" },
      { es: "la carta", en: "menu (list)", ja: "メニュー表" },
      { es: "el pedido", en: "order", ja: "注文" },
      { es: "la comida para llevar", en: "takeout food", ja: "テイクアウト" },
      { es: "el hambre", en: "hunger", ja: "空腹" },
      { es: "la sed", en: "thirst", ja: "のどの渇き" },
      { es: "el olor", en: "smell", ja: "におい、香り" },
    ],
  },
];
