// ¡Escucha! 単語データ 3/4 — 街・交通・旅行・仕事・学校・テクノロジー・趣味・お金・時間

const WORD_PART_3 = [
  {
    cat: "街・場所", icon: "🏙",
    items: [
      { es: "el pueblo", en: "town / village", ja: "町、村" },
      { es: "la capital", en: "capital city", ja: "首都" },
      { es: "el centro", en: "center / downtown", ja: "中心街、センター" },
      { es: "la plaza", en: "square / plaza", ja: "広場" },
      { es: "la avenida", en: "avenue", ja: "大通り" },
      { es: "la esquina", en: "corner", ja: "角、曲がり角" },
      { es: "la acera", en: "sidewalk", ja: "歩道" },
      { es: "el cruce", en: "crossing / intersection", ja: "交差点" },
      { es: "el semáforo", en: "traffic light", ja: "信号機" },
      { es: "el paso de cebra", en: "crosswalk", ja: "横断歩道" },
      { es: "el puente", en: "bridge", ja: "橋" },
      { es: "el túnel", en: "tunnel", ja: "トンネル" },
      { es: "la fuente", en: "fountain", ja: "噴水" },
      { es: "el parque", en: "park", ja: "公園" },
      { es: "el edificio de oficinas", en: "office building", ja: "オフィスビル" },
      { es: "el ayuntamiento", en: "city hall", ja: "市役所" },
      { es: "la comisaría", en: "police station", ja: "警察署" },
      { es: "el correo / la oficina de correos", en: "post office", ja: "郵便局" },
      { es: "la biblioteca", en: "library", ja: "図書館" },
      { es: "el museo", en: "museum", ja: "美術館、博物館" },
      { es: "el teatro", en: "theater", ja: "劇場" },
      { es: "el cine", en: "movie theater", ja: "映画館" },
      { es: "la iglesia", en: "church", ja: "教会" },
      { es: "la catedral", en: "cathedral", ja: "大聖堂" },
      { es: "el templo", en: "temple", ja: "寺、神殿" },
      { es: "el castillo", en: "castle", ja: "城" },
      { es: "la torre", en: "tower", ja: "塔、タワー" },
      { es: "el monumento", en: "monument", ja: "記念碑、モニュメント" },
      { es: "el estadio", en: "stadium", ja: "スタジアム" },
      { es: "el gimnasio", en: "gym", ja: "ジム、体育館" },
      { es: "la peluquería", en: "hair salon / barbershop", ja: "美容院、床屋" },
      { es: "la gasolinera", en: "gas station", ja: "ガソリンスタンド" },
      { es: "el aparcamiento", en: "parking lot", ja: "駐車場" },
      { es: "la cafetería", en: "café / coffee shop", ja: "カフェ、喫茶店" },
      { es: "el bar", en: "bar / pub", ja: "バル、バー" },
      { es: "la zona", en: "zone / area", ja: "地域、ゾーン" },
      { es: "el lugar", en: "place", ja: "場所" },
      { es: "el sitio", en: "place / site / spot", ja: "場所、スポット" },
      { es: "las afueras", en: "outskirts / suburbs", ja: "郊外" },
      { es: "el campo", en: "countryside / field", ja: "田舎、畑、フィールド" },
    ],
  },
  {
    cat: "店・買い物", icon: "🛒",
    items: [
      { es: "el supermercado", en: "supermarket", ja: "スーパー" },
      { es: "el mercado", en: "market", ja: "市場、マーケット" },
      { es: "la panadería", en: "bakery", ja: "パン屋" },
      { es: "la pastelería", en: "pastry shop", ja: "ケーキ屋" },
      { es: "la carnicería", en: "butcher shop", ja: "肉屋" },
      { es: "la pescadería", en: "fish shop", ja: "魚屋" },
      { es: "la frutería", en: "fruit shop", ja: "八百屋、果物屋" },
      { es: "la librería", en: "bookstore", ja: "本屋" },
      { es: "la floristería", en: "flower shop", ja: "花屋" },
      { es: "la juguetería", en: "toy store", ja: "おもちゃ屋" },
      { es: "la zapatería", en: "shoe store", ja: "靴屋" },
      { es: "la tienda de ropa", en: "clothing store", ja: "服屋" },
      { es: "el centro comercial", en: "shopping mall", ja: "ショッピングモール" },
      { es: "los grandes almacenes", en: "department store", ja: "デパート" },
      { es: "la tienda de conveniencia", en: "convenience store", ja: "コンビニ" },
      { es: "el quiosco", en: "kiosk / newsstand", ja: "キオスク、売店" },
      { es: "el escaparate", en: "shop window", ja: "ショーウィンドウ" },
      { es: "la caja registradora", en: "cash register", ja: "レジ" },
      { es: "el carrito", en: "shopping cart", ja: "カート" },
      { es: "la cesta", en: "basket", ja: "かご" },
      { es: "el cliente / la clienta", en: "customer", ja: "客" },
      { es: "el dependiente / la dependienta", en: "shop assistant", ja: "店員" },
      { es: "la oferta", en: "offer / sale", ja: "特売、セール品" },
      { es: "las rebajas", en: "sales (discount season)", ja: "バーゲン、セール" },
      { es: "el descuento", en: "discount", ja: "割引" },
      { es: "el recibo", en: "receipt", ja: "レシート、領収書" },
      { es: "el ticket", en: "ticket / receipt", ja: "チケット、レシート" },
      { es: "la devolución", en: "return / refund", ja: "返品、返金" },
      { es: "la compra", en: "purchase / shopping", ja: "買い物、購入" },
      { es: "la venta", en: "sale", ja: "販売" },
      { es: "el regalo", en: "gift / present", ja: "プレゼント、贈り物" },
      { es: "la calidad", en: "quality", ja: "品質" },
      { es: "la cantidad", en: "quantity / amount", ja: "量、数量" },
      { es: "gratis", en: "free (no cost)", ja: "無料の" },
      { es: "la marca de la casa", en: "store brand", ja: "プライベートブランド" },
    ],
  },
  {
    cat: "交通・移動", icon: "🚗",
    items: [
      { es: "el tráfico", en: "traffic", ja: "交通、渋滞" },
      { es: "el atasco", en: "traffic jam", ja: "渋滞" },
      { es: "la carretera", en: "road / highway", ja: "道路、幹線道路" },
      { es: "la autopista", en: "freeway / motorway", ja: "高速道路" },
      { es: "el camino", en: "path / way", ja: "道、道のり" },
      { es: "la moto", en: "motorcycle", ja: "バイク" },
      { es: "el camión", en: "truck", ja: "トラック" },
      { es: "la furgoneta", en: "van", ja: "バン、ワゴン車" },
      { es: "el barco", en: "boat / ship", ja: "船" },
      { es: "el ferry", en: "ferry", ja: "フェリー" },
      { es: "el helicóptero", en: "helicopter", ja: "ヘリコプター" },
      { es: "el tranvía", en: "tram / streetcar", ja: "路面電車、トラム" },
      { es: "el AVE / el tren de alta velocidad", en: "high-speed train", ja: "高速鉄道、新幹線" },
      { es: "el andén", en: "platform", ja: "ホーム、プラットホーム" },
      { es: "la vía", en: "track / rail", ja: "線路、〜番線" },
      { es: "el vagón", en: "train car", ja: "車両" },
      { es: "el asiento", en: "seat", ja: "座席、シート" },
      { es: "el conductor / la conductora", en: "driver", ja: "運転手" },
      { es: "el/la pasajero/a", en: "passenger", ja: "乗客" },
      { es: "el horario", en: "schedule / timetable", ja: "時刻表、スケジュール" },
      { es: "el retraso", en: "delay", ja: "遅れ、遅延" },
      { es: "la línea", en: "line", ja: "路線、ライン" },
      { es: "el transbordo", en: "transfer / change", ja: "乗り換え" },
      { es: "el destino", en: "destination", ja: "目的地、行き先" },
      { es: "la ida", en: "one-way (trip)", ja: "行き、片道" },
      { es: "la vuelta", en: "return (trip)", ja: "帰り、往復の帰路" },
      { es: "el billete de ida y vuelta", en: "round-trip ticket", ja: "往復切符" },
      { es: "la tarifa", en: "fare / rate", ja: "運賃、料金" },
      { es: "la gasolina", en: "gasoline", ja: "ガソリン" },
      { es: "el carné de conducir", en: "driver's license", ja: "運転免許証" },
      { es: "la rueda", en: "wheel / tire", ja: "車輪、タイヤ" },
      { es: "el volante", en: "steering wheel", ja: "ハンドル" },
      { es: "el freno", en: "brake", ja: "ブレーキ" },
      { es: "el casco", en: "helmet", ja: "ヘルメット" },
      { es: "la multa", en: "fine / ticket", ja: "罰金、違反切符" },
      { es: "la velocidad", en: "speed", ja: "速度、スピード" },
      { es: "la distancia", en: "distance", ja: "距離" },
      { es: "el kilómetro", en: "kilometer", ja: "キロメートル" },
      { es: "el metro (medida)", en: "meter (unit)", ja: "メートル" },
      { es: "el mapa", en: "map", ja: "地図" },
    ],
  },
  {
    cat: "旅行・ホテル", icon: "✈️",
    items: [
      { es: "el turismo", en: "tourism / sightseeing", ja: "観光" },
      { es: "el/la turista", en: "tourist", ja: "観光客" },
      { es: "el/la guía", en: "guide", ja: "ガイド" },
      { es: "la agencia de viajes", en: "travel agency", ja: "旅行代理店" },
      { es: "el hotel", en: "hotel", ja: "ホテル" },
      { es: "el hostal", en: "hostel / guesthouse", ja: "ホステル、民宿" },
      { es: "la recepción", en: "reception / front desk", ja: "受付、フロント" },
      { es: "el/la recepcionista", en: "receptionist", ja: "受付係" },
      { es: "la llegada", en: "arrival", ja: "到着" },
      { es: "el equipaje", en: "luggage", ja: "荷物" },
      { es: "la habitación doble", en: "double room", ja: "ダブルルーム" },
      { es: "la habitación individual", en: "single room", ja: "シングルルーム" },
      { es: "la vista", en: "view", ja: "眺め、景色" },
      { es: "el alojamiento", en: "accommodation", ja: "宿泊、宿" },
      { es: "el vuelo", en: "flight", ja: "フライト、便" },
      { es: "la escala", en: "layover / stopover", ja: "乗り継ぎ" },
      { es: "la aduana", en: "customs", ja: "税関" },
      { es: "el visado", en: "visa", ja: "ビザ、査証" },
      { es: "la frontera", en: "border", ja: "国境" },
      { es: "el seguro de viaje", en: "travel insurance", ja: "旅行保険" },
      { es: "la excursión", en: "excursion / day trip", ja: "遠足、日帰り旅行" },
      { es: "la aventura", en: "adventure", ja: "冒険" },
      { es: "el recuerdo / el souvenir", en: "souvenir", ja: "お土産" },
      { es: "la cámara", en: "camera", ja: "カメラ" },
      { es: "la postal", en: "postcard", ja: "絵はがき" },
      { es: "la tienda de campaña", en: "tent", ja: "テント" },
      { es: "el camping", en: "camping / campsite", ja: "キャンプ、キャンプ場" },
      { es: "el saco de dormir", en: "sleeping bag", ja: "寝袋" },
      { es: "el paseo", en: "walk / stroll", ja: "散歩" },
      { es: "la caminata", en: "hike", ja: "ハイキング、長歩き" },
      { es: "el descanso del viaje", en: "rest stop", ja: "休憩" },
      { es: "el itinerario", en: "itinerary", ja: "旅程" },
      { es: "la propina del guía", en: "tip for the guide", ja: "ガイドへのチップ" },
      { es: "el extranjero", en: "abroad / overseas", ja: "外国、海外" },
      { es: "el mundo hispano", en: "Spanish-speaking world", ja: "スペイン語圏" },
    ],
  },
  {
    cat: "仕事・オフィス", icon: "💼",
    items: [
      { es: "la empresa", en: "company", ja: "会社、企業" },
      { es: "la oficina", en: "office", ja: "オフィス、事務所" },
      { es: "el despacho", en: "office (private) / study", ja: "個室オフィス、書斎" },
      { es: "el jefe / la jefa", en: "boss", ja: "上司、ボス" },
      { es: "el empleado / la empleada", en: "employee", ja: "従業員、社員" },
      { es: "el compañero / la compañera de trabajo", en: "coworker", ja: "同僚" },
      { es: "el sueldo / el salario", en: "salary / wage", ja: "給料" },
      { es: "el contrato", en: "contract", ja: "契約" },
      { es: "la entrevista", en: "interview", ja: "面接、インタビュー" },
      { es: "el currículum", en: "resume / CV", ja: "履歴書" },
      { es: "la experiencia", en: "experience", ja: "経験" },
      { es: "la habilidad", en: "skill / ability", ja: "能力、スキル" },
      { es: "la reunión", en: "meeting", ja: "会議、ミーティング" },
      { es: "el proyecto", en: "project", ja: "プロジェクト、企画" },
      { es: "el informe", en: "report", ja: "報告書、レポート" },
      { es: "el documento", en: "document", ja: "書類、文書" },
      { es: "la firma", en: "signature", ja: "署名、サイン" },
      { es: "la tarea", en: "task / homework", ja: "仕事、課題、宿題" },
      { es: "el plazo", en: "deadline", ja: "締め切り、期限" },
      { es: "el horario de trabajo", en: "work schedule", ja: "勤務時間" },
      { es: "el turno", en: "shift / turn", ja: "シフト、順番" },
      { es: "las horas extras", en: "overtime", ja: "残業" },
      { es: "el día libre", en: "day off", ja: "休みの日" },
      { es: "la baja", en: "sick leave", ja: "病欠、休職" },
      { es: "la jubilación", en: "retirement", ja: "退職、年金生活" },
      { es: "el desempleo / el paro", en: "unemployment", ja: "失業" },
      { es: "el negocio", en: "business", ja: "ビジネス、商売" },
      { es: "el éxito profesional", en: "professional success", ja: "仕事での成功" },
      { es: "la carrera", en: "career / degree / race", ja: "キャリア、経歴、競走" },
      { es: "el puesto", en: "position / post", ja: "職、ポスト" },
      { es: "la responsabilidad", en: "responsibility", ja: "責任" },
      { es: "el objetivo", en: "goal / objective", ja: "目標" },
      { es: "el resultado", en: "result", ja: "結果" },
      { es: "el esfuerzo", en: "effort", ja: "努力" },
      { es: "la solución", en: "solution", ja: "解決策" },
      { es: "la decisión", en: "decision", ja: "決定、決断" },
      { es: "la información", en: "information", ja: "情報" },
      { es: "la noticia", en: "news", ja: "ニュース、知らせ" },
      { es: "el servicio", en: "service", ja: "サービス" },
      { es: "el producto", en: "product", ja: "製品、商品" },
    ],
  },
  {
    cat: "職業", icon: "👩‍⚕️",
    items: [
      { es: "la profesión", en: "profession", ja: "職業" },
      { es: "el profesor / la profesora", en: "teacher", ja: "先生、教師" },
      { es: "el ingeniero / la ingeniera", en: "engineer", ja: "エンジニア、技師" },
      { es: "el abogado / la abogada", en: "lawyer", ja: "弁護士" },
      { es: "el/la policía", en: "police officer", ja: "警察官" },
      { es: "el bombero / la bombera", en: "firefighter", ja: "消防士" },
      { es: "el/la soldado", en: "soldier", ja: "兵士" },
      { es: "el/la artista", en: "artist", ja: "芸術家、アーティスト" },
      { es: "el/la cantante", en: "singer", ja: "歌手" },
      { es: "el actor / la actriz", en: "actor / actress", ja: "俳優、女優" },
      { es: "el/la periodista", en: "journalist", ja: "記者、ジャーナリスト" },
      { es: "el escritor / la escritora", en: "writer", ja: "作家" },
      { es: "el/la deportista", en: "athlete", ja: "スポーツ選手" },
      { es: "el/la futbolista", en: "soccer player", ja: "サッカー選手" },
      { es: "el panadero / la panadera", en: "baker", ja: "パン職人" },
      { es: "el carnicero / la carnicera", en: "butcher", ja: "肉屋さん" },
      { es: "el peluquero / la peluquera", en: "hairdresser", ja: "美容師" },
      { es: "el/la taxista", en: "taxi driver", ja: "タクシー運転手" },
      { es: "el/la piloto", en: "pilot", ja: "パイロット" },
      { es: "el/la agricultor/a", en: "farmer", ja: "農家" },
      { es: "el/la pescador/a", en: "fisherman", ja: "漁師" },
      { es: "el carpintero / la carpintera", en: "carpenter", ja: "大工" },
      { es: "el/la electricista", en: "electrician", ja: "電気工事士" },
      { es: "el fontanero / la fontanera", en: "plumber", ja: "配管工" },
      { es: "el/la programador/a", en: "programmer", ja: "プログラマー" },
      { es: "el/la diseñador/a", en: "designer", ja: "デザイナー" },
      { es: "el/la científico/a", en: "scientist", ja: "科学者" },
      { es: "el/la investigador/a", en: "researcher", ja: "研究者" },
      { es: "el/la traductor/a", en: "translator", ja: "翻訳者" },
      { es: "el/la intérprete", en: "interpreter", ja: "通訳" },
      { es: "el/la voluntario/a", en: "volunteer", ja: "ボランティア" },
      { es: "el/la dueño/a del negocio", en: "business owner", ja: "経営者、オーナー" },
      { es: "el/la funcionario/a", en: "civil servant", ja: "公務員" },
      { es: "el/la vendedor/a", en: "salesperson", ja: "販売員、営業" },
      { es: "el/la músico/a", en: "musician", ja: "音楽家、ミュージシャン" },
    ],
  },
  {
    cat: "学校・学び", icon: "🎓",
    items: [
      { es: "la universidad", en: "university / college", ja: "大学" },
      { es: "el instituto", en: "high school", ja: "高校" },
      { es: "la guardería", en: "nursery / daycare", ja: "保育園" },
      { es: "la clase", en: "class / classroom", ja: "授業、クラス、教室" },
      { es: "el aula", en: "classroom", ja: "教室" },
      { es: "el curso", en: "course / school year", ja: "講座、学年" },
      { es: "la lección", en: "lesson", ja: "レッスン、課" },
      { es: "el examen", en: "exam / test", ja: "試験、テスト" },
      { es: "la nota", en: "grade / note", ja: "成績、メモ" },
      { es: "el error", en: "mistake / error", ja: "間違い、エラー" },
      { es: "la duda", en: "doubt / question", ja: "疑問、迷い" },
      { es: "el conocimiento", en: "knowledge", ja: "知識" },
      { es: "la memoria", en: "memory", ja: "記憶、記憶力" },
      { es: "la atención", en: "attention", ja: "注意、注目" },
      { es: "el cuaderno", en: "notebook", ja: "ノート" },
      { es: "el lápiz", en: "pencil", ja: "鉛筆" },
      { es: "el bolígrafo", en: "pen", ja: "ボールペン" },
      { es: "la goma", en: "eraser", ja: "消しゴム" },
      { es: "la regla", en: "ruler / rule", ja: "定規、規則" },
      { es: "la mochila escolar", en: "school bag", ja: "通学かばん" },
      { es: "la pizarra", en: "blackboard / whiteboard", ja: "黒板、ホワイトボード" },
      { es: "el diccionario", en: "dictionary", ja: "辞書" },
      { es: "la página", en: "page", ja: "ページ" },
      { es: "el capítulo", en: "chapter", ja: "章" },
      { es: "el texto", en: "text", ja: "テキスト、文章" },
      { es: "la letra", en: "letter (alphabet) / handwriting", ja: "文字、字" },
      { es: "la gramática", en: "grammar", ja: "文法" },
      { es: "el vocabulario", en: "vocabulary", ja: "語彙、単語" },
      { es: "la pronunciación", en: "pronunciation", ja: "発音" },
      { es: "el acento", en: "accent", ja: "アクセント、なまり" },
      { es: "la traducción", en: "translation", ja: "翻訳" },
      { es: "el nivel", en: "level", ja: "レベル" },
      { es: "el/la principiante", en: "beginner", ja: "初心者" },
      { es: "el/la alumno/a", en: "pupil / student", ja: "生徒" },
      { es: "la beca", en: "scholarship", ja: "奨学金" },
      { es: "el título", en: "degree / title", ja: "学位、タイトル" },
      { es: "la ciencia", en: "science", ja: "科学" },
      { es: "las matemáticas", en: "mathematics", ja: "数学" },
      { es: "la física", en: "physics", ja: "物理" },
      { es: "el arte", en: "art", ja: "芸術、アート" },
    ],
  },
  {
    cat: "テクノロジー・ネット", icon: "📱",
    items: [
      { es: "el móvil / el celular", en: "cell phone", ja: "携帯電話、スマホ" },
      { es: "el ordenador / la computadora", en: "computer", ja: "パソコン、コンピューター" },
      { es: "el portátil", en: "laptop", ja: "ノートパソコン" },
      { es: "la tableta", en: "tablet", ja: "タブレット" },
      { es: "la pantalla", en: "screen", ja: "画面、スクリーン" },
      { es: "el teclado", en: "keyboard", ja: "キーボード" },
      { es: "el ratón (de ordenador)", en: "mouse (computer)", ja: "マウス" },
      { es: "los auriculares", en: "headphones / earphones", ja: "イヤホン、ヘッドホン" },
      { es: "el altavoz", en: "speaker", ja: "スピーカー" },
      { es: "el cargador", en: "charger", ja: "充電器" },
      { es: "el cable", en: "cable / cord", ja: "ケーブル、コード" },
      { es: "el wifi", en: "wi-fi", ja: "Wi-Fi" },
      { es: "la conexión", en: "connection", ja: "接続" },
      { es: "la contraseña", en: "password", ja: "パスワード" },
      { es: "la red", en: "network / the net", ja: "ネットワーク、網" },
      { es: "la aplicación / la app", en: "app / application", ja: "アプリ" },
      { es: "el programa", en: "program", ja: "プログラム、番組" },
      { es: "el archivo", en: "file", ja: "ファイル" },
      { es: "la carpeta", en: "folder", ja: "フォルダ" },
      { es: "la descarga", en: "download", ja: "ダウンロード" },
      { es: "el enlace", en: "link", ja: "リンク" },
      { es: "la página web", en: "website / web page", ja: "ウェブサイト、ページ" },
      { es: "el buscador", en: "search engine", ja: "検索エンジン" },
      { es: "el correo electrónico", en: "email", ja: "電子メール" },
      { es: "el usuario / la usuaria", en: "user", ja: "ユーザー" },
      { es: "la foto de perfil", en: "profile picture", ja: "プロフィール写真" },
      { es: "el vídeo en directo", en: "live video / stream", ja: "ライブ配信" },
      { es: "el juego en línea", en: "online game", ja: "オンラインゲーム" },
      { es: "la inteligencia artificial", en: "artificial intelligence", ja: "人工知能、AI" },
      { es: "el robot", en: "robot", ja: "ロボット" },
      { es: "la impresora", en: "printer", ja: "プリンター" },
      { es: "la máquina", en: "machine", ja: "機械" },
      { es: "la herramienta", en: "tool", ja: "道具、ツール" },
      { es: "el botón (de la pantalla)", en: "button (on screen)", ja: "ボタン(画面の)" },
      { es: "el sonido", en: "sound", ja: "音" },
      { es: "el volumen", en: "volume", ja: "音量、ボリューム" },
      { es: "el silencio", en: "silence", ja: "静けさ、沈黙" },
      { es: "la tecnología", en: "technology", ja: "テクノロジー、技術" },
    ],
  },
  {
    cat: "スポーツ・運動", icon: "⚽",
    items: [
      { es: "el partido", en: "match / game", ja: "試合" },
      { es: "el equipo", en: "team / equipment", ja: "チーム、装備" },
      { es: "el/la jugador/a", en: "player", ja: "選手、プレイヤー" },
      { es: "el entrenador / la entrenadora", en: "coach / trainer", ja: "コーチ、監督" },
      { es: "el entrenamiento", en: "training / practice", ja: "トレーニング、練習" },
      { es: "la pelota / el balón", en: "ball", ja: "ボール" },
      { es: "el gol", en: "goal (score)", ja: "ゴール、得点" },
      { es: "el punto", en: "point", ja: "点、ポイント" },
      { es: "la victoria", en: "victory / win", ja: "勝利" },
      { es: "la derrota", en: "defeat / loss", ja: "敗北" },
      { es: "el empate", en: "tie / draw", ja: "引き分け" },
      { es: "el campeonato", en: "championship", ja: "選手権、大会" },
      { es: "el trofeo", en: "trophy", ja: "トロフィー、優勝杯" },
      { es: "la medalla", en: "medal", ja: "メダル" },
      { es: "el árbitro / la árbitra", en: "referee", ja: "審判" },
      { es: "el/la aficionado/a", en: "fan / supporter", ja: "ファン、サポーター" },
      { es: "el baloncesto", en: "basketball", ja: "バスケットボール" },
      { es: "el tenis", en: "tennis", ja: "テニス" },
      { es: "el béisbol", en: "baseball", ja: "野球" },
      { es: "el voleibol", en: "volleyball", ja: "バレーボール" },
      { es: "la natación", en: "swimming", ja: "水泳" },
      { es: "el ciclismo", en: "cycling", ja: "サイクリング、自転車競技" },
      { es: "el atletismo", en: "track and field", ja: "陸上競技" },
      { es: "la carrera (deporte)", en: "race / running", ja: "レース、ランニング" },
      { es: "el maratón", en: "marathon", ja: "マラソン" },
      { es: "el yoga", en: "yoga", ja: "ヨガ" },
      { es: "el esquí", en: "skiing", ja: "スキー" },
      { es: "el golf", en: "golf", ja: "ゴルフ" },
      { es: "el boxeo", en: "boxing", ja: "ボクシング" },
      { es: "las artes marciales", en: "martial arts", ja: "武道、格闘技" },
      { es: "el senderismo", en: "hiking / trekking", ja: "ハイキング、登山" },
      { es: "la escalada", en: "climbing", ja: "クライミング" },
      { es: "el surf", en: "surfing", ja: "サーフィン" },
      { es: "el músculo en forma", en: "in shape / fitness", ja: "体づくり、フィットネス" },
      { es: "el campo de fútbol", en: "soccer field", ja: "サッカー場" },
    ],
  },
  {
    cat: "趣味・娯楽・文化", icon: "🎨",
    items: [
      { es: "el pasatiempo / el hobby", en: "hobby / pastime", ja: "趣味" },
      { es: "la canción", en: "song", ja: "歌、曲" },
      { es: "el concierto", en: "concert", ja: "コンサート、ライブ" },
      { es: "el grupo / la banda", en: "band / group", ja: "バンド、グループ" },
      { es: "la guitarra", en: "guitar", ja: "ギター" },
      { es: "el piano", en: "piano", ja: "ピアノ" },
      { es: "el tambor", en: "drum", ja: "太鼓、ドラム" },
      { es: "el baile", en: "dance", ja: "ダンス、踊り" },
      { es: "el flamenco", en: "flamenco", ja: "フラメンコ" },
      { es: "la salsa (baile)", en: "salsa (dance)", ja: "サルサ" },
      { es: "las entradas", en: "tickets (admission)", ja: "入場券、チケット" },
      { es: "el escenario", en: "stage", ja: "舞台、ステージ" },
      { es: "el público", en: "audience / public", ja: "観客、大衆" },
      { es: "la serie", en: "series / TV show", ja: "ドラマ、シリーズ" },
      { es: "el dibujo", en: "drawing", ja: "絵、イラスト" },
      { es: "la pintura", en: "painting / paint", ja: "絵画、絵の具" },
      { es: "la novela", en: "novel", ja: "小説" },
      { es: "el cuento", en: "short story / tale", ja: "短編、童話" },
      { es: "la revista", en: "magazine", ja: "雑誌" },
      { es: "el periódico", en: "newspaper", ja: "新聞" },
      { es: "el cómic", en: "comic", ja: "漫画、コミック" },
      { es: "el ajedrez", en: "chess", ja: "チェス" },
      { es: "las cartas", en: "playing cards", ja: "トランプ" },
      { es: "el videojuego", en: "video game", ja: "テレビゲーム" },
      { es: "el premio", en: "prize / award", ja: "賞、賞品" },
      { es: "la suerte en el juego", en: "luck in games", ja: "勝負運" },
      { es: "la lotería", en: "lottery", ja: "宝くじ" },
      { es: "la feria", en: "fair / festival", ja: "縁日、見本市" },
      { es: "el festival", en: "festival", ja: "フェス、祭り" },
      { es: "el desfile", en: "parade", ja: "パレード" },
      { es: "la tradición", en: "tradition", ja: "伝統" },
      { es: "la Navidad", en: "Christmas", ja: "クリスマス" },
      { es: "el Año Nuevo", en: "New Year", ja: "新年、正月" },
      { es: "la Semana Santa", en: "Holy Week / Easter", ja: "聖週間、イースター" },
      { es: "el día festivo", en: "holiday (public)", ja: "祝日" },
    ],
  },
  {
    cat: "お金・銀行", icon: "💰",
    items: [
      { es: "el euro", en: "euro", ja: "ユーロ" },
      { es: "el dólar", en: "dollar", ja: "ドル" },
      { es: "el yen", en: "yen", ja: "円" },
      { es: "la moneda", en: "coin / currency", ja: "硬貨、通貨" },
      { es: "el billete de banco", en: "banknote / bill", ja: "紙幣、お札" },
      { es: "el cambio", en: "change / exchange", ja: "おつり、両替、変化" },
      { es: "el cajero automático", en: "ATM", ja: "ATM" },
      { es: "la cuenta bancaria", en: "bank account", ja: "銀行口座" },
      { es: "la tarjeta de crédito", en: "credit card", ja: "クレジットカード" },
      { es: "el pago", en: "payment", ja: "支払い" },
      { es: "la factura", en: "invoice / bill", ja: "請求書" },
      { es: "el impuesto", en: "tax", ja: "税金" },
      { es: "el ahorro", en: "savings", ja: "貯金、節約" },
      { es: "el gasto", en: "expense / spending", ja: "出費、支出" },
      { es: "el presupuesto", en: "budget", ja: "予算" },
      { es: "la deuda", en: "debt", ja: "借金" },
      { es: "el préstamo", en: "loan", ja: "ローン、貸付" },
      { es: "la inversión", en: "investment", ja: "投資" },
      { es: "la economía", en: "economy", ja: "経済" },
      { es: "el valor", en: "value / worth", ja: "価値" },
      { es: "la riqueza", en: "wealth", ja: "富、豊かさ" },
      { es: "la pobreza", en: "poverty", ja: "貧困" },
      { es: "rico / rica", en: "rich / delicious", ja: "金持ちの、おいしい" },
      { es: "pobre", en: "poor", ja: "貧しい、かわいそうな" },
      { es: "la propiedad", en: "property", ja: "財産、所有" },
    ],
  },
  {
    cat: "時間・カレンダー", icon: "🗓",
    items: [
      { es: "el mes", en: "month", ja: "月(暦)" },
      { es: "el año", en: "year", ja: "年" },
      { es: "el siglo", en: "century", ja: "世紀" },
      { es: "la fecha", en: "date", ja: "日付" },
      { es: "el calendario", en: "calendar", ja: "カレンダー" },
      { es: "enero", en: "January", ja: "1月" },
      { es: "febrero", en: "February", ja: "2月" },
      { es: "marzo", en: "March", ja: "3月" },
      { es: "abril", en: "April", ja: "4月" },
      { es: "mayo", en: "May", ja: "5月" },
      { es: "junio", en: "June", ja: "6月" },
      { es: "julio", en: "July", ja: "7月" },
      { es: "agosto", en: "August", ja: "8月" },
      { es: "septiembre", en: "September", ja: "9月" },
      { es: "octubre", en: "October", ja: "10月" },
      { es: "noviembre", en: "November", ja: "11月" },
      { es: "diciembre", en: "December", ja: "12月" },
      { es: "la mañana", en: "morning", ja: "朝、午前" },
      { es: "la tarde", en: "afternoon / evening", ja: "午後、夕方" },
      { es: "la noche", en: "night", ja: "夜" },
      { es: "la medianoche", en: "midnight", ja: "真夜中" },
      { es: "el mediodía", en: "noon / midday", ja: "正午、昼" },
      { es: "el minuto", en: "minute", ja: "分" },
      { es: "el segundo", en: "second (time)", ja: "秒" },
      { es: "el rato", en: "a while / moment", ja: "しばらく、ひととき" },
      { es: "el pasado", en: "past", ja: "過去" },
      { es: "el presente", en: "present (time)", ja: "現在" },
      { es: "el principio", en: "beginning", ja: "初め、始まり" },
      { es: "el final", en: "end", ja: "終わり、最後" },
      { es: "la mitad", en: "half / middle", ja: "半分、真ん中" },
      { es: "el aniversario", en: "anniversary", ja: "記念日" },
      { es: "la época", en: "era / period / time", ja: "時代、時期" },
      { es: "la temporada", en: "season (period)", ja: "シーズン、時期" },
      { es: "el ritmo", en: "rhythm / pace", ja: "リズム、ペース" },
      { es: "la prisa", en: "hurry / rush", ja: "急ぎ" },
      { es: "la costumbre diaria", en: "daily habit", ja: "日課、日々の習慣" },
      { es: "la rutina", en: "routine", ja: "ルーティン、日常" },
      { es: "el madrugador / la madrugadora", en: "early riser", ja: "早起きの人" },
      { es: "la madrugada", en: "early morning / dawn hours", ja: "未明、明け方" },
      { es: "el anochecer", en: "nightfall", ja: "日暮れ、夕闇" },
    ],
  },
];
