// ¡Escucha! 単語データ 5/5 — 形容詞・副詞・つなぎ言葉・抽象名詞・素材

const WORD_PART_5 = [
  {
    cat: "形容詞① サイズ・状態", icon: "📐",
    items: [
      { es: "grande", en: "big / large", ja: "大きい" },
      { es: "pequeño / pequeña", en: "small", ja: "小さい" },
      { es: "alto / alta", en: "tall / high", ja: "高い、背が高い" },
      { es: "bajo / baja", en: "short / low", ja: "低い、背が低い" },
      { es: "largo / larga", en: "long", ja: "長い" },
      { es: "corto / corta", en: "short (length)", ja: "短い" },
      { es: "ancho / ancha", en: "wide", ja: "幅の広い" },
      { es: "estrecho / estrecha", en: "narrow", ja: "狭い、幅の狭い" },
      { es: "gordo / gorda", en: "fat", ja: "太った" },
      { es: "delgado / delgada", en: "thin / slim", ja: "やせた、細い" },
      { es: "fuerte", en: "strong", ja: "強い" },
      { es: "débil", en: "weak", ja: "弱い" },
      { es: "pesado / pesada", en: "heavy", ja: "重い" },
      { es: "ligero / ligera", en: "light (weight)", ja: "軽い" },
      { es: "duro / dura", en: "hard / tough", ja: "硬い、厳しい" },
      { es: "blando / blanda", en: "soft", ja: "柔らかい" },
      { es: "suave", en: "smooth / gentle", ja: "なめらかな、優しい" },
      { es: "limpio / limpia", en: "clean", ja: "きれいな、清潔な" },
      { es: "sucio / sucia", en: "dirty", ja: "汚い" },
      { es: "nuevo / nueva", en: "new", ja: "新しい" },
      { es: "viejo / vieja", en: "old", ja: "古い、年老いた" },
      { es: "joven", en: "young", ja: "若い" },
      { es: "antiguo / antigua", en: "ancient / former", ja: "昔の、古い" },
      { es: "moderno / moderna", en: "modern", ja: "現代的な、モダンな" },
      { es: "lleno / llena", en: "full", ja: "いっぱいの、満腹の" },
      { es: "vacío / vacía", en: "empty", ja: "空の" },
      { es: "abierto / abierta", en: "open", ja: "開いた" },
      { es: "cerrado / cerrada", en: "closed", ja: "閉まった" },
      { es: "roto / rota", en: "broken", ja: "壊れた、破れた" },
      { es: "entero / entera", en: "whole / entire", ja: "全部の、丸ごとの" },
      { es: "seco / seca", en: "dry", ja: "乾いた" },
      { es: "mojado / mojada", en: "wet", ja: "ぬれた" },
      { es: "húmedo / húmeda", en: "humid / damp", ja: "湿った、蒸し暑い" },
      { es: "caliente", en: "hot (temperature)", ja: "熱い、温かい" },
      { es: "fresco / fresca", en: "fresh / cool", ja: "新鮮な、涼しい" },
      { es: "rápido / rápida", en: "fast / quick", ja: "速い" },
      { es: "lento / lenta", en: "slow", ja: "遅い、ゆっくりな" },
      { es: "temprano", en: "early", ja: "早い、早く" },
      { es: "ruidoso / ruidosa", en: "noisy", ja: "うるさい" },
      { es: "silencioso / silenciosa", en: "silent / quiet", ja: "静かな" },
      { es: "peligroso / peligrosa", en: "dangerous", ja: "危険な" },
      { es: "sano / sana", en: "healthy", ja: "健康な" },
      { es: "oscuro / oscura", en: "dark", ja: "暗い" },
      { es: "brillante", en: "bright / shiny", ja: "輝く、明るい" },
    ],
  },
  {
    cat: "形容詞② 評価・印象", icon: "✨",
    items: [
      { es: "bonito / bonita", en: "pretty / nice", ja: "きれいな、かわいい" },
      { es: "hermoso / hermosa", en: "beautiful", ja: "美しい" },
      { es: "guapo / guapa", en: "handsome / good-looking", ja: "ハンサムな、美人の" },
      { es: "feo / fea", en: "ugly", ja: "醜い、不細工な" },
      { es: "lindo / linda", en: "cute / lovely", ja: "かわいい、すてきな" },
      { es: "precioso / preciosa", en: "gorgeous / precious", ja: "とても美しい、貴重な" },
      { es: "maravilloso / maravillosa", en: "wonderful / marvelous", ja: "すばらしい" },
      { es: "estupendo / estupenda", en: "great / terrific", ja: "すごい、すてきな" },
      { es: "fantástico / fantástica", en: "fantastic", ja: "最高の、ファンタスティックな" },
      { es: "excelente", en: "excellent", ja: "優れた、最高の" },
      { es: "horrible", en: "horrible", ja: "ひどい、恐ろしい" },
      { es: "terrible", en: "terrible", ja: "ひどい" },
      { es: "fatal", en: "awful / terrible", ja: "最悪の、ひどく" },
      { es: "raro / rara", en: "strange / rare", ja: "変な、珍しい" },
      { es: "extraño / extraña", en: "strange / odd", ja: "奇妙な、不思議な" },
      { es: "normal", en: "normal", ja: "普通の" },
      { es: "común", en: "common", ja: "よくある、共通の" },
      { es: "especial", en: "special", ja: "特別な" },
      { es: "único / única", en: "unique / only", ja: "唯一の、独特な" },
      { es: "famoso / famosa", en: "famous", ja: "有名な" },
      { es: "popular", en: "popular", ja: "人気のある" },
      { es: "verdadero / verdadera", en: "true / real", ja: "本当の" },
      { es: "falso / falsa", en: "false / fake", ja: "偽の、間違った" },
      { es: "correcto / correcta", en: "correct", ja: "正しい" },
      { es: "incorrecto / incorrecta", en: "incorrect", ja: "間違った" },
      { es: "justo / justa", en: "fair / just", ja: "公平な、ちょうどの" },
      { es: "injusto / injusta", en: "unfair", ja: "不公平な" },
      { es: "posible", en: "possible", ja: "可能な" },
      { es: "imposible", en: "impossible", ja: "不可能な" },
      { es: "necesario / necesaria", en: "necessary", ja: "必要な" },
      { es: "útil", en: "useful", ja: "役に立つ" },
      { es: "inútil", en: "useless", ja: "役に立たない" },
      { es: "cómodo / cómoda", en: "comfortable", ja: "快適な、楽な" },
      { es: "incómodo / incómoda", en: "uncomfortable", ja: "不快な、居心地の悪い" },
      { es: "agradable", en: "pleasant", ja: "心地よい、感じのいい" },
      { es: "desagradable", en: "unpleasant", ja: "不快な" },
      { es: "divertido / divertida", en: "fun / amusing", ja: "楽しい、面白い" },
      { es: "emocionante", en: "exciting", ja: "わくわくする" },
      { es: "impresionante", en: "impressive / amazing", ja: "印象的な、すごい" },
      { es: "curioso / curiosa", en: "curious / odd", ja: "好奇心旺盛な、興味深い" },
    ],
  },
  {
    cat: "形容詞③ 味・食べ物", icon: "😋",
    items: [
      { es: "delicioso / deliciosa", en: "delicious", ja: "とてもおいしい" },
      { es: "sabroso / sabrosa", en: "tasty", ja: "味のよい、おいしい" },
      { es: "dulce", en: "sweet", ja: "甘い" },
      { es: "salado / salada", en: "salty", ja: "塩辛い、しょっぱい" },
      { es: "amargo / amarga", en: "bitter", ja: "苦い" },
      { es: "ácido / ácida", en: "sour / acidic", ja: "酸っぱい" },
      { es: "picante", en: "spicy", ja: "辛い" },
      { es: "soso / sosa", en: "bland", ja: "味の薄い、物足りない" },
      { es: "congelado / congelada", en: "frozen", ja: "冷凍の" },
      { es: "crudo / cruda", en: "raw", ja: "生の" },
      { es: "cocido / cocida", en: "cooked / boiled", ja: "火を通した、ゆでた" },
      { es: "frito / frita", en: "fried", ja: "揚げた、炒めた" },
      { es: "maduro / madura", en: "ripe / mature", ja: "熟した" },
      { es: "podrido / podrida", en: "rotten", ja: "腐った" },
      { es: "natural", en: "natural", ja: "自然な、天然の" },
      { es: "vegetariano / vegetariana", en: "vegetarian", ja: "ベジタリアンの" },
      { es: "vegano / vegana", en: "vegan", ja: "ビーガンの" },
      { es: "casero / casera", en: "homemade", ja: "自家製の、手作りの" },
    ],
  },
  {
    cat: "形容詞④ よく使う状態", icon: "🙂",
    items: [
      { es: "propio / propia", en: "own", ja: "自分自身の" },
      { es: "junto / junta", en: "together", ja: "一緒の" },
      { es: "listo / lista", en: "ready / clever", ja: "準備できた、賢い" },
      { es: "preparado / preparada", en: "prepared", ja: "用意ができた" },
      { es: "despierto / despierta", en: "awake", ja: "目が覚めた" },
      { es: "dormido / dormida", en: "asleep", ja: "眠った" },
      { es: "sentado / sentada", en: "seated / sitting", ja: "座った" },
      { es: "de pie", en: "standing", ja: "立った" },
      { es: "perdido / perdida", en: "lost", ja: "迷った、なくした" },
      { es: "casado / casada", en: "married", ja: "結婚した" },
      { es: "soltero / soltera", en: "single (unmarried)", ja: "独身の" },
      { es: "vivo / viva", en: "alive", ja: "生きている" },
      { es: "muerto / muerta", en: "dead", ja: "死んだ" },
      { es: "herido / herida", en: "injured / hurt", ja: "けがをした" },
      { es: "soleado / soleada", en: "sunny", ja: "晴れた" },
      { es: "nublado / nublada", en: "cloudy", ja: "曇った" },
      { es: "lluvioso / lluviosa", en: "rainy", ja: "雨がちの" },
    ],
  },
  {
    cat: "副詞・頻度・程度", icon: "⚡",
    items: [
      { es: "muy", en: "very", ja: "とても" },
      { es: "más", en: "more", ja: "もっと、より多く" },
      { es: "menos", en: "less", ja: "より少なく" },
      { es: "tan", en: "so / such", ja: "そんなに、とても" },
      { es: "tanto", en: "so much", ja: "そんなにたくさん" },
      { es: "casi", en: "almost", ja: "ほとんど、もう少しで" },
      { es: "solamente / solo", en: "only", ja: "〜だけ、たった" },
      { es: "también", en: "also / too", ja: "〜もまた" },
      { es: "tampoco", en: "neither / not either", ja: "〜もまた…ない" },
      { es: "bien", en: "well", ja: "よく、上手に" },
      { es: "mal", en: "badly", ja: "悪く、下手に" },
      { es: "así", en: "like this / so", ja: "このように、そんなふうに" },
      { es: "ahora", en: "now", ja: "今" },
      { es: "enseguida", en: "right away", ja: "すぐに" },
      { es: "recientemente", en: "recently", ja: "最近" },
      { es: "últimamente", en: "lately", ja: "このごろ、最近" },
      { es: "actualmente", en: "currently", ja: "現在は" },
      { es: "normalmente", en: "normally / usually", ja: "普段は、通常は" },
      { es: "generalmente", en: "generally", ja: "一般的に、たいてい" },
      { es: "a menudo", en: "often", ja: "よく、しばしば" },
      { es: "a veces", en: "sometimes", ja: "ときどき" },
      { es: "de vez en cuando", en: "from time to time", ja: "たまに" },
      { es: "casi nunca", en: "hardly ever", ja: "めったに〜ない" },
      { es: "casi siempre", en: "almost always", ja: "ほとんどいつも" },
      { es: "todos los días", en: "every day", ja: "毎日" },
      { es: "dos veces", en: "twice", ja: "2回" },
      { es: "de nuevo", en: "again", ja: "再び、もう一度" },
      { es: "tarde", en: "late", ja: "遅く" },
      { es: "juntos / juntas", en: "together", ja: "一緒に" },
      { es: "incluso", en: "even", ja: "〜でさえ" },
      { es: "sobre todo", en: "above all / especially", ja: "特に、とりわけ" },
      { es: "especialmente", en: "especially", ja: "特に" },
      { es: "realmente", en: "really", ja: "本当に" },
      { es: "probablemente", en: "probably", ja: "たぶん、おそらく" },
      { es: "tal vez", en: "maybe / perhaps", ja: "もしかしたら" },
      { es: "seguramente", en: "surely", ja: "きっと" },
      { es: "afortunadamente", en: "fortunately", ja: "幸いにも" },
      { es: "por desgracia", en: "unfortunately", ja: "残念ながら" },
      { es: "finalmente", en: "finally", ja: "ついに、最後に" },
      { es: "al principio", en: "at first / in the beginning", ja: "初めは" },
      { es: "por fin", en: "at last", ja: "やっと、ようやく" },
      { es: "poco a poco", en: "little by little", ja: "少しずつ" },
      { es: "apenas", en: "barely / hardly", ja: "ほとんど〜ない、かろうじて" },
      { es: "allá", en: "over there", ja: "あちらに" },
      { es: "en todas partes", en: "everywhere", ja: "どこでも、至る所に" },
      { es: "en ninguna parte", en: "nowhere", ja: "どこにも〜ない" },
      { es: "mientras tanto", en: "meanwhile", ja: "その間に" },
      { es: "en general", en: "in general", ja: "一般的に、概して" },
      { es: "sin duda", en: "without a doubt", ja: "間違いなく" },
      { es: "a tiempo", en: "on time", ja: "時間どおりに" },
      { es: "de verdad", en: "really / truly", ja: "本当に" },
      { es: "al revés", en: "backwards / upside down", ja: "逆に、あべこべに" },
      { es: "a propósito", en: "on purpose / by the way", ja: "わざと、ところで" },
      { es: "de memoria", en: "by heart", ja: "暗記で、そらで" },
    ],
  },
  {
    cat: "接続詞・前置詞", icon: "🔗",
    items: [
      { es: "y", en: "and", ja: "〜と、そして" },
      { es: "o", en: "or", ja: "または" },
      { es: "ni", en: "neither / nor", ja: "〜も…ない" },
      { es: "que", en: "that / which", ja: "〜ということ、〜する…" },
      { es: "si", en: "if", ja: "もし〜なら" },
      { es: "cuando", en: "when", ja: "〜するとき" },
      { es: "donde", en: "where", ja: "〜する場所" },
      { es: "como", en: "as / like / since", ja: "〜のように、〜なので" },
      { es: "sino", en: "but (rather)", ja: "〜ではなく…" },
      { es: "así que", en: "so / therefore", ja: "だから" },
      { es: "sin embargo", en: "however", ja: "しかしながら" },
      { es: "en cambio", en: "on the other hand", ja: "その一方で" },
      { es: "por ejemplo", en: "for example", ja: "例えば" },
      { es: "es decir", en: "that is to say", ja: "つまり" },
      { es: "o sea", en: "I mean / in other words", ja: "つまり、要するに" },
      { es: "de", en: "of / from", ja: "〜の、〜から" },
      { es: "a", en: "to / at", ja: "〜へ、〜に" },
      { es: "en", en: "in / on / at", ja: "〜の中に、〜で" },
      { es: "con", en: "with", ja: "〜と一緒に" },
      { es: "sin", en: "without", ja: "〜なしで" },
      { es: "para", en: "for / in order to", ja: "〜のために" },
      { es: "por", en: "for / by / because of", ja: "〜によって、〜のせいで" },
      { es: "sobre", en: "on / about", ja: "〜の上に、〜について" },
      { es: "bajo", en: "under", ja: "〜の下に" },
      { es: "hacia", en: "toward", ja: "〜の方へ" },
      { es: "desde", en: "from / since", ja: "〜から" },
      { es: "hasta", en: "until / up to", ja: "〜まで" },
      { es: "contra", en: "against", ja: "〜に対して、〜に反対して" },
      { es: "según", en: "according to", ja: "〜によれば" },
      { es: "durante", en: "during", ja: "〜の間" },
      { es: "antes de", en: "before", ja: "〜の前に" },
      { es: "después de", en: "after", ja: "〜の後に" },
      { es: "a pesar de", en: "despite / in spite of", ja: "〜にもかかわらず" },
      { es: "en vez de", en: "instead of", ja: "〜の代わりに" },
      { es: "gracias a", en: "thanks to", ja: "〜のおかげで" },
    ],
  },
  {
    cat: "抽象・コミュニケーション", icon: "💡",
    items: [
      { es: "la manera", en: "way / manner", ja: "方法、やり方" },
      { es: "el modo", en: "way / mode", ja: "方法、モード" },
      { es: "el tipo", en: "type / kind / guy", ja: "種類、タイプ" },
      { es: "el consejo", en: "advice", ja: "アドバイス、助言" },
      { es: "la promesa", en: "promise", ja: "約束" },
      { es: "el secreto", en: "secret", ja: "秘密" },
      { es: "la broma", en: "joke / prank", ja: "冗談、いたずら" },
      { es: "el chiste", en: "joke", ja: "ジョーク、小話" },
      { es: "el ruido", en: "noise", ja: "騒音、物音" },
      { es: "la queja", en: "complaint", ja: "苦情、不満" },
      { es: "la discusión", en: "argument / discussion", ja: "口論、議論" },
      { es: "el acuerdo", en: "agreement", ja: "合意、協定" },
      { es: "la invitación", en: "invitation", ja: "招待" },
      { es: "el tema", en: "topic / subject", ja: "テーマ、話題" },
      { es: "la charla", en: "chat / talk", ja: "おしゃべり、トーク" },
      { es: "la despedida", en: "farewell", ja: "別れ、送別" },
      { es: "la bienvenida", en: "welcome", ja: "歓迎" },
      { es: "el saludo", en: "greeting", ja: "あいさつ" },
      { es: "el permiso", en: "permission", ja: "許可" },
      { es: "el apoyo", en: "support", ja: "支え、サポート" },
      { es: "la oportunidad", en: "opportunity / chance", ja: "機会、チャンス" },
      { es: "la posibilidad", en: "possibility", ja: "可能性" },
      { es: "la diferencia", en: "difference", ja: "違い" },
      { es: "la ventaja", en: "advantage", ja: "利点、メリット" },
      { es: "la desventaja", en: "disadvantage", ja: "欠点、デメリット" },
      { es: "el detalle", en: "detail", ja: "詳細、細部" },
      { es: "el caso", en: "case", ja: "場合、ケース" },
      { es: "la situación", en: "situation", ja: "状況" },
      { es: "la libertad", en: "freedom", ja: "自由" },
      { es: "la paz", en: "peace", ja: "平和" },
      { es: "la guerra", en: "war", ja: "戦争" },
      { es: "la ley", en: "law", ja: "法律" },
      { es: "el gobierno", en: "government", ja: "政府" },
      { es: "el derecho", en: "right (legal)", ja: "権利" },
      { es: "la seguridad", en: "safety / security", ja: "安全、セキュリティ" },
      { es: "la sociedad", en: "society", ja: "社会" },
      { es: "la comunidad", en: "community", ja: "コミュニティ、共同体" },
      { es: "la relación", en: "relationship", ja: "関係" },
      { es: "la actitud", en: "attitude", ja: "態度" },
      { es: "el comportamiento", en: "behavior", ja: "振る舞い、行動" },
      { es: "el hecho", en: "fact", ja: "事実" },
      { es: "la actividad", en: "activity", ja: "活動、アクティビティ" },
      { es: "la acción", en: "action", ja: "行動、アクション" },
      { es: "el movimiento", en: "movement", ja: "動き、運動" },
      { es: "el estado", en: "state / condition", ja: "状態、州" },
      { es: "la condición", en: "condition", ja: "条件、状態" },
      { es: "la causa", en: "cause", ja: "原因" },
      { es: "el efecto", en: "effect", ja: "効果、影響" },
      { es: "la intención", en: "intention", ja: "意図、つもり" },
      { es: "el sistema", en: "system", ja: "システム、制度" },
      { es: "el proceso", en: "process", ja: "過程、プロセス" },
      { es: "el método", en: "method", ja: "方法、メソッド" },
      { es: "el modelo", en: "model", ja: "モデル、模型" },
      { es: "la imagen", en: "image", ja: "画像、イメージ" },
      { es: "la lista", en: "list", ja: "リスト、一覧" },
      { es: "la mente", en: "mind", ja: "心、頭脳" },
      { es: "el alma", en: "soul", ja: "魂" },
      { es: "la belleza", en: "beauty", ja: "美しさ" },
      { es: "la fuerza", en: "strength / force", ja: "力" },
      { es: "la energía", en: "energy", ja: "エネルギー、元気" },
      { es: "la calma", en: "calm", ja: "落ち着き、静けさ" },
      { es: "la culpa", en: "fault / blame", ja: "罪、〜のせい" },
      { es: "el aviso", en: "notice / warning", ja: "お知らせ、警告" },
      { es: "el cartel", en: "poster / sign", ja: "ポスター、看板" },
      { es: "el anuncio", en: "advertisement / announcement", ja: "広告、告知" },
      { es: "la publicidad", en: "advertising", ja: "宣伝、広告" },
      { es: "la etiqueta", en: "label / tag", ja: "ラベル、値札" },
      { es: "la cola", en: "line (queue) / tail", ja: "行列、しっぽ" },
      { es: "el rincón", en: "corner (inside)", ja: "隅、コーナー" },
      { es: "el asunto", en: "matter / affair", ja: "用件、問題" },
    ],
  },
  {
    cat: "生活いろいろ", icon: "🧺",
    items: [
      { es: "el juguete", en: "toy", ja: "おもちゃ" },
      { es: "el globo", en: "balloon", ja: "風船" },
      { es: "el peluche", en: "stuffed animal", ja: "ぬいぐるみ" },
      { es: "el pañal", en: "diaper", ja: "おむつ" },
      { es: "el carrito de bebé", en: "stroller", ja: "ベビーカー" },
      { es: "la cuna", en: "crib / cradle", ja: "ベビーベッド、ゆりかご" },
      { es: "el sello", en: "stamp", ja: "切手、はんこ" },
      { es: "el sobre", en: "envelope", ja: "封筒" },
      { es: "la vajilla", en: "tableware / dishes", ja: "食器類" },
      { es: "los cubiertos", en: "cutlery / silverware", ja: "カトラリー" },
      { es: "el cucharón", en: "ladle", ja: "お玉" },
      { es: "la pajita", en: "straw", ja: "ストロー" },
      { es: "la ensalada", en: "salad", ja: "サラダ" },
      { es: "la hamburguesa", en: "hamburger", ja: "ハンバーガー" },
      { es: "la pizza", en: "pizza", ja: "ピザ" },
      { es: "el sushi", en: "sushi", ja: "寿司" },
      { es: "la tortilla", en: "Spanish omelet / tortilla", ja: "スペインオムレツ、トルティーヤ" },
      { es: "la paella", en: "paella", ja: "パエリア" },
      { es: "el gazpacho", en: "gazpacho (cold soup)", ja: "ガスパチョ、冷製スープ" },
      { es: "la empanada", en: "empanada / stuffed pastry", ja: "エンパナーダ" },
      { es: "los deberes", en: "homework", ja: "宿題" },
      { es: "el recreo", en: "recess / break", ja: "休み時間" },
      { es: "la asignatura", en: "school subject", ja: "科目、教科" },
      { es: "la geografía", en: "geography", ja: "地理" },
      { es: "la biología", en: "biology", ja: "生物学" },
      { es: "el peatón", en: "pedestrian", ja: "歩行者" },
      { es: "la ilusión", en: "excitement / hope", ja: "楽しみ、期待、夢" },
      { es: "la pereza", en: "laziness", ja: "だるさ、おっくうさ" },
      { es: "el mando a distancia", en: "remote control", ja: "リモコン" },
      { es: "el selfi", en: "selfie", ja: "自撮り、セルフィー" },
      { es: "el uniforme", en: "uniform", ja: "制服、ユニフォーム" },
      { es: "el disfraz", en: "costume", ja: "仮装、コスチューム" },
      { es: "la sombrilla", en: "parasol / beach umbrella", ja: "パラソル、日傘" },
      { es: "las chanclas", en: "flip-flops", ja: "ビーチサンダル" },
      { es: "la huelga", en: "strike (labor)", ja: "ストライキ" },
      { es: "el formulario", en: "form (to fill out)", ja: "記入用紙、フォーム" },
      { es: "la solicitud", en: "application / request", ja: "申し込み、申請" },
      { es: "la videollamada", en: "video call", ja: "ビデオ通話" },
      { es: "la colada", en: "laundry (washing)", ja: "洗濯、洗濯物" },
      { es: "la limpieza", en: "cleaning", ja: "掃除、清潔さ" },
      { es: "el desorden", en: "mess / disorder", ja: "散らかり、乱雑" },
      { es: "la lavandería", en: "laundromat", ja: "コインランドリー、クリーニング店" },
    ],
  },
  {
    cat: "素材・材料", icon: "🪵",
    items: [
      { es: "el material", en: "material", ja: "材料、素材" },
      { es: "el metal", en: "metal", ja: "金属" },
      { es: "el oro", en: "gold", ja: "金" },
      { es: "la plata", en: "silver", ja: "銀" },
      { es: "el hierro", en: "iron (metal)", ja: "鉄" },
      { es: "el plástico", en: "plastic", ja: "プラスチック" },
      { es: "el vidrio / el cristal", en: "glass (material)", ja: "ガラス" },
      { es: "el papel", en: "paper", ja: "紙" },
      { es: "la madera", en: "wood", ja: "木材" },
      { es: "el cartón", en: "cardboard", ja: "段ボール、厚紙" },
      { es: "la cuerda", en: "rope / string", ja: "ロープ、ひも" },
      { es: "la cadena", en: "chain", ja: "鎖、チェーン" },
      { es: "el martillo", en: "hammer", ja: "ハンマー、金づち" },
      { es: "el ladrillo", en: "brick", ja: "レンガ" },
      { es: "el polvo", en: "dust / powder", ja: "ほこり、粉" },
      { es: "la mancha", en: "stain / spot", ja: "しみ、汚れ" },
      { es: "el agujero", en: "hole", ja: "穴" },
      { es: "el humo", en: "smoke", ja: "煙" },
    ],
  },
];
