// ¡Escucha! 単語データ 4/5 — 色・形・数・方角・国・動詞

const WORD_PART_4 = [
  {
    cat: "色", icon: "🎨",
    items: [
      { es: "el color", en: "color", ja: "色" },
      { es: "rojo / roja", en: "red", ja: "赤い" },
      { es: "azul", en: "blue", ja: "青い" },
      { es: "verde", en: "green", ja: "緑の" },
      { es: "amarillo / amarilla", en: "yellow", ja: "黄色い" },
      { es: "naranja (color)", en: "orange (color)", ja: "オレンジ色の" },
      { es: "blanco / blanca", en: "white", ja: "白い" },
      { es: "negro / negra", en: "black", ja: "黒い" },
      { es: "gris", en: "gray", ja: "灰色の、グレーの" },
      { es: "marrón", en: "brown", ja: "茶色の" },
      { es: "rosa", en: "pink", ja: "ピンクの" },
      { es: "morado / morada", en: "purple", ja: "紫の" },
      { es: "violeta", en: "violet", ja: "すみれ色の" },
      { es: "dorado / dorada", en: "golden", ja: "金色の" },
      { es: "plateado / plateada", en: "silver (color)", ja: "銀色の" },
      { es: "celeste", en: "sky blue", ja: "空色の、水色の" },
      { es: "turquesa", en: "turquoise", ja: "ターコイズの" },
      { es: "beige", en: "beige", ja: "ベージュの" },
    ],
  },
  {
    cat: "形・量・単位", icon: "📏",
    items: [
      { es: "la forma", en: "shape / form", ja: "形" },
      { es: "el círculo", en: "circle", ja: "円、丸" },
      { es: "el cuadrado", en: "square", ja: "四角、正方形" },
      { es: "el triángulo", en: "triangle", ja: "三角形" },
      { es: "el rectángulo", en: "rectangle", ja: "長方形" },
      { es: "la curva", en: "curve", ja: "カーブ、曲線" },
      { es: "el borde", en: "edge", ja: "端、縁" },
      { es: "la superficie", en: "surface", ja: "表面" },
      { es: "el tamaño", en: "size", ja: "大きさ、サイズ" },
      { es: "el centímetro", en: "centimeter", ja: "センチメートル" },
      { es: "el gramo", en: "gram", ja: "グラム" },
      { es: "el kilo", en: "kilogram", ja: "キログラム、キロ" },
      { es: "el litro", en: "liter", ja: "リットル" },
      { es: "la pieza", en: "piece / part", ja: "部品、一片" },
      { es: "el trozo / el pedazo", en: "piece / chunk", ja: "かけら、切れ端" },
      { es: "la parte", en: "part", ja: "部分" },
      { es: "el grupo", en: "group", ja: "グループ、集団" },
      { es: "el montón", en: "pile / a lot", ja: "山積み、たくさん" },
      { es: "la fila", en: "row / line (queue)", ja: "列、行列" },
      { es: "el orden", en: "order (sequence)", ja: "順序、順番" },
      { es: "el par", en: "pair", ja: "一対、ペア" },
      { es: "la docena", en: "dozen", ja: "ダース、12個" },
      { es: "el resto", en: "rest / remainder", ja: "残り" },
      { es: "redondo / redonda", en: "round", ja: "丸い" },
      { es: "plano / plana", en: "flat", ja: "平らな" },
    ],
  },
  {
    cat: "数・数量", icon: "🔢",
    items: [
      { es: "cero", en: "zero", ja: "0、ゼロ" },
      { es: "once", en: "eleven", ja: "11" },
      { es: "doce", en: "twelve", ja: "12" },
      { es: "trece", en: "thirteen", ja: "13" },
      { es: "catorce", en: "fourteen", ja: "14" },
      { es: "dieciséis", en: "sixteen", ja: "16" },
      { es: "diecisiete", en: "seventeen", ja: "17" },
      { es: "dieciocho", en: "eighteen", ja: "18" },
      { es: "diecinueve", en: "nineteen", ja: "19" },
      { es: "veintiuno", en: "twenty-one", ja: "21" },
      { es: "treinta", en: "thirty", ja: "30" },
      { es: "cuarenta", en: "forty", ja: "40" },
      { es: "cincuenta", en: "fifty", ja: "50" },
      { es: "sesenta", en: "sixty", ja: "60" },
      { es: "setenta", en: "seventy", ja: "70" },
      { es: "ochenta", en: "eighty", ja: "80" },
      { es: "noventa", en: "ninety", ja: "90" },
      { es: "doscientos", en: "two hundred", ja: "200" },
      { es: "quinientos", en: "five hundred", ja: "500" },
      { es: "un millón", en: "one million", ja: "100万" },
      { es: "el doble", en: "double", ja: "2倍" },
      { es: "el triple", en: "triple", ja: "3倍" },
      { es: "medio / media", en: "half (adj)", ja: "半分の" },
      { es: "un cuarto", en: "a quarter", ja: "4分の1、15分" },
      { es: "el porcentaje", en: "percentage", ja: "パーセント、割合" },
      { es: "el total", en: "total", ja: "合計" },
      { es: "la suma", en: "sum / addition", ja: "合計、足し算" },
      { es: "el promedio", en: "average", ja: "平均" },
      { es: "mucho / mucha", en: "much / a lot", ja: "たくさんの" },
      { es: "poco / poca", en: "little / few", ja: "少しの" },
      { es: "bastante", en: "quite / enough", ja: "かなりの、十分な" },
      { es: "demasiado / demasiada", en: "too much", ja: "多すぎる" },
      { es: "suficiente", en: "enough / sufficient", ja: "十分な" },
      { es: "varios / varias", en: "several", ja: "いくつかの" },
      { es: "algunos / algunas", en: "some", ja: "いくつかの、何人かの" },
      { es: "cada", en: "each / every", ja: "それぞれの、毎〜" },
      { es: "ambos / ambas", en: "both", ja: "両方の" },
      { es: "ninguno / ninguna", en: "none / no one", ja: "ひとつも〜ない" },
      { es: "otro / otra", en: "other / another", ja: "他の、もうひとつの" },
      { es: "mismo / misma", en: "same", ja: "同じ" },
      { es: "alguien", en: "someone", ja: "誰か" },
      { es: "nadie", en: "no one / nobody", ja: "誰も〜ない" },
      { es: "cualquiera", en: "any / anyone", ja: "どれでも、誰でも" },
    ],
  },
  {
    cat: "方角・位置", icon: "🧭",
    items: [
      { es: "el norte", en: "north", ja: "北" },
      { es: "el sur", en: "south", ja: "南" },
      { es: "el este", en: "east", ja: "東" },
      { es: "el oeste", en: "west", ja: "西" },
      { es: "arriba", en: "up / upstairs", ja: "上に、上の階に" },
      { es: "abajo", en: "down / downstairs", ja: "下に、下の階に" },
      { es: "delante", en: "in front", ja: "前に" },
      { es: "detrás", en: "behind", ja: "後ろに" },
      { es: "encima", en: "on top / above", ja: "上に、〜の上に" },
      { es: "debajo", en: "underneath / below", ja: "下に、〜の下に" },
      { es: "dentro", en: "inside", ja: "中に" },
      { es: "fuera", en: "outside", ja: "外に" },
      { es: "cerca", en: "near / close", ja: "近くに" },
      { es: "lejos", en: "far", ja: "遠くに" },
      { es: "enfrente", en: "opposite / across", ja: "向かいに、正面に" },
      { es: "al lado de", en: "next to", ja: "〜の隣に" },
      { es: "entre", en: "between / among", ja: "〜の間に" },
      { es: "alrededor", en: "around", ja: "周りに" },
      { es: "el lado", en: "side", ja: "側、横" },
      { es: "el fondo", en: "back / bottom / background", ja: "奥、底、背景" },
    ],
  },
  {
    cat: "国・地域・国籍", icon: "🌎",
    items: [
      { es: "España", en: "Spain", ja: "スペイン" },
      { es: "México", en: "Mexico", ja: "メキシコ" },
      { es: "Argentina", en: "Argentina", ja: "アルゼンチン" },
      { es: "Colombia", en: "Colombia", ja: "コロンビア" },
      { es: "Perú", en: "Peru", ja: "ペルー" },
      { es: "Chile", en: "Chile", ja: "チリ" },
      { es: "los Estados Unidos", en: "the United States", ja: "アメリカ合衆国" },
      { es: "Inglaterra", en: "England", ja: "イギリス、イングランド" },
      { es: "Francia", en: "France", ja: "フランス" },
      { es: "Alemania", en: "Germany", ja: "ドイツ" },
      { es: "Italia", en: "Italy", ja: "イタリア" },
      { es: "Portugal", en: "Portugal", ja: "ポルトガル" },
      { es: "Brasil", en: "Brazil", ja: "ブラジル" },
      { es: "China", en: "China", ja: "中国" },
      { es: "Corea", en: "Korea", ja: "韓国" },
      { es: "la India", en: "India", ja: "インド" },
      { es: "Rusia", en: "Russia", ja: "ロシア" },
      { es: "Europa", en: "Europe", ja: "ヨーロッパ" },
      { es: "Asia", en: "Asia", ja: "アジア" },
      { es: "África", en: "Africa", ja: "アフリカ" },
      { es: "América Latina", en: "Latin America", ja: "ラテンアメリカ、中南米" },
      { es: "español / española", en: "Spanish (nationality)", ja: "スペイン人の" },
      { es: "mexicano / mexicana", en: "Mexican", ja: "メキシコ人の" },
      { es: "estadounidense", en: "American (from the U.S.)", ja: "アメリカ人の" },
      { es: "latino / latina", en: "Latino / Latina", ja: "ラテン系の" },
      { es: "la bandera", en: "flag", ja: "旗、国旗" },
      { es: "el francés", en: "French (language)", ja: "フランス語" },
    ],
  },
  {
    cat: "動詞① 基本・日常", icon: "🔤",
    items: [
      { es: "ser", en: "to be (identity)", ja: "〜である" },
      { es: "estar", en: "to be (state / place)", ja: "〜の状態である、〜にいる" },
      { es: "tener", en: "to have", ja: "持っている" },
      { es: "haber (hay)", en: "there is / there are", ja: "〜がある、いる" },
      { es: "poder", en: "to be able to / can", ja: "できる" },
      { es: "querer", en: "to want / to love", ja: "欲しい、愛する" },
      { es: "necesitar", en: "to need", ja: "必要とする" },
      { es: "deber", en: "must / to owe", ja: "〜すべき、借りている" },
      { es: "saber", en: "to know (facts)", ja: "知っている、できる" },
      { es: "conocer", en: "to know (people / places)", ja: "知っている、面識がある" },
      { es: "decir", en: "to say / to tell", ja: "言う" },
      { es: "pedir", en: "to ask for / to order", ja: "頼む、注文する" },
      { es: "dar", en: "to give", ja: "与える、あげる" },
      { es: "tomar", en: "to take / to drink", ja: "取る、飲む" },
      { es: "poner", en: "to put", ja: "置く" },
      { es: "quitar", en: "to remove / to take away", ja: "取り除く" },
      { es: "abrir", en: "to open", ja: "開ける" },
      { es: "cerrar", en: "to close", ja: "閉める" },
      { es: "empezar", en: "to begin / to start", ja: "始める" },
      { es: "terminar", en: "to finish / to end", ja: "終える" },
      { es: "buscar", en: "to look for / to search", ja: "探す" },
      { es: "encontrar", en: "to find", ja: "見つける" },
      { es: "llevar", en: "to carry / to wear / to take", ja: "持って行く、身につける" },
      { es: "traer", en: "to bring", ja: "持ってくる" },
      { es: "sacar", en: "to take out", ja: "取り出す" },
      { es: "meter", en: "to put in", ja: "入れる" },
      { es: "usar", en: "to use", ja: "使う" },
      { es: "comprar", en: "to buy", ja: "買う" },
      { es: "vender", en: "to sell", ja: "売る" },
      { es: "pagar", en: "to pay", ja: "払う" },
      { es: "costar", en: "to cost", ja: "(値段が)かかる" },
      { es: "gastar", en: "to spend", ja: "使う(お金を)" },
      { es: "ahorrar", en: "to save (money)", ja: "貯金する、節約する" },
      { es: "lavar", en: "to wash", ja: "洗う" },
      { es: "limpiar", en: "to clean", ja: "掃除する" },
      { es: "ordenar", en: "to tidy up / to order", ja: "片付ける、命じる" },
      { es: "barrer", en: "to sweep", ja: "掃く" },
      { es: "planchar", en: "to iron", ja: "アイロンをかける" },
      { es: "coser", en: "to sew", ja: "縫う" },
      { es: "cortar", en: "to cut", ja: "切る" },
      { es: "romper", en: "to break", ja: "壊す、破る" },
      { es: "arreglar", en: "to fix / to arrange", ja: "直す、整える" },
      { es: "reparar", en: "to repair", ja: "修理する" },
      { es: "construir", en: "to build", ja: "建てる" },
      { es: "pintar", en: "to paint", ja: "塗る、描く" },
      { es: "colgar", en: "to hang", ja: "掛ける、吊るす" },
      { es: "guardar", en: "to keep / to put away", ja: "しまう、保存する" },
      { es: "tirar", en: "to throw away / to pull", ja: "捨てる、引く" },
      { es: "recoger", en: "to pick up / to collect", ja: "拾う、片付ける" },
      { es: "llenar", en: "to fill", ja: "満たす、いっぱいにする" },
      { es: "vaciar", en: "to empty", ja: "空にする" },
      { es: "mezclar", en: "to mix", ja: "混ぜる" },
      { es: "hervir", en: "to boil", ja: "沸かす、ゆでる" },
      { es: "freír", en: "to fry", ja: "揚げる、炒める" },
      { es: "asar", en: "to roast / to grill", ja: "焼く、ローストする" },
      { es: "calentar", en: "to heat", ja: "温める" },
      { es: "enfriar", en: "to cool", ja: "冷やす" },
      { es: "probar", en: "to try / to taste", ja: "試す、味見する" },
      { es: "servir", en: "to serve", ja: "給仕する、役立つ" },
      { es: "preparar", en: "to prepare", ja: "準備する、作る" },
      { es: "desayunar", en: "to have breakfast", ja: "朝食をとる" },
      { es: "almorzar", en: "to have lunch", ja: "昼食をとる" },
      { es: "cenar", en: "to have dinner", ja: "夕食をとる" },
      { es: "morder", en: "to bite", ja: "かむ、かじる" },
      { es: "masticar", en: "to chew", ja: "そしゃくする、かむ" },
      { es: "tragar", en: "to swallow", ja: "飲み込む" },
      { es: "oler", en: "to smell", ja: "においがする、かぐ" },
      { es: "tocar", en: "to touch / to play (instrument)", ja: "触る、演奏する" },
      { es: "mirar", en: "to look at / to watch", ja: "見る、眺める" },
      { es: "oír", en: "to hear", ja: "聞こえる" },
    ],
  },
  {
    cat: "動詞② 移動・体の動き", icon: "🏃",
    items: [
      { es: "caminar", en: "to walk", ja: "歩く" },
      { es: "andar", en: "to walk / to go", ja: "歩く、進む" },
      { es: "correr", en: "to run", ja: "走る" },
      { es: "saltar", en: "to jump", ja: "跳ぶ、ジャンプする" },
      { es: "nadar", en: "to swim", ja: "泳ぐ" },
      { es: "volar", en: "to fly", ja: "飛ぶ" },
      { es: "conducir / manejar", en: "to drive", ja: "運転する" },
      { es: "viajar", en: "to travel", ja: "旅行する" },
      { es: "salir", en: "to go out / to leave", ja: "出る、出かける" },
      { es: "entrar", en: "to enter", ja: "入る" },
      { es: "llegar", en: "to arrive", ja: "着く、到着する" },
      { es: "volver", en: "to return / to come back", ja: "戻る、帰る" },
      { es: "regresar", en: "to return", ja: "帰る、戻る" },
      { es: "subir", en: "to go up / to get on", ja: "上がる、乗る" },
      { es: "bajar", en: "to go down / to get off", ja: "下りる、降りる" },
      { es: "cruzar", en: "to cross", ja: "渡る、横切る" },
      { es: "girar", en: "to turn", ja: "曲がる、回る" },
      { es: "doblar", en: "to turn / to fold", ja: "曲がる、折る" },
      { es: "parar", en: "to stop", ja: "止まる、止める" },
      { es: "seguir", en: "to continue / to follow", ja: "続ける、ついて行く" },
      { es: "esperar", en: "to wait / to hope", ja: "待つ、期待する" },
      { es: "quedar", en: "to meet up / to remain", ja: "待ち合わせる、残る" },
      { es: "mover", en: "to move (something)", ja: "動かす" },
      { es: "empujar", en: "to push", ja: "押す" },
      { es: "levantar", en: "to lift / to raise", ja: "持ち上げる" },
      { es: "cargar", en: "to carry / to charge", ja: "運ぶ、充電する" },
      { es: "montar", en: "to ride / to assemble", ja: "乗る、組み立てる" },
      { es: "caer / caerse", en: "to fall", ja: "落ちる、転ぶ" },
      { es: "escalar", en: "to climb", ja: "登る" },
      { es: "pasear", en: "to take a walk", ja: "散歩する" },
      { es: "descansar", en: "to rest", ja: "休む" },
      { es: "sentarse", en: "to sit down", ja: "座る" },
      { es: "levantarse", en: "to get up", ja: "起きる、立ち上がる" },
      { es: "acostarse", en: "to go to bed", ja: "寝る、横になる" },
      { es: "despertarse", en: "to wake up", ja: "目を覚ます" },
      { es: "ducharse", en: "to take a shower", ja: "シャワーを浴びる" },
      { es: "bañarse", en: "to take a bath / to bathe", ja: "入浴する" },
      { es: "vestirse", en: "to get dressed", ja: "服を着る" },
      { es: "ponerse", en: "to put on", ja: "身につける" },
      { es: "quitarse", en: "to take off", ja: "脱ぐ" },
      { es: "probarse", en: "to try on", ja: "試着する" },
      { es: "peinarse", en: "to comb one's hair", ja: "髪をとかす" },
      { es: "afeitarse", en: "to shave", ja: "ひげをそる" },
      { es: "maquillarse", en: "to put on makeup", ja: "化粧する" },
      { es: "lavarse", en: "to wash oneself", ja: "(体を)洗う" },
      { es: "cepillarse", en: "to brush", ja: "(歯・髪を)磨く、とかす" },
      { es: "relajarse", en: "to relax", ja: "リラックスする" },
      { es: "moverse", en: "to move (oneself)", ja: "動く" },
      { es: "darse prisa", en: "to hurry", ja: "急ぐ" },
      { es: "irse", en: "to leave / to go away", ja: "立ち去る、行ってしまう" },
      { es: "quedarse", en: "to stay", ja: "とどまる、残る" },
      { es: "mudarse", en: "to move (house)", ja: "引っ越す" },
      { es: "perderse", en: "to get lost", ja: "道に迷う" },
      { es: "sentirse", en: "to feel", ja: "感じる、気分が〜だ" },
      { es: "dormirse", en: "to fall asleep", ja: "眠りに落ちる" },
      { es: "estirar", en: "to stretch", ja: "伸ばす、ストレッチする" },
      { es: "abrazar", en: "to hug", ja: "抱きしめる" },
      { es: "besar", en: "to kiss", ja: "キスする" },
      { es: "saludar", en: "to greet", ja: "あいさつする" },
      { es: "despedirse", en: "to say goodbye", ja: "別れを告げる" },
      { es: "aparcar", en: "to park", ja: "駐車する" },
      { es: "chocar", en: "to crash / to bump", ja: "ぶつかる" },
      { es: "recorrer", en: "to travel around / to cover", ja: "巡る、走破する" },
      { es: "alcanzar", en: "to reach / to catch up", ja: "届く、追いつく" },
      { es: "escapar", en: "to escape", ja: "逃げる" },
      { es: "acompañar", en: "to accompany", ja: "付き添う、一緒に行く" },
      { es: "lanzar", en: "to throw", ja: "投げる" },
      { es: "coger", en: "to take / to catch", ja: "取る、つかむ(スペイン)" },
      { es: "agarrar", en: "to grab", ja: "つかむ" },
      { es: "soltar", en: "to let go / to release", ja: "放す、離す" },
    ],
  },
  {
    cat: "動詞③ 話す・考える", icon: "💭",
    items: [
      { es: "pensar", en: "to think", ja: "考える、思う" },
      { es: "creer", en: "to believe / to think", ja: "信じる、思う" },
      { es: "opinar", en: "to give an opinion", ja: "意見を言う" },
      { es: "entender", en: "to understand", ja: "理解する、わかる" },
      { es: "comprender", en: "to comprehend", ja: "理解する" },
      { es: "explicar", en: "to explain", ja: "説明する" },
      { es: "preguntar", en: "to ask (a question)", ja: "質問する、たずねる" },
      { es: "responder", en: "to answer / to respond", ja: "答える" },
      { es: "contestar", en: "to answer / to reply", ja: "返事する、答える" },
      { es: "contar", en: "to tell / to count", ja: "語る、数える" },
      { es: "charlar", en: "to chat", ja: "おしゃべりする" },
      { es: "gritar", en: "to shout / to scream", ja: "叫ぶ" },
      { es: "callar", en: "to be quiet", ja: "黙る" },
      { es: "repetir", en: "to repeat", ja: "繰り返す" },
      { es: "traducir", en: "to translate", ja: "翻訳する" },
      { es: "significar", en: "to mean", ja: "意味する" },
      { es: "escribir", en: "to write", ja: "書く" },
      { es: "leer", en: "to read", ja: "読む" },
      { es: "enviar", en: "to send", ja: "送る" },
      { es: "mandar", en: "to send / to order", ja: "送る、命じる" },
      { es: "recibir", en: "to receive", ja: "受け取る" },
      { es: "compartir", en: "to share", ja: "分け合う、シェアする" },
      { es: "publicar", en: "to publish / to post", ja: "公開する、投稿する" },
      { es: "comentar", en: "to comment", ja: "コメントする、話題にする" },
      { es: "discutir", en: "to argue / to discuss", ja: "口論する、議論する" },
      { es: "pelear", en: "to fight", ja: "けんかする" },
      { es: "quejarse", en: "to complain", ja: "文句を言う" },
      { es: "prometer", en: "to promise", ja: "約束する" },
      { es: "mentir", en: "to lie", ja: "嘘をつく" },
      { es: "engañar", en: "to deceive / to cheat", ja: "だます" },
      { es: "admitir", en: "to admit", ja: "認める" },
      { es: "aceptar", en: "to accept", ja: "受け入れる" },
      { es: "rechazar", en: "to reject / to refuse", ja: "断る、拒否する" },
      { es: "negar", en: "to deny", ja: "否定する" },
      { es: "agradecer", en: "to thank", ja: "感謝する" },
      { es: "felicitar", en: "to congratulate", ja: "祝う、おめでとうと言う" },
      { es: "invitar", en: "to invite / to treat", ja: "招待する、おごる" },
      { es: "ofrecer", en: "to offer", ja: "提供する、申し出る" },
      { es: "sugerir", en: "to suggest", ja: "提案する" },
      { es: "recomendar", en: "to recommend", ja: "すすめる" },
      { es: "aconsejar", en: "to advise", ja: "助言する" },
      { es: "avisar", en: "to notify / to let know", ja: "知らせる" },
      { es: "advertir", en: "to warn", ja: "警告する、注意する" },
      { es: "informar", en: "to inform", ja: "報告する、知らせる" },
      { es: "anunciar", en: "to announce", ja: "発表する、告知する" },
      { es: "describir", en: "to describe", ja: "描写する、説明する" },
      { es: "mostrar", en: "to show", ja: "見せる" },
      { es: "enseñar", en: "to teach / to show", ja: "教える、見せる" },
      { es: "aprender", en: "to learn", ja: "学ぶ、覚える" },
      { es: "memorizar", en: "to memorize", ja: "暗記する" },
      { es: "recordar", en: "to remember / to remind", ja: "思い出す、思い出させる" },
      { es: "olvidar", en: "to forget", ja: "忘れる" },
      { es: "acordarse", en: "to remember", ja: "覚えている、思い出す" },
      { es: "olvidarse", en: "to forget (about)", ja: "忘れてしまう" },
      { es: "imaginar", en: "to imagine", ja: "想像する" },
      { es: "soñar", en: "to dream", ja: "夢を見る" },
      { es: "decidir", en: "to decide", ja: "決める" },
      { es: "elegir / escoger", en: "to choose", ja: "選ぶ" },
      { es: "dudar", en: "to doubt / to hesitate", ja: "疑う、ためらう" },
      { es: "adivinar", en: "to guess", ja: "当てる、推測する" },
      { es: "suponer", en: "to suppose", ja: "推測する、〜だと思う" },
      { es: "presentar", en: "to introduce / to present", ja: "紹介する、発表する" },
      { es: "expresar", en: "to express", ja: "表現する" },
      { es: "mencionar", en: "to mention", ja: "言及する、触れる" },
      { es: "sonreír", en: "to smile", ja: "ほほえむ" },
      { es: "reírse", en: "to laugh", ja: "笑う" },
      { es: "llorar", en: "to cry", ja: "泣く" },
      { es: "firmar", en: "to sign", ja: "署名する" },
      { es: "apuntar", en: "to write down / to note", ja: "メモする、書き留める" },
    ],
  },
  {
    cat: "動詞④ 仕事・生活", icon: "🛠",
    items: [
      { es: "ayudar", en: "to help", ja: "手伝う、助ける" },
      { es: "cuidar", en: "to take care of", ja: "世話する、気をつける" },
      { es: "proteger", en: "to protect", ja: "守る" },
      { es: "salvar", en: "to save / to rescue", ja: "救う" },
      { es: "apoyar", en: "to support", ja: "支える、応援する" },
      { es: "atender", en: "to attend to / to serve", ja: "対応する、応対する" },
      { es: "visitar", en: "to visit", ja: "訪ねる" },
      { es: "ganar", en: "to win / to earn", ja: "勝つ、稼ぐ" },
      { es: "competir", en: "to compete", ja: "競争する" },
      { es: "jugar", en: "to play", ja: "遊ぶ、(スポーツを)する" },
      { es: "practicar", en: "to practice", ja: "練習する" },
      { es: "entrenar", en: "to train", ja: "トレーニングする" },
      { es: "mejorar", en: "to improve", ja: "良くなる、改善する" },
      { es: "empeorar", en: "to get worse", ja: "悪化する" },
      { es: "crecer", en: "to grow", ja: "成長する、育つ" },
      { es: "cambiar", en: "to change", ja: "変える、変わる" },
      { es: "convertirse", en: "to become", ja: "〜になる" },
      { es: "desarrollar", en: "to develop", ja: "開発する、発展させる" },
      { es: "crear", en: "to create", ja: "創る、生み出す" },
      { es: "inventar", en: "to invent", ja: "発明する" },
      { es: "diseñar", en: "to design", ja: "デザインする、設計する" },
      { es: "producir", en: "to produce", ja: "生産する" },
      { es: "fabricar", en: "to manufacture", ja: "製造する" },
      { es: "organizar", en: "to organize", ja: "企画する、整理する" },
      { es: "planear", en: "to plan", ja: "計画する" },
      { es: "revisar", en: "to check / to review", ja: "確認する、見直す" },
      { es: "corregir", en: "to correct", ja: "訂正する、直す" },
      { es: "resolver", en: "to solve", ja: "解決する" },
      { es: "conseguir", en: "to get / to achieve", ja: "手に入れる、達成する" },
      { es: "obtener", en: "to obtain", ja: "得る、取得する" },
      { es: "intentar", en: "to try / to attempt", ja: "試みる、〜しようとする" },
      { es: "tratar", en: "to try / to treat", ja: "扱う、〜しようとする" },
      { es: "fallar", en: "to fail", ja: "失敗する" },
      { es: "triunfar", en: "to succeed / to triumph", ja: "成功する" },
      { es: "celebrar", en: "to celebrate", ja: "祝う" },
      { es: "regalar", en: "to give (a gift)", ja: "贈る、プレゼントする" },
      { es: "envolver", en: "to wrap", ja: "包む" },
      { es: "alquilar", en: "to rent", ja: "借りる、貸す" },
      { es: "reservar", en: "to reserve / to book", ja: "予約する" },
      { es: "cancelar", en: "to cancel", ja: "キャンセルする" },
      { es: "confirmar", en: "to confirm", ja: "確認する、確定する" },
      { es: "devolver", en: "to return (something)", ja: "返す" },
      { es: "prestar", en: "to lend", ja: "貸す" },
      { es: "pedir prestado", en: "to borrow", ja: "借りる" },
      { es: "contratar", en: "to hire", ja: "雇う、契約する" },
      { es: "despedir", en: "to fire / to dismiss", ja: "解雇する" },
      { es: "renunciar", en: "to quit / to resign", ja: "辞める" },
      { es: "jubilarse", en: "to retire", ja: "退職する" },
      { es: "dirigir", en: "to direct / to manage", ja: "指揮する、経営する" },
      { es: "cobrar", en: "to charge / to get paid", ja: "請求する、受け取る" },
      { es: "invertir", en: "to invest", ja: "投資する" },
      { es: "imprimir", en: "to print", ja: "印刷する" },
      { es: "copiar", en: "to copy", ja: "コピーする" },
      { es: "pegar", en: "to paste / to stick / to hit", ja: "貼る、たたく" },
      { es: "borrar", en: "to erase / to delete", ja: "消す、削除する" },
      { es: "descargar", en: "to download", ja: "ダウンロードする" },
      { es: "instalar", en: "to install", ja: "インストールする" },
      { es: "encender", en: "to turn on / to light", ja: "つける、点火する" },
      { es: "apagar", en: "to turn off", ja: "消す" },
      { es: "enchufar", en: "to plug in", ja: "コンセントにつなぐ" },
      { es: "funcionar", en: "to work / to function", ja: "作動する、機能する" },
      { es: "estropearse", en: "to break down", ja: "故障する" },
      { es: "sonar", en: "to sound / to ring", ja: "鳴る" },
      { es: "participar", en: "to participate", ja: "参加する" },
      { es: "asistir", en: "to attend", ja: "出席する" },
      { es: "faltar", en: "to be missing / to be absent", ja: "足りない、欠席する" },
      { es: "aprobar", en: "to pass (an exam) / to approve", ja: "合格する、承認する" },
      { es: "suspender", en: "to fail (an exam)", ja: "落第する、不合格になる" },
      { es: "graduarse", en: "to graduate", ja: "卒業する" },
    ],
  },
  {
    cat: "動詞⑤ 気持ち・状態", icon: "💗",
    items: [
      { es: "gustar", en: "to like (to be pleasing)", ja: "好きである" },
      { es: "encantar", en: "to love / to delight", ja: "大好きである" },
      { es: "interesar", en: "to interest", ja: "興味を引く" },
      { es: "molestar", en: "to bother / to annoy", ja: "邪魔する、嫌がらせる" },
      { es: "aburrir", en: "to bore", ja: "退屈させる" },
      { es: "divertirse", en: "to have fun", ja: "楽しむ" },
      { es: "preocuparse", en: "to worry", ja: "心配する" },
      { es: "alegrarse", en: "to be glad", ja: "喜ぶ" },
      { es: "enfadarse / enojarse", en: "to get angry", ja: "怒る" },
      { es: "calmarse", en: "to calm down", ja: "落ち着く" },
      { es: "asustarse", en: "to get scared", ja: "怖がる、驚く" },
      { es: "sorprenderse", en: "to be surprised", ja: "驚く" },
      { es: "emocionarse", en: "to get excited / moved", ja: "感動する、興奮する" },
      { es: "enamorarse", en: "to fall in love", ja: "恋に落ちる" },
      { es: "casarse", en: "to get married", ja: "結婚する" },
      { es: "divorciarse", en: "to get divorced", ja: "離婚する" },
      { es: "nacer", en: "to be born", ja: "生まれる" },
      { es: "morir", en: "to die", ja: "死ぬ" },
      { es: "existir", en: "to exist", ja: "存在する" },
      { es: "pasar", en: "to happen / to pass", ja: "起こる、過ぎる" },
      { es: "ocurrir", en: "to occur / to happen", ja: "起こる" },
      { es: "suceder", en: "to happen", ja: "起こる、生じる" },
      { es: "parecer", en: "to seem", ja: "〜のように見える" },
      { es: "parecerse", en: "to look like / to resemble", ja: "似ている" },
      { es: "sobrar", en: "to be left over", ja: "余る" },
      { es: "importar", en: "to matter / to import", ja: "重要である、気にする" },
      { es: "valer", en: "to be worth", ja: "価値がある" },
      { es: "merecer", en: "to deserve", ja: "値する" },
      { es: "depender", en: "to depend", ja: "依存する、〜次第である" },
      { es: "pertenecer", en: "to belong", ja: "属する" },
      { es: "incluir", en: "to include", ja: "含む" },
      { es: "contener", en: "to contain", ja: "含む、入っている" },
      { es: "evitar", en: "to avoid", ja: "避ける" },
      { es: "permitir", en: "to allow / to permit", ja: "許可する" },
      { es: "prohibir", en: "to prohibit / to forbid", ja: "禁止する" },
      { es: "dejar", en: "to leave / to let / to quit", ja: "残す、やめる、〜させる" },
      { es: "continuar", en: "to continue", ja: "続ける" },
      { es: "acabar", en: "to finish / to end", ja: "終わる、終える" },
      { es: "disfrutar", en: "to enjoy", ja: "楽しむ" },
      { es: "sufrir", en: "to suffer", ja: "苦しむ" },
      { es: "doler", en: "to hurt / to ache", ja: "痛む" },
      { es: "curar", en: "to cure / to heal", ja: "治す" },
      { es: "respirar", en: "to breathe", ja: "呼吸する" },
      { es: "sudar", en: "to sweat", ja: "汗をかく" },
      { es: "temblar", en: "to tremble / to shiver", ja: "震える" },
      { es: "toser", en: "to cough", ja: "せきをする" },
      { es: "estornudar", en: "to sneeze", ja: "くしゃみをする" },
      { es: "vomitar", en: "to vomit", ja: "吐く" },
      { es: "engordar", en: "to gain weight", ja: "太る" },
      { es: "adelgazar", en: "to lose weight", ja: "やせる" },
      { es: "envejecer", en: "to get old / to age", ja: "年をとる" },
      { es: "cumplir", en: "to turn (age) / to fulfill", ja: "(歳に)なる、果たす" },
      { es: "tardar", en: "to take (time)", ja: "時間がかかる" },
      { es: "durar", en: "to last", ja: "続く、持続する" },
      { es: "desear", en: "to wish / to desire", ja: "願う、望む" },
      { es: "odiar", en: "to hate", ja: "憎む、大嫌いである" },
      { es: "amar", en: "to love", ja: "愛する" },
      { es: "extrañar", en: "to miss (someone)", ja: "恋しく思う" },
      { es: "confiar", en: "to trust", ja: "信頼する" },
      { es: "respetar", en: "to respect", ja: "尊敬する、尊重する" },
      { es: "admirar", en: "to admire", ja: "感心する、憧れる" },
      { es: "perdonar", en: "to forgive", ja: "許す" },
      { es: "disculparse", en: "to apologize", ja: "謝る" },
      { es: "soler", en: "to usually do", ja: "いつも〜する、〜する習慣がある" },
      { es: "atreverse", en: "to dare", ja: "思い切って〜する" },
      { es: "apetecer", en: "to feel like", ja: "〜したい気分である" },
      { es: "reunirse", en: "to meet / to gather", ja: "集まる、会合する" },
    ],
  },
];
