// ¡Escucha! フレーズデータ — ネイティブがよく使う短いフレーズ 384本
// ※ ¡Hablemos! 本編に収録済みのフレーズは除外

const PHRASE_SECTIONS = [
  {
    cat: "あいづち・リアクション", icon: "😮",
    items: [
      { es: "¡Qué bueno!", en: "How nice! / That's great!", ja: "いいね!、よかった!" },
      { es: "¡Anda!", en: "Wow! / No way!", ja: "おや!、へえ!" },
      { es: "¡Vaya!", en: "Wow! / Oh my!", ja: "うわあ、なんと" },
      { es: "¡Venga ya!", en: "Come on! / No way!", ja: "まさか!、うそでしょ!" },
      { es: "¡No puede ser!", en: "It can't be!", ja: "ありえない!" },
      { es: "¿De verdad?", en: "Really?", ja: "本当に?" },
      { es: "¿Ah, sí?", en: "Oh, really?", ja: "あ、そうなの?" },
      { es: "¡Qué fuerte!", en: "That's crazy!", ja: "すごい!、衝撃!" },
      { es: "¡Qué raro!", en: "How strange!", ja: "変なの!、おかしいな" },
      { es: "¡Qué suerte!", en: "How lucky!", ja: "ラッキーだね!" },
      { es: "¡Qué mala suerte!", en: "What bad luck!", ja: "ついてないね!" },
      { es: "¡Qué lástima!", en: "What a shame!", ja: "残念!" },
      { es: "¡Qué alegría!", en: "What a joy!", ja: "うれしい!" },
      { es: "¡Qué sorpresa!", en: "What a surprise!", ja: "びっくり!" },
      { es: "¡Qué susto!", en: "What a scare!", ja: "びっくりした!、怖かった!" },
      { es: "¡Qué asco!", en: "How gross!", ja: "気持ち悪い!、最悪!" },
      { es: "¡Qué rollo!", en: "What a drag!", ja: "めんどくさい!、退屈!" },
      { es: "¡Qué lío!", en: "What a mess!", ja: "ややこしい!、大変だ!" },
      { es: "¡Menos mal!", en: "Thank goodness!", ja: "よかった!、助かった!" },
      { es: "¡Madre mía!", en: "Oh my goodness!", ja: "なんてこった!" },
      { es: "¡Dios mío!", en: "My God!", ja: "ああ、神様!、なんてこと!" },
      { es: "¡Ojo!", en: "Watch out! / Careful!", ja: "気をつけて!、注意!" },
      { es: "Ya está.", en: "Done. / That's it.", ja: "できた、これで終わり" },
      { es: "Eso es.", en: "That's it. / Exactly.", ja: "そうそう、その通り" },
      { es: "¿Y eso?", en: "How come? / Why's that?", ja: "なんで?、どうして?" },
      { es: "No me lo puedo creer.", en: "I can't believe it.", ja: "信じられない" },
      { es: "Es una broma, ¿no?", en: "It's a joke, right?", ja: "冗談でしょ?" },
      { es: "¿Me tomas el pelo?", en: "Are you kidding me?", ja: "からかってるの?" },
      { es: "¡Qué risa!", en: "How funny!", ja: "ウケる!、笑える!" },
      { es: "¡Ni hablar!", en: "No way!", ja: "絶対だめ!、とんでもない!" },
      { es: "¡Para nada!", en: "Not at all!", ja: "全然そんなことない!" },
      { es: "¡Cómo no!", en: "Of course!", ja: "もちろん!" },
      { es: "Ya lo sé.", en: "I know.", ja: "知ってるよ、わかってる" },
      { es: "No lo sabía.", en: "I didn't know that.", ja: "知らなかった" },
      { es: "Tiene sentido.", en: "That makes sense.", ja: "なるほど、筋が通ってる" },
    ],
  },
  {
    cat: "日常のひとこと", icon: "💬",
    items: [
      { es: "Vamos.", en: "Let's go.", ja: "行こう" },
      { es: "¡Vámonos!", en: "Let's get going!", ja: "さあ行こう!" },
      { es: "Ya voy.", en: "I'm coming.", ja: "今行くよ" },
      { es: "Ahora vuelvo.", en: "I'll be right back.", ja: "すぐ戻るね" },
      { es: "Espera un poco.", en: "Wait a bit.", ja: "ちょっと待って" },
      { es: "Date prisa.", en: "Hurry up.", ja: "急いで" },
      { es: "Tranquilo.", en: "Relax. / Calm down.", ja: "落ち着いて" },
      { es: "Con calma.", en: "Take it easy.", ja: "焦らずに、ゆっくりね" },
      { es: "Sin prisa.", en: "No rush.", ja: "急がなくていいよ" },
      { es: "Como quieras.", en: "As you like.", ja: "好きにしていいよ" },
      { es: "Da igual.", en: "It doesn't matter.", ja: "どっちでもいい" },
      { es: "No importa.", en: "It doesn't matter. / Never mind.", ja: "気にしないで、構わない" },
      { es: "Lo que sea.", en: "Whatever.", ja: "何でもいいよ" },
      { es: "Yo también.", en: "Me too.", ja: "私も" },
      { es: "Yo tampoco.", en: "Me neither.", ja: "私も(〜ない)" },
      { es: "Yo sí.", en: "I do.", ja: "私はそうだよ" },
      { es: "Yo no.", en: "Not me.", ja: "私は違うよ" },
      { es: "Está bien.", en: "It's fine. / OK.", ja: "いいよ、大丈夫" },
      { es: "De acuerdo.", en: "All right. / Agreed.", ja: "了解、わかった" },
      { es: "Por supuesto.", en: "Of course.", ja: "もちろん" },
      { es: "Claro que sí.", en: "Of course!", ja: "もちろんだよ!" },
      { es: "Claro que no.", en: "Of course not.", ja: "もちろん違うよ" },
      { es: "Sin problema.", en: "No problem.", ja: "問題ないよ" },
      { es: "No pasa nada.", en: "It's OK. / No worries.", ja: "大丈夫、何でもないよ" },
      { es: "Así es la vida.", en: "That's life.", ja: "人生そんなもの" },
      { es: "Es lo que hay.", en: "It is what it is.", ja: "仕方ない、これが現実" },
      { es: "Ya veremos.", en: "We'll see.", ja: "そのうちわかるよ、様子を見よう" },
      { es: "Quién sabe.", en: "Who knows.", ja: "さあね、誰にもわからない" },
      { es: "Puede ser.", en: "Maybe. / Could be.", ja: "かもね" },
      { es: "A lo mejor.", en: "Maybe. / Perhaps.", ja: "もしかしたら" },
      { es: "Ni idea.", en: "No idea.", ja: "さっぱりわからない" },
      { es: "No sé.", en: "I don't know.", ja: "わからない" },
      { es: "No estoy seguro.", en: "I'm not sure.", ja: "確信がない、どうかな" },
      { es: "Se me olvidó.", en: "I forgot.", ja: "忘れちゃった" },
      { es: "Ahora caigo.", en: "Now I get it.", ja: "ああ、今わかった" },
      { es: "Ya me acuerdo.", en: "Now I remember.", ja: "思い出した" },
      { es: "Estoy de camino.", en: "I'm on my way.", ja: "今向かってる" },
      { es: "Ya casi llego.", en: "I'm almost there.", ja: "もうすぐ着く" },
      { es: "¿Qué pasa?", en: "What's up? / What's wrong?", ja: "どうしたの?" },
      { es: "No es para tanto.", en: "It's not a big deal.", ja: "大したことないよ" },
      { es: "Trato hecho.", en: "It's a deal.", ja: "商談成立、決まりだね" },
    ],
  },
  {
    cat: "気持ち・感想", icon: "❤️",
    items: [
      { es: "Me encanta.", en: "I love it.", ja: "大好き、すごく気に入った" },
      { es: "Me gusta mucho.", en: "I like it a lot.", ja: "とても好き" },
      { es: "No me gusta nada.", en: "I don't like it at all.", ja: "全然好きじゃない" },
      { es: "Lo odio.", en: "I hate it.", ja: "大嫌い" },
      { es: "Estoy muy contento.", en: "I'm very happy.", ja: "とてもうれしい" },
      { es: "Estoy emocionado.", en: "I'm excited.", ja: "わくわくしてる" },
      { es: "Estoy de buen humor.", en: "I'm in a good mood.", ja: "機嫌がいい" },
      { es: "Estoy de mal humor.", en: "I'm in a bad mood.", ja: "機嫌が悪い" },
      { es: "Tengo sueño.", en: "I'm sleepy.", ja: "眠い" },
      { es: "Tengo frío.", en: "I'm cold.", ja: "寒い" },
      { es: "Tengo calor.", en: "I'm hot.", ja: "暑い" },
      { es: "Tengo miedo.", en: "I'm scared.", ja: "怖い" },
      { es: "Tengo prisa.", en: "I'm in a hurry.", ja: "急いでる" },
      { es: "Estoy agotado.", en: "I'm exhausted.", ja: "くたくただ" },
      { es: "Estoy hecho polvo.", en: "I'm worn out.", ja: "疲れ果てた、ボロボロだ" },
      { es: "Me muero de hambre.", en: "I'm starving.", ja: "お腹ぺこぺこ" },
      { es: "Me muero de sueño.", en: "I'm dying of sleepiness.", ja: "眠くて死にそう" },
      { es: "Está buenísimo.", en: "It's really good (food).", ja: "めちゃくちゃおいしい" },
      { es: "Huele muy bien.", en: "It smells really good.", ja: "すごくいい匂い" },
      { es: "Suena bien.", en: "Sounds good.", ja: "いいね、よさそう" },
      { es: "Me suena.", en: "It rings a bell.", ja: "聞き覚えがある" },
      { es: "No me suena.", en: "It doesn't ring a bell.", ja: "聞いたことないな" },
      { es: "Qué gusto verte.", en: "So nice to see you.", ja: "会えてうれしい" },
      { es: "Me alegro por ti.", en: "I'm happy for you.", ja: "よかったね(あなたのために)" },
      { es: "Me alegro mucho.", en: "I'm very glad.", ja: "本当によかった" },
      { es: "Lo siento mucho.", en: "I'm very sorry.", ja: "本当にごめんなさい、お気の毒に" },
      { es: "Qué vergüenza.", en: "How embarrassing.", ja: "恥ずかしい" },
      { es: "Estoy orgulloso de ti.", en: "I'm proud of you.", ja: "君を誇りに思う" },
      { es: "Te lo mereces.", en: "You deserve it.", ja: "当然の報いだよ、頑張ったもんね" },
      { es: "No aguanto más.", en: "I can't take it anymore.", ja: "もう我慢できない" },
      { es: "Estoy harto.", en: "I'm fed up.", ja: "うんざりだ" },
      { es: "Me vuelve loco.", en: "It drives me crazy. / I'm crazy about it.", ja: "夢中になる、イライラさせられる" },
      { es: "Me hace ilusión.", en: "I'm looking forward to it.", ja: "楽しみ、わくわくする" },
      { es: "No me lo esperaba.", en: "I didn't expect that.", ja: "予想してなかった" },
      { es: "Qué alivio.", en: "What a relief.", ja: "ほっとした" },
      { es: "¡Qué detalle!", en: "How thoughtful!", ja: "気が利くね!、優しい!" },
    ],
  },
  {
    cat: "お願い・提案", icon: "🙏",
    items: [
      { es: "¿Me ayudas?", en: "Can you help me?", ja: "手伝ってくれる?" },
      { es: "¿Me haces un favor?", en: "Can you do me a favor?", ja: "お願いがあるんだけど" },
      { es: "¿Puedo?", en: "May I?", ja: "いい?、してもいい?" },
      { es: "¿Se puede?", en: "May I come in? / Is it allowed?", ja: "入っていい?、いいですか?" },
      { es: "Pasa, pasa.", en: "Come in, come in.", ja: "どうぞどうぞ、入って" },
      { es: "Adelante.", en: "Go ahead. / Come in.", ja: "どうぞ、お先に" },
      { es: "Toma.", en: "Here you go.", ja: "はい、どうぞ" },
      { es: "¿Me lo das?", en: "Can you give it to me?", ja: "それちょうだい" },
      { es: "¿Me lo prestas?", en: "Can you lend it to me?", ja: "貸してくれる?" },
      { es: "¿Me dejas ver?", en: "Can I see?", ja: "見せてくれる?" },
      { es: "Mira esto.", en: "Look at this.", ja: "これ見て" },
      { es: "Ven aquí.", en: "Come here.", ja: "こっちに来て" },
      { es: "Ven conmigo.", en: "Come with me.", ja: "一緒に来て" },
      { es: "¿Vamos juntos?", en: "Shall we go together?", ja: "一緒に行く?" },
      { es: "¿Quieres venir?", en: "Do you want to come?", ja: "来たい?、来る?" },
      { es: "¿Te apuntas?", en: "Are you in?", ja: "参加する?、乗る?" },
      { es: "¿Te apetece?", en: "Do you feel like it?", ja: "気が向く?、どう?" },
      { es: "¿Qué te parece?", en: "What do you think?", ja: "どう思う?" },
      { es: "¿Te parece bien?", en: "Is that OK with you?", ja: "それでいい?" },
      { es: "Como tú digas.", en: "Whatever you say.", ja: "君の言う通りに" },
      { es: "Te invito.", en: "It's on me. / My treat.", ja: "おごるよ" },
      { es: "¿Probamos?", en: "Shall we try?", ja: "試してみる?" },
      { es: "Inténtalo.", en: "Try it. / Give it a try.", ja: "やってみて" },
      { es: "Prueba esto.", en: "Try this.", ja: "これ試してみて、食べてみて" },
      { es: "Dímelo.", en: "Tell me.", ja: "言って、教えて" },
      { es: "Cuéntame.", en: "Tell me about it.", ja: "聞かせて、話して" },
      { es: "Escúchame.", en: "Listen to me.", ja: "聞いて" },
      { es: "Espérame.", en: "Wait for me.", ja: "待ってて" },
      { es: "No te vayas.", en: "Don't go.", ja: "行かないで" },
      { es: "Quédate.", en: "Stay.", ja: "いてよ、残って" },
      { es: "Sígueme.", en: "Follow me.", ja: "ついて来て" },
      { es: "Ayúdame.", en: "Help me.", ja: "助けて、手伝って" },
      { es: "Déjame en paz.", en: "Leave me alone.", ja: "ほっといて" },
      { es: "Déjame pensar.", en: "Let me think.", ja: "考えさせて" },
      { es: "No lo toques.", en: "Don't touch it.", ja: "触らないで" },
    ],
  },
  {
    cat: "賛成・反対・意見", icon: "🗣",
    items: [
      { es: "Estoy de acuerdo.", en: "I agree.", ja: "賛成、同意見だよ" },
      { es: "Totalmente.", en: "Totally.", ja: "完全に、まったくその通り" },
      { es: "Es verdad.", en: "It's true.", ja: "本当だ、確かに" },
      { es: "Es cierto.", en: "That's right.", ja: "その通り、確かに" },
      { es: "Es mentira.", en: "That's a lie.", ja: "嘘だよ" },
      { es: "Eso creo.", en: "I think so.", ja: "そう思う" },
      { es: "Creo que no.", en: "I don't think so.", ja: "違うと思う" },
      { es: "Supongo que sí.", en: "I suppose so.", ja: "たぶんそうだと思う" },
      { es: "Puede que sí.", en: "Maybe yes.", ja: "そうかもしれない" },
      { es: "Pienso lo mismo.", en: "I think the same.", ja: "同感だよ" },
      { es: "Yo lo veo así.", en: "That's how I see it.", ja: "私はそう見てる" },
      { es: "No lo veo claro.", en: "I'm not convinced.", ja: "はっきりしないな、微妙だな" },
      { es: "En absoluto.", en: "Absolutely not.", ja: "全然、決して" },
      { es: "De ninguna manera.", en: "No way.", ja: "絶対にだめ" },
      { es: "Ni de broma.", en: "Not even as a joke. / No way.", ja: "冗談でも無理" },
      { es: "Por mí, bien.", en: "Fine by me.", ja: "私はそれでいいよ" },
      { es: "Me parece bien.", en: "Sounds good to me.", ja: "いいと思う" },
      { es: "Me parece mal.", en: "I don't think it's right.", ja: "よくないと思う" },
      { es: "No tiene sentido.", en: "It makes no sense.", ja: "意味がわからない、筋が通らない" },
      { es: "Es buena idea.", en: "It's a good idea.", ja: "いい考えだね" },
      { es: "Mala idea.", en: "Bad idea.", ja: "やめた方がいい" },
      { es: "¿Tú qué crees?", en: "What do you think?", ja: "君はどう思う?" },
      { es: "En mi opinión...", en: "In my opinion...", ja: "私の意見では…" },
      { es: "Si tú lo dices.", en: "If you say so.", ja: "君がそう言うなら" },
      { es: "Ya, pero...", en: "Yeah, but...", ja: "うん、でもね…" },
      { es: "Eso mismo.", en: "Exactly that.", ja: "まさにそれ" },
      { es: "Estoy a favor.", en: "I'm in favor.", ja: "賛成です" },
      { es: "Estoy en contra.", en: "I'm against it.", ja: "反対です" },
      { es: "No sé qué decir.", en: "I don't know what to say.", ja: "何と言えばいいか" },
      { es: "Buena pregunta.", en: "Good question.", ja: "いい質問だね" },
    ],
  },
  {
    cat: "質問・聞き返し", icon: "❓",
    items: [
      { es: "¿Cómo?", en: "What? / Pardon?", ja: "え?、何て?" },
      { es: "¿Qué has dicho?", en: "What did you say?", ja: "何て言ったの?" },
      { es: "¿Perdona?", en: "Sorry? / Excuse me?", ja: "すみません、何て?" },
      { es: "¿Cómo se llama esto?", en: "What is this called?", ja: "これは何て言うの?" },
      { es: "¿Qué es esto?", en: "What is this?", ja: "これは何?" },
      { es: "¿Dónde está?", en: "Where is it?", ja: "どこにあるの?" },
      { es: "¿Dónde estás?", en: "Where are you?", ja: "どこにいるの?" },
      { es: "¿Adónde vas?", en: "Where are you going?", ja: "どこに行くの?" },
      { es: "¿De dónde vienes?", en: "Where are you coming from?", ja: "どこから来たの?" },
      { es: "¿Cuándo?", en: "When?", ja: "いつ?" },
      { es: "¿Desde cuándo?", en: "Since when?", ja: "いつから?" },
      { es: "¿Hasta cuándo?", en: "Until when?", ja: "いつまで?" },
      { es: "¿Por qué?", en: "Why?", ja: "なぜ?、どうして?" },
      { es: "¿Por qué no?", en: "Why not?", ja: "なんでだめなの?、いいじゃん" },
      { es: "¿Para qué?", en: "What for?", ja: "何のために?" },
      { es: "¿Con quién?", en: "With whom?", ja: "誰と?" },
      { es: "¿Quién es?", en: "Who is it?", ja: "誰?、どなたですか?" },
      { es: "¿Cuál prefieres?", en: "Which one do you prefer?", ja: "どっちが好き?" },
      { es: "¿Cuánto tiempo?", en: "How long?", ja: "どのくらいの時間?" },
      { es: "¿Cuántas veces?", en: "How many times?", ja: "何回?" },
      { es: "¿Qué más?", en: "What else?", ja: "他には?" },
      { es: "¿Algo más?", en: "Anything else?", ja: "他に何か?" },
      { es: "¿Cómo funciona?", en: "How does it work?", ja: "どうやって使うの?" },
      { es: "¿Qué quiere decir?", en: "What does it mean?", ja: "どういう意味?" },
      { es: "¿Me entiendes?", en: "Do you understand me?", ja: "わかる?、伝わってる?" },
      { es: "¿Me explico?", en: "Am I making sense?", ja: "説明伝わってるかな?" },
      { es: "¿Me oyes bien?", en: "Can you hear me well?", ja: "ちゃんと聞こえてる?" },
      { es: "¿Verdad?", en: "Right?", ja: "でしょ?、だよね?" },
      { es: "¿No crees?", en: "Don't you think?", ja: "そう思わない?" },
      { es: "¿Estás seguro?", en: "Are you sure?", ja: "本当に?、確かなの?" },
      { es: "¿Listo?", en: "Ready?", ja: "準備できた?" },
      { es: "¿Todo bien?", en: "Everything OK?", ja: "全部順調?、大丈夫?" },
      { es: "¿Qué necesitas?", en: "What do you need?", ja: "何が必要?" },
      { es: "¿En qué puedo ayudarte?", en: "How can I help you?", ja: "何かお手伝いしましょうか?" },
    ],
  },
  {
    cat: "あいさつ・社交", icon: "🤝",
    items: [
      { es: "¡Buenas!", en: "Hi! / Hello!", ja: "どうも!、こんにちは!" },
      { es: "¿Qué hay?", en: "What's up?", ja: "調子どう?、やあ" },
      { es: "¿Cómo te va?", en: "How's it going?", ja: "調子はどう?" },
      { es: "¿Cómo van las cosas?", en: "How are things?", ja: "最近どう?" },
      { es: "¿Qué es de tu vida?", en: "What have you been up to?", ja: "最近何してるの?" },
      { es: "Cuánto tiempo.", en: "Long time no see.", ja: "久しぶりだね" },
      { es: "Me alegro de verte.", en: "Glad to see you.", ja: "会えてうれしいよ" },
      { es: "Igualmente.", en: "Likewise. / Same to you.", ja: "こちらこそ、あなたもね" },
      { es: "Encantado.", en: "Pleased to meet you.", ja: "はじめまして(男性)" },
      { es: "Es un placer.", en: "It's a pleasure.", ja: "光栄です、うれしいです" },
      { es: "El gusto es mío.", en: "The pleasure is mine.", ja: "こちらこそ" },
      { es: "Bienvenido.", en: "Welcome.", ja: "ようこそ" },
      { es: "Pásate cuando quieras.", en: "Drop by whenever you want.", ja: "いつでも寄ってね" },
      { es: "Saluda a tu familia.", en: "Say hi to your family.", ja: "家族によろしくね" },
      { es: "Dale recuerdos.", en: "Give them my regards.", ja: "よろしく伝えてね" },
      { es: "Feliz cumpleaños.", en: "Happy birthday.", ja: "誕生日おめでとう" },
      { es: "Feliz Navidad.", en: "Merry Christmas.", ja: "メリークリスマス" },
      { es: "Feliz Año Nuevo.", en: "Happy New Year.", ja: "あけましておめでとう" },
      { es: "Felices fiestas.", en: "Happy holidays.", ja: "よい祝日を" },
      { es: "Buen viaje.", en: "Have a good trip.", ja: "よい旅を" },
      { es: "Buen fin de semana.", en: "Have a good weekend.", ja: "よい週末を" },
      { es: "Que descanses.", en: "Rest well. / Sleep well.", ja: "ゆっくり休んでね" },
      { es: "Que te mejores.", en: "Get well soon.", ja: "お大事に" },
      { es: "Que aproveche.", en: "Enjoy your meal.", ja: "召し上がれ、どうぞごゆっくり" },
      { es: "Que vaya bien.", en: "Hope it goes well.", ja: "うまくいきますように、お元気で" },
      { es: "Que lo pases bien.", en: "Have a good time.", ja: "楽しんでね" },
      { es: "Hasta ahora.", en: "See you in a bit.", ja: "またすぐにね" },
      { es: "Hasta pronto.", en: "See you soon.", ja: "また近いうちに" },
      { es: "Hasta la próxima.", en: "Until next time.", ja: "また今度" },
      { es: "Cuídate.", en: "Take care.", ja: "体に気をつけてね" },
      { es: "Con permiso.", en: "Excuse me (passing).", ja: "失礼します、ちょっと通ります" },
      { es: "Disculpe.", en: "Excuse me (formal).", ja: "すみません(丁寧)" },
      { es: "Perdón por llegar tarde.", en: "Sorry for being late.", ja: "遅れてごめんなさい" },
      { es: "Gracias por todo.", en: "Thanks for everything.", ja: "いろいろありがとう" },
      { es: "Muchísimas gracias.", en: "Thank you so much.", ja: "本当にありがとう" },
      { es: "No hay de qué.", en: "Don't mention it.", ja: "どういたしまして、お礼には及ばないよ" },
    ],
  },
  {
    cat: "食事・カフェ・バル", icon: "🍻",
    items: [
      { es: "¿Tienes hambre?", en: "Are you hungry?", ja: "お腹すいた?" },
      { es: "¿Ya comiste?", en: "Did you eat already?", ja: "もうご飯食べた?" },
      { es: "¿Qué hay de comer?", en: "What's for lunch/dinner?", ja: "ご飯何?" },
      { es: "¡A comer!", en: "Time to eat!", ja: "ご飯だよ!" },
      { es: "Está caliente.", en: "It's hot.", ja: "熱いよ" },
      { es: "Pica un poco.", en: "It's a bit spicy.", ja: "ちょっと辛い" },
      { es: "¿Quieres probar?", en: "Do you want to try?", ja: "食べてみる?" },
      { es: "Un poquito más.", en: "A little more.", ja: "もうちょっとだけ" },
      { es: "Estoy lleno.", en: "I'm full.", ja: "お腹いっぱい" },
      { es: "No puedo más.", en: "I can't eat any more.", ja: "もう無理、限界" },
      { es: "Para mí, lo mismo.", en: "The same for me.", ja: "私も同じものを" },
      { es: "Una caña, por favor.", en: "A small beer, please.", ja: "生ビールひとつください" },
      { es: "Un café, por favor.", en: "A coffee, please.", ja: "コーヒーひとつください" },
      { es: "Para llevar, por favor.", en: "To go, please.", ja: "持ち帰りでお願いします" },
      { es: "Para tomar aquí.", en: "For here.", ja: "店内で食べます" },
      { es: "¿Me cobras?", en: "Can I pay?", ja: "お会計お願い" },
      { es: "¿Cuánto te debo?", en: "How much do I owe you?", ja: "いくら払えばいい?" },
      { es: "Pagamos a medias.", en: "Let's split the bill.", ja: "割り勘にしよう" },
      { es: "Otra ronda, por favor.", en: "Another round, please.", ja: "もう一杯ずつください" },
      { es: "¡Salud!", en: "Cheers!", ja: "乾杯!" },
      { es: "¿Está libre esta mesa?", en: "Is this table free?", ja: "この席空いてますか?" },
      { es: "¿Hay sitio?", en: "Is there room?", ja: "席ありますか?" },
      { es: "Sin hielo, por favor.", en: "No ice, please.", ja: "氷なしでお願いします" },
      { es: "Sin picante, por favor.", en: "Not spicy, please.", ja: "辛くしないでください" },
      { es: "Soy alérgico.", en: "I'm allergic.", ja: "アレルギーがあります" },
      { es: "No como carne.", en: "I don't eat meat.", ja: "肉は食べません" },
      { es: "¿Qué lleva este plato?", en: "What's in this dish?", ja: "この料理何が入ってますか?" },
      { es: "Está en su punto.", en: "It's just right.", ja: "ちょうどいい、絶妙" },
      { es: "Le falta sal.", en: "It needs salt.", ja: "塩が足りない" },
      { es: "Invita la casa.", en: "It's on the house.", ja: "お店のおごりです" },
    ],
  },
  {
    cat: "買い物・お店", icon: "🛍",
    items: [
      { es: "¿A cuánto está?", en: "How much is it (per unit)?", ja: "(単価は)いくらですか?" },
      { es: "¿Cuánto vale?", en: "How much is it worth?", ja: "いくらしますか?" },
      { es: "Es una ganga.", en: "It's a bargain.", ja: "お買い得だよ" },
      { es: "Está de oferta.", en: "It's on sale.", ja: "セール中だよ" },
      { es: "¿Tiene otro color?", en: "Do you have another color?", ja: "他の色はありますか?" },
      { es: "¿Tiene otra talla?", en: "Do you have another size?", ja: "他のサイズはありますか?" },
      { es: "¿Me lo puedo probar?", en: "Can I try it on?", ja: "試着してもいいですか?" },
      { es: "¿Dónde está el probador?", en: "Where is the fitting room?", ja: "試着室はどこですか?" },
      { es: "Me queda bien.", en: "It fits me well.", ja: "ぴったり、似合ってる" },
      { es: "Me queda pequeño.", en: "It's too small for me.", ja: "小さすぎる" },
      { es: "Me queda grande.", en: "It's too big for me.", ja: "大きすぎる" },
      { es: "No me convence.", en: "I'm not convinced.", ja: "いまいちピンとこない" },
      { es: "Me lo pienso.", en: "I'll think about it.", ja: "ちょっと考えます" },
      { es: "Vuelvo luego.", en: "I'll come back later.", ja: "また後で来ます" },
      { es: "¿Hasta qué hora abren?", en: "Until what time are you open?", ja: "何時まで開いてますか?" },
      { es: "¿A qué hora cierran?", en: "What time do you close?", ja: "何時に閉まりますか?" },
      { es: "Está agotado.", en: "It's sold out.", ja: "売り切れです" },
      { es: "¿Queda alguno?", en: "Are there any left?", ja: "まだ残ってますか?" },
      { es: "Quisiera devolver esto.", en: "I'd like to return this.", ja: "これを返品したいのですが" },
      { es: "¿Me da una bolsa?", en: "Can I have a bag?", ja: "袋をもらえますか?" },
      { es: "El recibo, por favor.", en: "The receipt, please.", ja: "レシートをください" },
      { es: "¿Aceptan tarjeta?", en: "Do you take cards?", ja: "カードは使えますか?" },
      { es: "En efectivo.", en: "In cash.", ja: "現金で" },
      { es: "Quédese con el cambio.", en: "Keep the change.", ja: "おつりは取っておいてください" },
      { es: "Nada más, gracias.", en: "That's all, thanks.", ja: "以上です、ありがとう" },
    ],
  },
  {
    cat: "外出・移動", icon: "🚶",
    items: [
      { es: "¿Dónde estamos?", en: "Where are we?", ja: "ここはどこ?" },
      { es: "Estamos cerca.", en: "We're close.", ja: "もうすぐ近くだよ" },
      { es: "Todavía queda un poco.", en: "There's still a bit to go.", ja: "まだもう少しある" },
      { es: "Es por aquí.", en: "It's this way.", ja: "こっちだよ" },
      { es: "Es por allí.", en: "It's that way.", ja: "あっちだよ" },
      { es: "Gira a la derecha.", en: "Turn right.", ja: "右に曲がって" },
      { es: "Gira a la izquierda.", en: "Turn left.", ja: "左に曲がって" },
      { es: "En la esquina.", en: "At the corner.", ja: "角のところで" },
      { es: "Al final de la calle.", en: "At the end of the street.", ja: "通りの突き当たりに" },
      { es: "¿Me llevas?", en: "Can you give me a ride?", ja: "乗せてってくれる?" },
      { es: "Te llevo.", en: "I'll give you a ride.", ja: "送っていくよ" },
      { es: "Voy andando.", en: "I'm walking there.", ja: "歩いて行くよ" },
      { es: "Cojo el metro.", en: "I'll take the subway.", ja: "地下鉄で行く" },
      { es: "Pido un taxi.", en: "I'll call a taxi.", ja: "タクシーを呼ぶね" },
      { es: "¿Dónde aparco?", en: "Where do I park?", ja: "どこに停めればいい?" },
      { es: "Hay mucho tráfico.", en: "There's a lot of traffic.", ja: "渋滞してる" },
      { es: "¿Nos vamos?", en: "Shall we go?", ja: "そろそろ行く?" },
      { es: "Vamos tarde.", en: "We're running late.", ja: "遅れてるよ" },
      { es: "Llegamos a tiempo.", en: "We made it on time.", ja: "間に合った" },
      { es: "Acabo de llegar.", en: "I just arrived.", ja: "今着いたところ" },
      { es: "¿Falta mucho?", en: "Is it much farther?", ja: "まだかかる?" },
      { es: "Ya falta poco.", en: "Almost there.", ja: "もう少しだよ" },
      { es: "Estamos llegando.", en: "We're arriving.", ja: "もうすぐ着くよ" },
      { es: "Aquí es.", en: "This is it. / Here it is.", ja: "ここだよ" },
      { es: "Para aquí, por favor.", en: "Stop here, please.", ja: "ここで停めてください" },
      { es: "Con cuidado.", en: "Carefully. / Be careful.", ja: "気をつけてね" },
    ],
  },
  {
    cat: "時間・予定", icon: "⏰",
    items: [
      { es: "¿Tienes tiempo?", en: "Do you have time?", ja: "時間ある?" },
      { es: "¿Estás libre hoy?", en: "Are you free today?", ja: "今日空いてる?" },
      { es: "¿Qué planes tienes?", en: "What are your plans?", ja: "どんな予定?" },
      { es: "¿Quedamos?", en: "Shall we meet up?", ja: "会わない?、集まらない?" },
      { es: "¿A qué hora quedamos?", en: "What time shall we meet?", ja: "何時に待ち合わせる?" },
      { es: "¿Dónde quedamos?", en: "Where shall we meet?", ja: "どこで待ち合わせる?" },
      { es: "Quedamos a las ocho.", en: "Let's meet at eight.", ja: "8時に待ち合わせね" },
      { es: "¿Te viene bien?", en: "Does that work for you?", ja: "都合いい?" },
      { es: "Me viene bien.", en: "That works for me.", ja: "都合いいよ" },
      { es: "Me viene mal.", en: "That doesn't work for me.", ja: "都合が悪い" },
      { es: "Otro día mejor.", en: "Better another day.", ja: "別の日の方がいいな" },
      { es: "Lo dejamos para mañana.", en: "Let's leave it for tomorrow.", ja: "明日にしよう" },
      { es: "Cambio de planes.", en: "Change of plans.", ja: "予定変更" },
      { es: "Se me hace tarde.", en: "I'm running late.", ja: "遅くなっちゃう" },
      { es: "Ya es hora.", en: "It's time.", ja: "もう時間だ" },
      { es: "Es hora de irse.", en: "It's time to go.", ja: "帰る時間だ" },
      { es: "Aún es pronto.", en: "It's still early.", ja: "まだ早いよ" },
      { es: "No hay prisa.", en: "There's no rush.", ja: "急がなくていい" },
      { es: "Tómate tu tiempo.", en: "Take your time.", ja: "ゆっくりでいいよ" },
      { es: "Dame un segundo.", en: "Give me a second.", ja: "ちょっと待って" },
      { es: "Dame cinco minutos.", en: "Give me five minutes.", ja: "5分ちょうだい" },
      { es: "En un rato.", en: "In a bit.", ja: "少ししたら" },
      { es: "Dentro de poco.", en: "Soon / shortly.", ja: "まもなく" },
      { es: "Hace un rato.", en: "A while ago.", ja: "さっき" },
      { es: "Hace mucho tiempo.", en: "A long time ago.", ja: "ずいぶん前に" },
      { es: "De momento, no.", en: "Not for now.", ja: "今のところはまだ" },
      { es: "Por ahora, bien.", en: "So far, so good.", ja: "今のところ順調" },
      { es: "Cuanto antes, mejor.", en: "The sooner, the better.", ja: "早ければ早いほどいい" },
      { es: "A última hora.", en: "At the last minute.", ja: "ぎりぎりに、土壇場で" },
      { es: "En punto.", en: "On the dot / sharp.", ja: "ちょうど(〜時)ぴったり" },
      { es: "Todo el día.", en: "All day.", ja: "一日中" },
      { es: "Toda la noche.", en: "All night.", ja: "一晩中" },
    ],
  },
  {
    cat: "励まし・お祝い", icon: "🎉",
    items: [
      { es: "¡Ánimo!", en: "Cheer up! / You can do it!", ja: "元気出して!、頑張って!" },
      { es: "¡Tú puedes!", en: "You can do it!", ja: "君ならできる!" },
      { es: "¡A por ello!", en: "Go for it!", ja: "さあやろう!、いけ!" },
      { es: "¡Buena suerte!", en: "Good luck!", ja: "幸運を祈る!、頑張って!" },
      { es: "Todo saldrá bien.", en: "Everything will be fine.", ja: "きっとうまくいくよ" },
      { es: "No te rindas.", en: "Don't give up.", ja: "あきらめないで" },
      { es: "Sigue así.", en: "Keep it up.", ja: "その調子!" },
      { es: "Lo estás haciendo muy bien.", en: "You're doing great.", ja: "すごく上手にできてるよ" },
      { es: "Cada vez mejor.", en: "Better and better.", ja: "どんどん良くなってる" },
      { es: "¡Bien hecho!", en: "Well done!", ja: "よくやった!" },
      { es: "¡Buen trabajo!", en: "Good job!", ja: "お疲れさま!、いい仕事!" },
      { es: "¡Enhorabuena!", en: "Congratulations!", ja: "おめでとう!" },
      { es: "¡Felicidades!", en: "Congratulations! / Best wishes!", ja: "おめでとう!" },
      { es: "Estoy contigo.", en: "I'm with you.", ja: "そばにいるよ、味方だよ" },
      { es: "Cuenta conmigo.", en: "Count on me.", ja: "任せて、頼っていいよ" },
      { es: "Aquí me tienes.", en: "I'm here for you.", ja: "私がついてるよ" },
      { es: "Lo conseguirás.", en: "You'll get it. / You'll make it.", ja: "きっとできるよ" },
      { es: "Confío en ti.", en: "I trust you.", ja: "信じてるよ" },
      { es: "Era broma.", en: "I was joking.", ja: "冗談だよ" },
      { es: "No es tu culpa.", en: "It's not your fault.", ja: "君のせいじゃないよ" },
      { es: "Olvídalo.", en: "Forget it.", ja: "気にしないで、忘れて" },
      { es: "Ya pasó.", en: "It's over now.", ja: "もう終わったこと、大丈夫" },
      { es: "Mejor imposible.", en: "Couldn't be better.", ja: "最高、これ以上ないくらい" },
      { es: "La próxima vez será.", en: "Next time it will happen.", ja: "次があるさ" },
    ],
  },
];
